Add Findora Chain
ethereum-lists/chains pull request #1013
Opened 2022-03-29 18:00 UTC by zqsun

This PR adds the details for the Findora Chain to chainlist. Findora Chain is an EVM chain with privacy features.

2022-03-30 05:02 UTC, ligi commented on _data/chains/eip155-2152.json
> +      "url": "https://evm.findorascan.io/",
```suggestion
      "url": "https://evm.findorascan.io",
```

2022-03-30 05:02 UTC, ligi commented on _data/chains/eip155-2153.json
> +      "url": "https://testnet-anvil.evm.findorascan.io/",
```suggestion
      "url": "https://testnet-anvil.evm.findorascan.io",
```

2022-03-30 05:03 UTC, ligi requested changes
shortNames must be unique

2022-04-02 03:34 UTC, DONALDSULLENDER approved these changes

2022-04-04 23:07 UTC, zqsun reviewed
Update the testnet short name

2022-04-12 15:57 UTC, closed without merging