add piecenetwork
ethereum-lists/chains pull request #1087
Opened 2022-04-19 16:29 UTC by piecenetwork

2022-04-20 07:53 UTC, ligi requested changes
I cannot get that IPFS CID - where did you pin it?

2022-04-23 13:54 UTC, piecenetwork commented
> I cannot get that IPFS CID - where did you pin it?

Hello, I have re-uploaded the logo file to IPFS and made public parsing

2022-04-23 15:33 UTC, piecenetwork commented
Hi, we have reapplied, please check



***@***.***
 
From: ligi
Date: 2022-04-20 15:53
To: ethereum-lists/chains
CC: piecenetwork; Author
Subject: Re: [ethereum-lists/chains] add piecenetwork (PR #1087)
@ligi requested changes on this pull request.
I cannot get that IPFS CID - where did you pin it?
―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-23 15:53 UTC, ligi approved these changes

2022-06-12 02:12 UTC, closed without merging