Add Candle (CNDL) Chain
ethereum-lists/chains pull request #1094
Opened 2022-04-21 06:14 UTC by samisbakedham

2022-04-21 09:06 UTC, ligi commented on _data/chains/eip155-534.json
> +        "https://rpc.cndlchain.com",
```suggestion
        "https://rpc.cndlchain.com"
```

2022-04-21 09:06 UTC, ligi requested changes
Please remove the comma to make it valid json

2022-04-21 09:07 UTC, samisbakedham commented
> Please remove the comma to make it valid json

Done thanks!

2022-04-21 09:28 UTC, ligi commented
I cannot get the IPFS CID - where did you pin it?

2022-04-21 09:34 UTC, samisbakedham commented
> I cannot get the IPFS CID - where did you pin it?

Piñata

2022-04-21 09:39 UTC, ligi requested changes
oh it took a bit longer to load. But the size seems to be off:

```
✓ ~/tmp identify QmRVVjhK4rBgRNXNX46YJG7epbDYfGXL3ERomrBkuG8nAu         11:37:14
QmRVVjhK4rBgRNXNX46YJG7epbDYfGXL3ERomrBkuG8nAu PNG 6385x5665 oh it took a bit longer to load. But the size seems to be off:

```
✓ ~/tmp identify QmRVVjhK4rBgRNXNX46YJG7epbDYfGXL3ERomrBkuG8nAu         11:37:14
QmRVVjhK4rBgRNXNX46YJG7epbDYfGXL3ERomrBkuG8nAu PNG 6385x5665 6385x56656385x5665+0+0 8-bit sRGB 852012B 0.000u 0:00.000

```

 6385x5665 is quite big and should not be the only icon - please provide a smaller one

2022-04-21 09:40 UTC, samisbakedham commented
> oh it took a bit longer to load. But the size seems to be off:
> 
> 
> 
> ```
> 
> ✓ ~/tmp identify QmRVVjhK4rBgRNXNX46YJG7epbDYfGXL3ERomrBkuG8nAu         11:37:14
> 
> QmRVVjhK4rBgRNXNX46YJG7epbDYfGXL3ERomrBkuG8nAu PNG 6385x5665 6385x56656385x5665+0+0 8-bit sRGB 852012B 0.000u 0:00.000
> 
> ```
> 
> 
> 
>  6385x5665 is quite big and should not be the only icon - please provide a smaller one 

Should I change it to a smaller size or add another icon? Thanks by the way

2022-04-21 10:13 UTC, samisbakedham commented
Fixed

2022-04-23 09:51 UTC, samisbakedham commented
> oh it took a bit longer to load. But the size seems to be off:
> 
> ```
> ✓ ~/tmp identify QmRVVjhK4rBgRNXNX46YJG7epbDYfGXL3ERomrBkuG8nAu         11:37:14
> QmRVVjhK4rBgRNXNX46YJG7epbDYfGXL3ERomrBkuG8nAu PNG 6385x5665 6385x56656385x5665+0+0 8-bit sRGB 852012B 0.000u 0:00.000
> ```
> 
> 6385x5665 is quite big and should not be the only icon - please provide a smaller one

All good to merge?

2022-04-24 02:37 UTC, samisbakedham commented
@ligi

2022-04-24 07:02 UTC, ligi commented
did you pin the smaller size? Trying to get this CID since 30min - no luck

2022-04-24 07:59 UTC, samisbakedham commented
> did you pin the smaller size? Trying to get this CID since 30min - no luck

Shoot, I'll check! Apologies for using your time in a wasteful manner, I'll get ON this ASAP

2022-04-24 10:38 UTC, samisbakedham commented
> did you pin the smaller size? Trying to get this CID since 30min - no luck

Try now!

2022-04-24 10:41 UTC, samisbakedham commented
Yup, tested again and it shows up, should be okay now. Check the link [here](https://cloudflare-ipfs.com/ipfs/Qmbe3ChumXNRfHcLsNBY2APRrGxkFWP68Nb35MaKMRfPye)

2022-04-25 02:13 UTC, samisbakedham commented
Running `Ipfs get Qmbe3ChumXNRfHcLsNBY2APRrGxkFWP68Nb35MaKMRfPye` seems to work as well I think. Attached image shows the result, if you'd like to try again @ligi ? ![image](https://user-images.githubusercontent.com/60489622/165009441-c00e3259-1cdd-46e8-978b-92493dcf22a5.png)

2022-04-30 03:22 UTC, samisbakedham commented
Any updates @ligi ?

2022-04-30 18:06 UTC, ligi commented
I could get the image now - but your explorer is not accessible

2022-04-30 23:41 UTC, samisbakedham commented
> I could get the image now - but your explorer is not accessible

Routine maintenance, check now

2022-05-01 06:50 UTC, ligi requested changes
Your explorer does not seem to conform to EIP3091 - please change to `none`

2022-05-01 06:54 UTC, samisbakedham commented
> Your explorer does not seem to conform to EIP3091 - please change to `none`

Fixed

2022-05-01 07:02 UTC, ligi commented
No I do not mean remove the explorer ( and leave an empty object) - I mean set the standard to `none`

2022-05-01 09:31 UTC, samisbakedham commented
> No I do not mean remove the explorer ( and leave an empty object) - I mean set the standard to `none`



> No I do not mean remove the explorer ( and leave an empty object) - I mean set the standard to `none`

Done!

2022-05-02 02:46 UTC, samisbakedham commented
@ligi Apologies but in order to build an adapter for DefiLlama we need this to be merged, preferably sooner rather than later. I understand you're extremely busy, is there any way we can give this the green light? I think it's good to go now. Thank you

2022-05-02 03:38 UTC, ligi approved these changes

2022-05-02 03:39 UTC, merged

2022-05-02 03:39 UTC, samisbakedham commented
Just saw it was approved - thank you! Will it be merged now?

2022-05-02 06:53 UTC, 0xngmi commented
having your chain listed here is NOT a requirement to build an adapter for defillama. Could you point me to the source where you got that idea @samisbakedham ?

2022-05-02 06:55 UTC, samisbakedham commented
> having your chain listed here is NOT a requirement to build an adapter for defillama. Could you point me to the source where you got that idea @samisbakedham ?

https://github.com/DefiLlama/chainlist/pull/19