Update ThunderCore mainnet/testnet info
ethereum-lists/chains pull request #1104
Opened 2022-04-24 19:13 UTC by kevin-thundertoken

2022-04-28 13:15 UTC, ligi requested changes

2022-04-29 16:41 UTC, kevin-thundertoken commented on _data/chains/eip155-108.json
> +      "standard": "EIP3091"
I've removed thunderscan from mainnet and testnet and will try to fix this in the feature.
We still have another workable explorer. Could you please help to merge this PR first?
Thanks!

2022-05-16 05:19 UTC, kevin-thundertoken commented
@ligi  could you please help to merge this PR? thanks!

2022-05-16 05:22 UTC, ligi approved these changes

2022-05-16 05:28 UTC, merged