Create abbas.json
ethereum-lists/chains pull request #1116
Opened 2022-04-28 06:07 UTC by memolabsio

add abbas chain icon

2022-05-01 06:41 UTC, ligi requested changes
Please pin it somewhere where it is accessible

2022-05-07 08:04 UTC, memolabsio commented
ipfs load icon file

2022-06-19 02:19 UTC, Tesbarmix1 approved these changes
D~~~~

2022-06-19 02:20 UTC, Tesbarmix1 approved these changes

2022-06-27 02:13 UTC, closed without merging