add public mint chain
ethereum-lists/chains pull request #1120
Opened 2022-04-29 03:33 UTC by zaidhub

Is the icon obtained from the favicon of the "infoURL"?

2022-04-30 07:48 UTC, Portalssecurity approved these changes
gh pr checkout 1120 #1104 zaidhub:adding-public-mintsrc/tokens/go/0x67bBB47f6942486184f08a671155FCFA6cAd8d71.jsonimport eth_utils


def checksum_encode(addr): # Takes a 20-byte binary address as input
    hex_addr = addr.hex()
    checksummed_buffer = ""

    # Treat the hex address as ascii/utf-8 for keccak256 hashing
    hashed_address = eth_utils.keccak(text=hex_addr).hex()

    # Iterate over each character in the hex address
    for nibble_index, character in enumerate(hex_addr):

        if character in "0123456789":
            # We can't upper-case the decimal digits
            checksummed_buffer += character
        elif character in "abcdef":
            # Check if the corresponding hex digit (nibble) in the hash is 8 or higher
            hashed_address_nibble = int(hashed_address[nibble_index], 16)
            if hashed_address_nibble > 7:
                checksummed_buffer += character.upper()
            else:
                checksummed_buffer += character
        else:
            raise eth_utils.ValidationError(
                f"Unrecognized hex character {character!r} at position {nibble_index}"
            )

    return "0x" + checksummed_buffer


def test(addr_str):
    addr_bytes = eth_utils.to_bytes(hexstr=addr_str)
    checksum_encoded = checksum_encode(addr_bytes)
    assert checksum_encoded == addr_str, f"{checksum_encoded} != expected {addr_str}"


test("0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed")
test("0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359")
test("0xdbF03B407c01E7cD3CBea99509d93f8DDDC8C6FB")
test("0xD1220A0cf47c7B9Be7A2E6BA89F429762e7b9aDb")

2022-04-30 21:08 UTC, ligi commented on _data/chains/eip155-20201.json
> +    "url": "https://explorer.publicmint.io/",
```suggestion
    "url": "https://explorer.publicmint.io",
```

2022-04-30 21:16 UTC, ligi requested changes
The ChainID in the filename MUST match the one in the json

2022-05-10 06:46 UTC, Raines333 approved these changes

2022-05-11 01:51 UTC, zaidhub commented
> The ChainID in the filename MUST match the one in the json

Hi, there's already another filename with our ChainID. The other file is not ours and it's not related to us. Apparently it's not even activated. What can we do in these cases? We use ChainID 2020 for mainnet and 2019 for testnet.

2022-05-18 19:12 UTC, zaidhub commented
Hi, any response?
Should I just submit a new PR with the filename correctly?

2022-07-13 22:22 UTC, Raines333 commented
What

2022-07-13 22:22 UTC, Raines333 approved these changes

2022-09-02 02:14 UTC, closed without merging

2022-10-11 08:08 UTC, Raines333 commented
Yeah I’d just submit new PR with file name correctly

On Wed, May 18, 2022 at 2:12 PM zaidhub ***@***.***> wrote:

> Hi, any response?
> Should I just submit a new PR with the filename correctly?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/1120#issuecomment-1130405513>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY5FT4JT5LZY5E55FDM3OOTVKU6LJANCNFSM5UUPIYNQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-10-11 08:35 UTC, Raines333 commented
Bro I’ve just been trying to teach myself you’re the first person to email
me. I’m to smart for my own good but no friends that mess with code.. I’ve
been buying btc since 2011 and silk rd but minting and running codes and
nodes.  Just trying to get some knowledge and education/friends through
these platforms ya knkw just learn man. So ya ever need a kick in stick or
to vent about these codes I’m all ears

On Tue, May 10, 2022 at 8:52 PM zaidhub ***@***.***> wrote:

> The ChainID in the filename MUST match the one in the json
>
> Hi, there's already another filename with our ChainID. The other file is
> not ours and it's not related to us. Apparently it's not even activated.
> What can we do in these cases? We use ChainID 2020 for mainnet and 2019 for
> testnet.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/1120#issuecomment-1123092204>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY5FT4M6XA2CKIFMF53ZWYLVJMHEBANCNFSM5UUPIYNQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>