add mandala/acala/karura chain info
ethereum-lists/chains pull request #1158
Opened 2022-05-17 03:16 UTC by shunjizhan

2022-05-17 05:18 UTC, ChenChunMing1986Loa approved these changes

2022-05-19 16:56 UTC, ligi approved these changes

2022-05-19 16:59 UTC, ligi requested changes

2022-05-19 16:59 UTC, ligi commented on _data/chains/eip155-595.json
> +    "url": "https://blockscout.mandala.acala.network/",
```suggestion
    "url": "https://blockscout.mandala.acala.network",
```

2022-05-19 16:59 UTC, ligi commented on _data/chains/eip155-596.json
> +    "url": "https://blockscout.karura-dev.aca-dev.network/",
```suggestion
    "url": "https://blockscout.karura-dev.aca-dev.network",
```

2022-05-19 16:59 UTC, ligi commented on _data/chains/eip155-597.json
> +    "url": "https://blockscout.acala-dev.aca-dev.network/",
```suggestion
    "url": "https://blockscout.acala-dev.aca-dev.network",
```

2022-05-19 16:59 UTC, ligi commented on _data/chains/eip155-686.json
> +    "url": "https://blockscout.karura.network/",
```suggestion
    "name": "blockscout",
    "url": "https://blockscout.karura.network",
```

2022-06-10 12:16 UTC, gluneau commented
Hey @ligi, are there more changes needed here or is it good to go?

2022-06-17 04:58 UTC, shunjizhan commented
@ligi any updates on this? If there is anything need to be changed plz let me know, thanks!

2022-06-19 22:10 UTC, gluneau commented
Hello @ligi, this PR seems to be in limbo.

It's ready to merge.

2022-08-09 02:12 UTC, closed without merging

2022-08-09 02:23 UTC, gluneau reviewed
Why close this, please merge it @ligi