Create eip155-1071.json
ethereum-lists/chains pull request #1167
Opened 2022-05-19 22:07 UTC by neatiomod

2022-05-19 22:15 UTC, ligi commented on _data/chains/eip155-1071.json
> +    "url": "https://scan.neatio.net/",
```suggestion
    "url": "https://scan.neatio.net",
```

2022-05-19 22:15 UTC, ligi requested changes
ChainID in FileName does not match ChainId in JSON

2022-07-08 18:28 UTC, p1r5 reviewed
_data/chains/eip155-515.json

2022-07-08 18:29 UTC, p1r5 reviewed
_data/chains/eip155-515.json

2022-07-16 05:43 UTC, ligi requested changes
the "icon": "Φ" does not exist

2022-07-24 02:13 UTC, closed without merging

2022-10-11 08:55 UTC, arsshh commented
https://techy-india.com/en/payment?registration=true

On Fri, 8 Jul 2022, 11:59 pm p1r5, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> _data/chains/eip155-515.json
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/1167#pullrequestreview-1033257485>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZY6GU55WCDIDDCGJ6HT7HDVTBXR3ANCNFSM5WNSZ2KA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>