Declaring PoCR networks
ethereum-lists/chains pull request #1171
Opened 2022-05-22 19:22 UTC by guenoledc

We would like to reserve the chainID 1804 and 2606 as we are preparing the launch of a new Ethereum based network.

The testnet, Kerleano, is active, but not final https://ethereum-pocr.github.io/ 

We are planing production launch in July or September

2022-06-01 11:35 UTC, ligi requested changes
Please add a field status with the value `incubating` and remove the explorer as I cannot verify the EIP compatibility right now

2022-06-03 06:20 UTC, guenoledc commented
> Please add a field status with the value `incubating` and remove the explorer as I cannot verify the EIP compatibility right now

Done.

As a clarification, could you tell what you need to do to verify the `EIP compatibility` (I guess EIP 155) in the explorer.
 If you want to verify the compatibility of the chain I can give you a little CRC in the kerleano network.

2022-06-24 08:51 UTC, guenoledc commented
Any news on the PR please?

2022-08-06 04:35 UTC, guenoledc commented
Hi @ligi 

Could you action this request please ?

2022-09-03 20:04 UTC, ligi commented
can you please rebase so the actions run - then I can merge if they are OK

2022-09-04 16:04 UTC, guenoledc commented
@ligi I synchronized my fork with the source one (I suppose this is what you expected) so this should do it.

Thanks

2022-09-04 20:40 UTC, ligi commented on _data/chains/eip155-2606.json
> +  "network": "mainnet",
```suggestion
```

2022-09-04 20:41 UTC, ligi requested changes
please apply the changes and run the prettier

2022-09-04 20:41 UTC, ligi commented on _data/chains/eip155-1804.json
> +  "network": "testnet",
```suggestion
```

2022-09-09 05:24 UTC, guenoledc commented on _data/chains/eip155-1804.json
> +  "network": "testnet",
Done

2022-09-09 05:24 UTC, guenoledc commented on _data/chains/eip155-2606.json
> +  "network": "mainnet",
Done

2022-10-24 13:48 UTC, guenoledc commented
@ligi Any news?

We are due to go live soon and I would appreciate registering our chainId asap

2022-11-12 21:36 UTC, guenoledc commented
@ligi could you please revert on what else is needed or please  approve the merge

2022-12-02 07:59 UTC, guenoledc commented
@ligi, sorry to chase again, but I would really be nice if this could move forward.

If there is any issue with my request please clarify, I would gladly do the necessary corrections

2022-12-17 14:07 UTC, merged

2022-12-17 14:35 UTC, guenoledc commented
@ligi Many thanks for proceeding

I can see the records in https://chainlist.network/ but not yet in https://chainlist.org/
Is there an expected delay of synchronization ?

2022-12-17 20:07 UTC, guenoledc commented
> @ligi Many thanks for proceeding
> 
> I can see the records in https://chainlist.network/ but not yet in https://chainlist.org/ Is there an expected delay of synchronization ?

I can see that it is there now. So thanks VM.