Add mainnet to cube
ethereum-lists/chains pull request #1224
Opened 2022-06-06 10:00 UTC by cppfuns

2022-06-12 06:51 UTC, cppfuns commented
@ligi Our project is in urgent need of this review. Please give priority to it. Thank you for your support

2022-06-13 05:06 UTC, ligi commented on _data/chains/eip155-1818.json
> +  "nativeCurrency": {
```suggestion
  ],
  "faucets": [],
  "nativeCurrency": {
```

2022-06-13 05:07 UTC, ligi requested changes
The faucets field is missing - please apply commit

2022-06-13 11:42 UTC, merged

2022-06-13 11:42 UTC, ligi commented
Please consider contributing to our grant: https://gitcoin.co/grants/2974/ethereum-lists