add arkon chain
ethereum-lists/chains pull request #1308
Opened 2022-06-28 16:19 UTC by NLGRF

- add arkon chain
- add arkon logo

2022-07-08 09:34 UTC, ligi commented on _data/chains/eip155-1678.json
> +    "url": "https://testnet.arkscan.net/",
```suggestion
    "url": "https://testnet.arkscan.net",
```

2022-07-08 09:42 UTC, ligi requested changes
I cannot resolve QmdZYBAwkZMV2UqE91oqEkNsd6pjP7bSjz3GR7N24nw7Lj - where did you pin it?

2022-07-09 09:02 UTC, NLGRF commented
> I cannot resolve QmdZYBAwkZMV2UqE91oqEkNsd6pjP7bSjz3GR7N24nw7Lj - where did you pin it?

I upload logo to pinata.cloud. @ligi

2022-07-30 14:47 UTC, NLGRF commented
Please review again. @ligi

2022-09-11 03:49 UTC, NLGRF commented
Please review again. @ligi @bmann

2022-11-02 02:13 UTC, closed without merging