add goheal chain
ethereum-lists/chains pull request #1347
Opened 2022-07-12 04:23 UTC by sundong-exideatech

Add GoHeal Testnet

2022-07-14 13:23 UTC, sundong-exideatech commented
@ligi, could you check this request?

2022-08-20 18:57 UTC, ligi requested changes

2022-08-20 18:57 UTC, ligi commented on _data/chains/eip155-3902.json
> +      "standard": "EIP3091"
```suggestion
      "url": "https://explorer.gohchain.com",
      "icon": "goheal",
      "standard": "none"
```

2022-08-20 19:00 UTC, ligi requested changes
chainID in json MUST match the filename

2022-10-10 02:13 UTC, closed without merging