Add epee chain
ethereum-lists/chains pull request #1350
Opened 2022-07-12 17:16 UTC by dangminhnhut1993

2022-07-15 09:29 UTC, ligi requested changes
shortName MUST be unique

2022-07-16 15:52 UTC, dangminhnhut1993 commented
@ligi Thanks for your checking, I updated shortName. Could you please help to check it again?

2022-08-20 19:08 UTC, ligi commented
/rebase

2022-08-20 19:17 UTC, ligi commented
/rebase

2022-10-10 02:13 UTC, closed without merging