Add CCN Main and Beta
ethereum-lists/chains pull request #1354
Opened 2022-07-14 06:57 UTC by hobbydev71

Added the main and beta networks for CCN

2022-07-14 12:19 UTC, ligi commented on _data/chains/eip155-971.json
> +  "shortName": "CCN",
```suggestion
  "shortName": "ccnbeta",
```

2022-07-14 21:51 UTC, hobbydev71 commented on _data/chains/eip155-971.json
> +  "shortName": "CCN",
I updated the shortname

2022-07-15 09:28 UTC, ligi requested changes
ShouldHaveNoMissingFields: missing field(s) [infoURL]

2022-07-16 19:37 UTC, hobbydev71 commented
> ShouldHaveNoMissingFields: missing field(s) [infoURL]

The infoURL is added.

2022-08-08 20:32 UTC, hobbydev71 commented
Hi @ligi ,
Could you check this PR to add new chain?

2022-08-10 00:32 UTC, closed without merging