Create 2020.json
ethereum-lists/chains pull request #137
Opened 2020-12-03 17:43 UTC by 420Integrated

adding 420coin to the EVM chains list.
ref: github.com/420integrated/go-420coin

https://420integrated.com
abvhiael@420integrated.com

2020-12-05 12:40 UTC, ligi requested changes

2020-12-05 12:40 UTC, ligi commented on _data/chains/2020.json
> +
can you remove this extra line?

2020-12-05 15:41 UTC, 420Integrated commented on _data/chains/2020.json
> +
done. sorry abt that.

2020-12-06 02:37 UTC, ligi approved these changes

2020-12-06 02:37 UTC, ligi commented on _data/chains/2020.json
> +
no worries

2020-12-06 02:38 UTC, merged