Update the Outdated Details for Cronos Mainnet
ethereum-lists/chains pull request #1389
Opened 2022-07-25 22:32 UTC by aw126

Update to the latest Block explorer URL for Cronos Mainnet. 
Official Cronos RPC URLs page: https://docs.cronos.org/for-users/metamask

2022-07-27 13:32 UTC, ligi requested changes
Seems to be 2 different explorers - so maybe just add it as an alternative? Or why does it need to be replaced?

2022-08-02 00:34 UTC, aw126 commented
> Seems to be 2 different explorers - so maybe just add it as an alternative? Or why does it need to be replaced?

There are two explorers for Cronos chain: in-house blockscout explorer and Cronoscan. Blockscout has its own advantages and will not be replaced by Cronoscan based on the current plan. 
`https://cronoscan.com/` is applied as the main explorer in the latest RPC detail.

2022-08-03 17:37 UTC, ligi commented
yes - then please add it as a second explorer and do not replace the old one. It is an array because of this reason.

2022-08-08 01:54 UTC, aw126 commented
> `https://cronoscan.com/` is more commonly used among Cronos users and applied as the main explorer in the latest RPC detail.

Though both explorers co-exist, from the perspective of RPC, the new explorer `https://cronoscan.com/` should replace the old one. The new one has now applied as the explorer URL in the latest RPC detail, so we can just keep the new one and remove the old one. Sorry for the confusion.

2022-09-09 20:34 UTC, aw126 commented
Hi @ligi, another quick follow-up on this change request along with https://github.com/ethereum-lists/chains/pull/1391. May we know if there are any further questions/concerns blocking merging these two changes? Thanks.

2022-10-03 17:42 UTC, ken-cronos commented
@ligi 
hi -- friendly follow-up to update the Cronos chain details in chainlist according to the official endpoints. All the details below are the official ones

Mainnet
Name: Cronos
New RPC URL: https://evm.cronos.org
Chain ID: 25
Symbol:CRO
Block explorer URL:https://cronoscan.com/

Testnet
Name: Cronos testnet
PC URL: https://evm-t3.cronos.org
Chain ID:338
Symbol:tCRO
Block explorer URL: https://testnet.cronoscan.com/

2022-10-21 20:45 UTC, ligi requested changes
Please run the prettier

2022-10-21 20:45 UTC, ligi commented on _data/chains/eip155-25.json
> +    "url": "https://cronoscan.com/",
```suggestion
    "url": "https://cronoscan.com",
```

2022-10-26 17:03 UTC, aw126 commented
> Please run the prettier

Hi @ligi, we've run the prettier checks and it should be good now. Could you please review and merge?

2022-10-26 17:44 UTC, ligi approved these changes

2022-10-26 17:47 UTC, merged