Add Newton NEW
ethereum-lists/chains pull request #140
Opened 2020-12-14 03:32 UTC by VieYang

2020-12-14 06:48 UTC, ligi requested changes
The shortNames must be different - this is a requirement by TREZOR

2020-12-14 07:59 UTC, VieYang commented
update shortName

2020-12-14 16:05 UTC, ligi commented
sorry - but also the name must be different - did not see this on the first view

2020-12-15 02:38 UTC, VieYang commented
ok, update it.

2020-12-16 08:05 UTC, ligi approved these changes

2020-12-16 08:05 UTC, merged