Add dogechain mainnet & testnet
ethereum-lists/chains pull request #1406
Opened 2022-08-02 08:17 UTC by Huuuulk

2022-08-03 14:29 UTC, ligi requested changes
short name must be unique - but found `dogechain` more than once

2022-08-03 17:39 UTC, abrahamcruise321 commented on _data/chains/eip155-2000.json
> +  "name": "Doge Chain Mainnet",
Doge Chain -> Dogechain

2022-08-12 03:48 UTC, HulkChou8 commented
@ligi Need to review again, thanks.

2022-08-12 03:48 UTC, HulkChou8 commented
@ligi Need to review again, thanks.

2022-08-12 08:04 UTC, Huuuulk commented
@ligi Need to review again, thanks.

2022-08-20 19:23 UTC, ligi approved these changes

2022-08-21 08:18 UTC, Huuuulk reviewed
dogechain logo

2022-08-21 10:55 UTC, closed without merging