Update Callisto Network
ethereum-lists/chains pull request #1411
Opened 2022-08-03 18:39 UTC by ESNJS

@ligi I opened a new PR so I do not spam the branch with commits.

2022-08-04 22:56 UTC, ligi requested changes
name must be unique - but found `Callisto Testnet` more than once
so please rename the deprecated one

2022-08-04 22:59 UTC, ESNJS commented
> name must be unique - but found `Callisto Testnet` more than once so please rename the deprecated one

@ligi done, I hope haha

2022-08-20 19:22 UTC, merged

2022-10-01 07:17 UTC, SQuIsHY7D3m commented on _data/chains/eip155-821.json
> -  "networkId": 2
-

2022-10-01 07:18 UTC, SQuIsHY7D3m commented on _data/chains/eip155-821.json
> -  "networkId": 2
#1411