Added SanR Chain
ethereum-lists/chains pull request #1430
Opened 2022-08-08 12:21 UTC by uxname

2022-08-18 09:19 UTC, ligi requested changes

2022-08-18 09:19 UTC, ligi commented on _data/chains/eip155-11888.json
> +      "standard": "EIP3091"
the explorer does not seem to be EIP3091 compatible


```suggestion
      "standard": "none"
```

2022-08-20 11:28 UTC, uxname commented
Changed explorer standard from EIP3091 to "none"

2022-08-20 12:35 UTC, ligi approved these changes

2022-08-20 12:35 UTC, merged