add  moba game testnet
ethereum-lists/chains pull request #1437
Opened 2022-08-10 09:34 UTC by Tetrose4

pls

2022-08-18 09:17 UTC, ligi requested changes
ShouldHaveNoMissingFields: missing field(s) [faucets, infoURL]

2022-08-22 02:25 UTC, Tetrose4 commented
> ShouldHaveNoMissingFields: missing field(s) [faucets, infoURL]

we  change the chainId  and fill the missing item.

2022-08-22 03:58 UTC, ligi commented on _data/chains/eip155-18000.json
> +    "url": "https://explorer.fod.games/",
```suggestion
    "url": "https://explorer.fod.games",
```

2022-09-06 21:10 UTC, ligi approved these changes

2022-09-06 21:10 UTC, merged