Create eip155-1515.json
ethereum-lists/chains pull request #1443
Opened 2022-08-14 14:59 UTC by 0xli

Add Beagle Messaging Chain which has run for more than 3 years

2022-08-17 10:35 UTC, ligi requested changes

2022-08-17 10:35 UTC, ligi commented on _data/chains/eip155-1515.json
> +    "url": "https://eth.beagle.chat",
I cannot reach this site

2022-08-17 23:00 UTC, 0xli commented
Can you access the RPC and infoURL site?
It should work.
We are still working on the faucet and explore site. Can I delete them and
add back later?

Wei Li

ligi ***@***.***> 于 2022年8月17日周三 18:35写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In _data/chains/eip155-1515.json
> <https://github.com/ethereum-lists/chains/pull/1443#discussion_r947764509>
> :
>
> > +  "rpc": [
> +    "https://beagle.chat/eth"
> +  ],
> +  "faucets": ["https://faucet.beagle.chat/"],
> +  "nativeCurrency": {
> +    "name": "Beagle",
> +    "symbol": "BG",
> +    "decimals": 18
> +  },
> +  "infoURL": "https://beagle.chat/",
> +  "shortName": "beagle",
> +  "chainId": 1515,
> +  "networkId": 1515,
> +  "explorers": [{
> +    "name": "beagle chain explorer",
> +    "url": "https://eth.beagle.chat",
>
> I cannot reach this site
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/1443#pullrequestreview-1075484391>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGUCANPBZH7TRZZPHKQODB3VZS56TANCNFSM56P76GWA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-18 09:15 UTC, 0xli commented on _data/chains/eip155-1515.json
> +    "url": "https://eth.beagle.chat",
it works now.

2022-08-18 09:16 UTC, ligi commented
yes - you can delete and add the details later - but I do not want to merge not working stuff

2022-08-18 12:00 UTC, 0xli commented
> yes - you can delete and add the details later - but I do not want to merge not working stuff

it works now, please check https://eth.beagle.chat

2022-08-18 15:55 UTC, 0xli commented
The explore is up but it is not stable yet, I am going to remove it
tomorrow. What's the minimal required information needed in order to be
listed on your esteemed site?

ligi ***@***.***> 于 2022年8月18日周四 17:16写道：

> yes - you can delete and add the details later - but I do not want to
> merge not working stuff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/1443#issuecomment-1219237317>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGUCANPKICVLYMUSQIJM2LLVZX5PHANCNFSM56P76GWA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-19 08:19 UTC, closed without merging

2022-08-19 08:20 UTC, 0xli commented
I am going to delete some information first