Add Bitcoin EVM
ethereum-lists/chains pull request #1461
Opened 2022-08-20 06:53 UTC by BitcoinEvm

Added Support For Bitcoin EVM Chain ID 2203

2022-08-20 09:11 UTC, ligi requested changes
the icon in iconsDownload cannot have the .PNG ending

2022-08-20 10:07 UTC, BitcoinEvm commented
Changes made @ligi PNG removed

2022-08-20 10:15 UTC, ligi requested changes
size is wrong - also the file in iconsDownload does not match the CID - please just remove

2022-08-20 10:15 UTC, ligi commented on _data/icons/ebtc.json
> +    "width":896,
size seems to be 200x200
✓ ~/tmp ipfs get bafkreic4aq265oaf6yze7ba5okefqh6vnqudyrz6ovukvbnrlhet36itle
Saving file(s) to bafkreic4aq265oaf6yze7ba5okefqh6vnqudyrz6ovukvbnrlhet36itle
 33.39 KiB / 33.39 KiB [============================================] 100.00% 0s
✓ ~/tmp identify bafkreic4aq265oaf6yze7ba5okefqh6vnqudyrz6ovukvbnrlhet36itle
bafkreic4aq265oaf6yze7ba5okefqh6vnqudyrz6ovukvbnrlhet36itle PNG 200x200 200x200+0+0 8-bit sRGB 34195B 0.000u 0:00.000

2022-08-21 00:51 UTC, BitcoinEvm commented
Ok It has been removed thank you.

2022-08-21 05:10 UTC, ligi commented on _data/icons/ebtc.json
> +    "height":690,
```suggestion
    "height":200,
```

2022-08-21 05:11 UTC, ligi commented on _data/icons/ebtc.json
> +    "width":896,
```suggestion
    "width":200,
```

2022-08-21 05:12 UTC, ligi commented
/rebase

2022-08-21 09:14 UTC, ligi commented
/rebase

2022-08-24 21:47 UTC, BitcoinEvm commented
https://github.com/ethereum-lists/chains/pull/1487 

New Pull Request Closing this

2022-08-24 21:47 UTC, closed without merging