Add BizNet mainnet
ethereum-lists/chains pull request #1520
Opened 2022-08-30 05:15 UTC by TrustHenry

This is our site. : https://bosagora.io

2022-08-30 09:04 UTC, ashutoshpw requested changes

2022-08-30 09:04 UTC, ashutoshpw commented on _data/chains/eip155-2151.json
> +  "network": "mainnet",
```suggestion
```

2022-08-30 09:04 UTC, ashutoshpw commented on _data/chains/eip155-2151.json
> +  "network": "mainnet",
Please remove the `network` param as of our latest docs and also run this command locally to format the JSON properly.

`npx prettier --write --ignore-unknown _data`

2022-08-30 09:25 UTC, ashutoshpw commented
@TrustHenry You need to run `npx prettier --write --ignore-unknown _data` from the project directory to format the JSON file properly and pass the Workflow `
Check JavaScript for conformance with Prettie`

2022-09-07 02:03 UTC, TrustHenry commented
@ashutoshpw Thankyou. 
I ran `npx prettier --write --ignore-unknown _data`
Could you run the workflow again?

2022-09-09 10:41 UTC, ashutoshpw approved these changes
Looks good to me. @ligi can merge it in the `main` branch

2022-09-23 07:44 UTC, TrustHenry commented
@ligi Please a review.

2022-11-02 08:41 UTC, TrustHenry commented
#1809 We start with a new name.(BOSagora)

2022-11-02 08:41 UTC, closed without merging