add memo chaininfo
ethereum-lists/chains pull request #1523
Opened 2022-08-30 10:00 UTC by memolabsio

add memo chaininfo

2022-08-30 23:59 UTC, ligi requested changes
I can resolve bafkreig52paynhccs4o5ew6f7mk3xoqu2bqtitmfvlgnwarh2pm33gbdrq but not QmNrdTWjkDuBSME5RZmCweVd4a34NvmSLwpW4Ca1NWwhpL

2022-08-31 07:22 UTC, memolabsio commented
update chaininfo delete 

> I can resolve bafkreig52paynhccs4o5ew6f7mk3xoqu2bqtitmfvlgnwarh2pm33gbdrq but not QmNrdTWjkDuBSME5RZmCweVd4a34NvmSLwpW4Ca1NWwhpL
update memo chain info
delete abbas.json

2022-08-31 08:07 UTC, ligi requested changes

2022-08-31 08:07 UTC, ligi commented on _data/chains/eip155-1985.json
> +    "url": "https://testscan.metamemo.one:8080/",
```suggestion
    "url": "https://testscan.metamemo.one:8080",
```

2022-08-31 08:07 UTC, ligi commented on _data/chains/eip155-985.json
> +    "url": "https://scan.metamemo.one:8080/",
```suggestion
    "url": "https://scan.metamemo.one:8080",
```

2022-08-31 08:10 UTC, ligi commented on _data/chains/eip155-1985.json
> +  "shortName": " memochain",
```suggestion
  "shortName": "memochain",
```

2022-08-31 08:11 UTC, ligi commented on _data/chains/eip155-1985.json
> +  "shortName": " memochain",
```suggestion
  "shortName": "memochain-testnet",
```

2022-10-25 02:14 UTC, closed without merging