Add Opside Testnet
ethereum-lists/chains pull request #1526
Opened 2022-08-31 02:53 UTC by icydark

Add Opside Testnet, chain ID 23118

2022-08-31 12:13 UTC, ligi approved these changes

2022-08-31 20:05 UTC, Jay4577 commented on _data/icons/opside.json
> +    "height": "591",
Thanks. Im just learning

2022-09-01 20:37 UTC, ligi requested changes
Can you run the prettier?

2022-09-02 07:17 UTC, ligi approved these changes

2022-09-02 07:17 UTC, merged