tecracoin registration (testnet and mainnet)
ethereum-lists/chains pull request #1542
Opened 2022-09-04 10:18 UTC by djm34

Hello, could you please add TecraCoin chains to the list (mainnet and testnet)

2022-09-04 10:20 UTC, ligi requested changes
The certificate of your explorers expired

2022-09-05 06:29 UTC, djm34 commented
ok, I'll let you know once it has been renewed

2022-09-05 06:52 UTC, djm34 commented
certificate should be fine now

2022-10-18 08:48 UTC, Saberhabeelshohdy approved these changes

2022-10-26 02:13 UTC, closed without merging