Add Highrise Blockchain Testnet
ethereum-lists/chains pull request #1579
Opened 2022-09-12 07:54 UTC by mculinovic

2022-09-12 10:42 UTC, oyakh commented
How can I add my wallet address

2022-09-12 13:59 UTC, ligi requested changes
The URL must be a IPFS CID

2022-09-12 20:51 UTC, najmahmd approved these changes

2022-09-12 20:51 UTC, najmahmd commented on _data/chains/eip155-8184.json
> +    "https://subnets.avax.network/pocket-worlds/testnet/rpc",
0x7ED3ac6Ee8e905F2341eC035118a0F7c42c8A677

2022-09-12 20:52 UTC, najmahmd approved these changes

2022-09-14 11:15 UTC, mculinovic commented
> The icon URL must be a IPFS URL (starting with ipfs://)

@ligi added IPFS url

2022-09-20 15:54 UTC, mculinovic commented
@ligi just a reminder for this when you have time to check it out

2022-09-23 08:42 UTC, closed without merging