add europa skale chain
ethereum-lists/chains pull request #1589
Opened 2022-09-14 12:28 UTC by RubyAquaMarine

2022-11-04 02:59 UTC, ligi requested changes
where did you pin the IPFS CID? I could not resolve it via `ipfs get`

2022-11-04 02:59 UTC, ligi commented on _data/chains/eip155-2046399126.json
> +        "url": "https://elated-tan-skat.explorer.mainnet.skalenodes.com/",
```suggestion
        "url": "https://elated-tan-skat.explorer.mainnet.skalenodes.com",
```

2022-11-04 02:59 UTC, ligi commented on _data/chains/eip155-2046399126.json
> +
```suggestion
```

2022-11-04 02:59 UTC, ligi commented on _data/icons/europa.json
> +
```suggestion
```

2022-11-04 06:09 UTC, RubyAquaMarine commented
> where did you pin the IPFS CID? I could not resolve it via `ipfs get`

https://gateway.pinata.cloud/ipfs/QmPKW7WnAie3rMkjdqfF1cgK8UMZ8RgoUebhNaMZPBFgYp

2022-11-04 06:43 UTC, ligi commented
please pin it somewhere else - pinata is currently not publishing to the DHT
also run the prettier

2022-11-08 02:46 UTC, RubyAquaMarine commented
everything ok? @ligi

2022-11-15 13:24 UTC, RubyAquaMarine commented
I'd love to check this off my todo list. I hope you're doing well @ligi

2022-11-22 11:15 UTC, RubyAquaMarine reviewed
changes added

2022-12-26 08:42 UTC, RubyAquaMarine commented
anything else required? @ligi

2022-12-26 12:41 UTC, RubyAquaMarine commented
@ligi  prettier ran again. npx prettier --check '_data/*/*.json' passes locally.

2022-12-26 13:48 UTC, ligi requested changes

2022-12-28 07:41 UTC, RubyAquaMarine commented on _data/icons/europa.json
> +    "format": "png"
ok

2023-01-05 09:01 UTC, ligi approved these changes

2023-01-05 09:01 UTC, merged