Create 0xTrade
ethereum-lists/chains pull request #1644
Opened 2022-09-24 14:22 UTC by reeveshen

add new chain  0xTrade

2022-09-27 05:31 UTC, MoGenius5420 commented
`gh pr checkout 1644`

2022-10-03 10:18 UTC, ligi requested changes

2022-10-03 10:18 UTC, ligi commented on _data/chains/0xTrade
> +    "name": "0XT"
```suggestion
    "name": "0XT",
```

2022-10-03 10:24 UTC, ligi requested changes

2022-10-03 10:24 UTC, ligi commented on _data/chains/0xTrade
> +  "icon": "0xtrade
```suggestion
  "shortName": "0xt",
  "chainId": 10248,
  "networkId": 10248,
  "icon": "0xtrade",
```

2022-10-03 10:24 UTC, ligi commented on _data/chains/eip155-10248.json
> +  "icon": "0xtrade",
```suggestion
```

2022-10-03 10:26 UTC, merged