add ETMP chain
ethereum-lists/chains pull request #1654
Opened 2022-09-27 04:11 UTC by LuxesOwen

Add ETMP chain,use chainId=48 for Mainnet,chainId=49 for Testnet

2022-09-27 05:21 UTC, MoGenius5420 commented
`gh pr checkout 1654`

2022-09-27 05:46 UTC, MoGenius5420 commented
`gh pr checkout 1654`

2022-09-27 05:46 UTC, MoGenius5420 approved these changes

2022-09-27 05:46 UTC, MoGenius5420 approved these changes

2022-09-27 05:51 UTC, MoGenius5420 commented
@mogeeeenius - Instagram

2022-10-14 08:02 UTC, LuxesOwen commented
@ligi Please merge, thank you very much

2022-10-14 12:33 UTC, ligi requested changes

2022-10-14 12:33 UTC, ligi commented on _data/chains/eip155-49.json
> +      "url": "https://pioneer.etmscan.network/",
```suggestion
      "url": "https://pioneer.etmscan.network",
```

2022-10-15 14:26 UTC, LuxesOwen commented
hi @ligi , thanks for your check,please merge my request.

2022-10-28 06:38 UTC, closed without merging