Pull request for addition of Apex chain.
ethereum-lists/chains pull request #1660
Opened 2022-09-28 02:36 UTC by matangazoadmin

2022-09-28 05:25 UTC, SQuIsHY7D3m approved these changes

2022-09-28 05:27 UTC, SQuIsHY7D3m commented
1. 

Uploading XRecorder_Edited_10092022_183527.mp4…

2022-11-07 02:05 UTC, robledo6 reviewed
Solo dire una cosa no preguntes lo que esta mas claro qye el agua

2023-01-22 19:15 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also: The Icon apex does not exist - was used in eip155-1501795822.json

2023-06-01 02:13 UTC, closed without merging