Add Maistest Subnet
ethereum-lists/chains pull request #1665
Opened 2022-09-28 13:59 UTC by steliyannedev

2022-11-04 02:04 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2022-11-04 08:59 UTC, steliyannedev commented
@ligi formatted as requested.

2022-12-20 14:03 UTC, steliyannedev commented
@ligi hey is there something else I should do?

2022-12-20 14:05 UTC, ligi commented on _data/chains/eip155-43214913.json
> +      "standard": "EIP3091"
```suggestion
      "standard": "none"
```

2022-12-20 14:21 UTC, merged