Adding MO Chain
ethereum-lists/chains pull request #1669
Opened 2022-09-29 21:26 UTC by mochainapp

eip155-7924.json
eip-155-22936.json
mochaintestnet.json

2022-10-03 10:12 UTC, mochainapp reviewed
changed icon size on mochaintestnet.json

2022-10-03 10:13 UTC, tazimamatovzeka approved these changes

2022-10-03 10:13 UTC, tazimamatovzeka commented
a37a89d077e7e696d320804a7a10be0f8e413579

2022-10-03 10:14 UTC, ligi requested changes
size is wrong:

```
identify QmZbfcg6gYPFyp7zHwPpyyq3yFvFjfYYyLWnaYZr5rxjfu         12:14:10
QmZbfcg6gYPFyp7zHwPpyyq3yFvFjfYYyLWnaYZr5rxjfu SVG 772x606 772x606+0+0 8-bit sRGB 175342B 0.010u 0:00.00
```

2022-10-03 10:47 UTC, atriciamoreirag approved these changes

2022-10-06 12:35 UTC, mochainapp commented
any update is appreciated. file changes were made as requested.

2022-10-10 11:15 UTC, mochainapp commented
@ligi can you please give it another check? thank you

2022-10-10 12:50 UTC, ligi commented on _data/chains/eip155-22936.json
> +      "url": "https://motestnet.app/",
```suggestion
      "url": "https://motestnet.app",
```

2022-10-10 12:51 UTC, ligi commented on _data/chains/eip155-22936.json
> +    "https://testnet-rpc.motestnet.app/",
```suggestion
    "https://testnet-rpc.motestnet.app/",
```
```suggestion
    "https://testnet-rpc.motestnet.app/"
```

2022-10-10 12:51 UTC, ligi commented on _data/chains/eip155-7924.json
> +    "https://mainnet-rpc.moscan.app/",
```suggestion
    "https://mainnet-rpc.moscan.app/"
```

2022-10-15 15:26 UTC, mochainapp commented
@ligi do you need any help from our side to finish this`? thank you

2022-10-15 19:57 UTC, deep709 commented
Thanks.

2022-10-18 12:03 UTC, mochainapp commented
@ligi can you give it another check please? all changes are done.

2022-11-30 14:02 UTC, mochainapp commented
> size is wrong:
> 
> ```
> identify QmZbfcg6gYPFyp7zHwPpyyq3yFvFjfYYyLWnaYZr5rxjfu         12:14:10
> QmZbfcg6gYPFyp7zHwPpyyq3yFvFjfYYyLWnaYZr5rxjfu SVG 772x606 772x606+0+0 8-bit sRGB 175342B 0.010u 0:00.00
> ```

Already did.

2023-01-22 19:16 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also:  short name must be unique - but found `MO` more than once

2023-02-19 15:54 UTC, ligi commented
Also:  short name must be unique - but found `MO` more than once

2023-04-11 01:51 UTC, closed without merging