Add Celoscan (EIP3091) and lowercase shortName
ethereum-lists/chains pull request #1676
Opened 2022-09-30 21:24 UTC by matthewlilley

Add Celoscan (EIP3091) and lowercase shortName to adhere to EIP-3770

2022-10-01 04:22 UTC, ligi requested changes

2022-10-01 04:22 UTC, ligi commented on _data/chains/eip155-42220.json
> +      "standard":"EIP3091"
```suggestion
      "name": "Celoscan",
      "url": "https://celoscan.io",
      "standard": "EIP3091"
```

2022-10-01 14:35 UTC, matthewlilley commented
@ligi Thanks. Looks like this one is good to go.

2022-10-01 15:35 UTC, tazimamatovzeka approved these changes

2022-10-01 16:57 UTC, FrederikBolding approved these changes

2022-10-01 20:31 UTC, tazimamatovzeka reviewed
Ayzat

2022-10-03 09:39 UTC, ligi approved these changes

2022-10-03 09:39 UTC, merged

2022-10-03 09:43 UTC, tazimamatovzeka commented
IE03091