Add darwinia network test net
ethereum-lists/chains pull request #168
Opened 2021-02-25 11:58 UTC by AsceticBear

2021-02-25 12:00 UTC, ligi requested changes
There can only be one native currency - wonder why you need 2

2021-02-26 01:42 UTC, AsceticBear commented
> There can only be one native currency - wonder why you need 2

Let me explain the details more. Darwinia network is a decentralized cross-chain bridge based on substrate framework. Due to the nature of substrate, we support two currencies now, RING, KTON.

The Pangolin network is a test network built by Darwinia to support ethereum evm which allows users to migrate existing Dapps to the Darwinia network without much modification.

2021-03-01 15:51 UTC, ligi commented
thanks for the info! But when a (EVM) smart-contract is executed - from which of the currencies does it take the gas?

2021-03-02 02:41 UTC, AsceticBear commented
> thanks for the info! But when a (EVM) smart-contract is executed - from which of the currencies does it take the gas?

The first one, RING.

2021-03-02 11:00 UTC, ligi commented
please set RING as native currency then. We can also add a new field maybe for a secondary currency. But of that I would need more information how this information can be used then.

2021-03-02 11:19 UTC, AsceticBear commented
> please set RING as native currency then. We can also add a new field maybe for a secondary currency. But of that I would need more information how this information can be used then.

Done, Please check again later.

2021-03-02 13:09 UTC, ligi requested changes

2021-03-02 13:09 UTC, ligi commented on _data/chains/eip155-43.json
> +  "nativeCurrency1": {
```suggestion
  "nativeCurrency": {
```

2021-03-03 20:46 UTC, ligi commented
I am happy with it now - but CI is missing the shortName field

2021-03-04 08:34 UTC, merged