update bttc testnet config
ethereum-lists/chains pull request #1709
Opened 2022-10-09 08:32 UTC by xq-lu

1. set old chainid 1028 to deprecated. 
2. add new testnet chainid 1029 and update some chain info like RPC URL, and faucets URL.

2022-10-09 08:36 UTC, xq-lu commented
@ligi Please merge, thank you very much.

2022-10-09 16:40 UTC, ligi requested changes

2022-10-09 16:40 UTC, ligi commented on _data/chains/eip155-1029.json
> +      "url": "https://testnet.bttcscan.com/",
```suggestion
      "url": "https://testnet.bttcscan.com",
```

2022-10-09 16:40 UTC, ligi commented on _data/chains/eip155-1029.json
> +      "url": "https://testscan.bt.io/",
```suggestion
      "url": "https://testscan.bt.io",
```

2022-10-09 16:46 UTC, ligi requested changes
NameMustBeUnique:  name must be unique - but found `BITTORRENTCHAINTESTNET` more than once

also please run the prettier

2022-10-10 03:06 UTC, xq-lu commented
> NameMustBeUnique: name must be unique - but found `BITTORRENTCHAINTESTNET` more than once
> 
> also please run the prettier

hi,ligi.already fixed the format errors.

2022-10-14 03:14 UTC, xq-lu commented
hi, @Tesbarmix1 thank you .but the status of this PR is still open. I guess it still needs a maintainer to approve running workflows. could you help?

2022-10-28 04:33 UTC, xq-lu commented
hi, @Tesbarmix1 , could you merge this pull request ? thank you

2022-12-12 02:15 UTC, ligi requested changes
short name must be unique - but found `TBTT` more than once

2022-12-20 01:57 UTC, closed without merging