Create eip155-400.json
ethereum-lists/chains pull request #1720
Opened 2022-10-14 18:02 UTC by HyperonChainOfficial

Adding HyperonChain-TestNet

2022-10-14 18:03 UTC, HyperonChainOfficial commented
@ligi Pls help me with Run prettier failed error while adding HyperonChain TestNet

2022-10-14 18:07 UTC, HyperonChainOfficial commented
@Tesbarmix1 @ligi  Pls merge request

2022-10-14 23:49 UTC, ligi requested changes

2022-10-14 23:49 UTC, ligi commented on _data/chains/eip155-400.json
> +  ],
```suggestion
  "rpc": ["https://testnet-rpc.hyperonchain.com"],
  "faucets": ["https://faucet.hyperonchain.com"],
```

2022-10-15 00:16 UTC, ligi approved these changes

2022-10-15 00:16 UTC, merged