Adding eip155-2139927552 - SKALE - Exorde Network
ethereum-lists/chains pull request #1732
Opened 2022-10-18 14:57 UTC by MathiasExorde

"url": "https://exorde.network/"
"faucetUrl": "http://faucet.exorde.network/"
"description": "The Web3 protocol collecting data from the Web jungle to capture topics, news, reputation, and trends worldwide in real-time."

2022-10-18 19:01 UTC, ligi requested changes

2022-10-18 19:03 UTC, ligi requested changes

2022-10-18 19:03 UTC, ligi commented on _data/icons/exorde.json
> +    "url": "ipfs://bafybeidq7g4nbgkok7m3syvqhabxivrpj5ryreeabye3mlqdw64cqmsvam",
This is a directory and not a file - so the contentHash in IconDownload is wrong also
```
identify bafybeidq7g4nbgkok7m3syvqhabxivrpj5ryreeabye3mlqdw64cqmsvam/exorde-logo.png 
bafybeidq7g4nbgkok7m3syvqhabxivrpj5ryreeabye3mlqdw64cqmsvam/exorde-logo.png PNG 290x401 290x401+0+0 8-bit sRGB 3114B 0.000u 0:00.000

```

2022-10-19 09:49 UTC, MathiasExorde reviewed
Changed folder IPFS hash to file hash

2022-10-21 08:57 UTC, MathiasExorde commented
is it all good now? @ligi

2022-11-18 13:28 UTC, ligi requested changes

2022-11-18 13:28 UTC, ligi commented on _data/chains/eip155-2139927552.json
> +
```suggestion
```

2022-11-18 13:28 UTC, ligi commented on _data/chains/eip155-2139927552.json
> +  "network": "mainnet",
```suggestion
```

2022-11-18 13:30 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2022-12-31 05:43 UTC, robledo6 commented on _data/chains/eip155-2139927552.json
> +    "url": "https://light-vast-diphda.explorer.mainnet.skalenodes.com/",
No sé hacer esto sheen

2023-01-08 02:00 UTC, closed without merging