Add STEP Main and Test networks
ethereum-lists/chains pull request #1746
Opened 2022-10-20 13:50 UTC by ongrid

2022-10-20 16:25 UTC, ligi requested changes

2022-10-21 08:35 UTC, ongrid commented on _data/icons/step.json
> +    "url": "ipfs://QmVp9jyb3UFW71867yVtymmiRw7dPY4BTnsp3hEjr9tn8L",
Pinata https://gateway.pinata.cloud/ipfs/QmVp9jyb3UFW71867yVtymmiRw7dPY4BTnsp3hEjr9tn8L

2022-10-21 08:41 UTC, ongrid commented
Image is available on all IPFS gateways I tested, changed shortname to unique (CI was failing because of that)

2022-10-24 08:53 UTC, ongrid commented
Here is the alternative link that confirms image available through another IPFS gateway https://ipfs.io/ipfs/QmVp9jyb3UFW71867yVtymmiRw7dPY4BTnsp3hEjr9tn8L Could you please check @ligi

2022-11-02 07:31 UTC, ongrid commented
@ligi could you please take a look 👀

2022-11-04 07:17 UTC, closed without merging