Added The Bifrost Testnet network and The Bifrost icon
ethereum-lists/chains pull request #1747
Opened 2022-10-20 14:52 UTC by mur-me

2022-10-20 15:47 UTC, ligi requested changes

2022-10-20 15:47 UTC, ligi commented on _data/icons/thebifrost.json
> +    "format": "png"
the sizes are wrong
```
✓ ~/tmp identify bafkreid32bybgacpg7v3rrpq56oplhegmoyzhygzbvykkigv62f5a3iltu
bafkreid32bybgacpg7v3rrpq56oplhegmoyzhygzbvykkigv62f5a3iltu PNG 670x175 670x175+0+0 8-bit sRGB 18352B 0.000u 0:00.000
```

2022-10-20 16:06 UTC, mur-me commented on _data/icons/thebifrost.json
> +    "format": "png"
Thanks, one sec, I'll change!

2022-10-20 16:17 UTC, ligi requested changes

2022-10-20 16:17 UTC, ligi commented on _data/chains/eip155-49088.json
> +      "url": "https://explorer.testnet.thebifrost.io/",
```suggestion
      "url": "https://explorer.testnet.thebifrost.io",
```

2022-10-20 16:17 UTC, merged

2022-10-20 18:58 UTC, mur-me commented
Hi @ligi,

Is it normal that some of the GitHub actions jobs have failed after merge?

2022-10-21 17:53 UTC, ligi commented
yes - you cannot use gor as a shortName - so I reverted your PR - please submit another one with a not yet used shortname

2022-10-24 16:57 UTC, mur-me commented
@ligi sorry for my fuckup, I've fixed everything, check it twice and created new pr - https://github.com/ethereum-lists/chains/pull/1766
can you please take a look on it, if u have time?