Update eip155-67390.json
ethereum-lists/chains pull request #1758
Opened 2022-10-22 03:06 UTC by warewar1

2022-10-25 00:41 UTC, ligi requested changes

2022-10-25 00:41 UTC, ligi commented on _data/chains/eip155-67390.json
> +    "url": "https://siriusnetscan.io",
I cannot reach this URL

2022-10-28 01:11 UTC, warewar1 commented on _data/chains/eip155-67390.json
> +    "url": "https://siriusnetscan.io",
Solved

2022-10-28 01:13 UTC, warewar1 reviewed
solved

2022-10-28 06:13 UTC, warewar1 commented
Solved

2022-11-02 15:04 UTC, warewar1 commented
Please aprove!

2022-11-08 18:21 UTC, ligi requested changes
This is not a good change:

![image](https://user-images.githubusercontent.com/111600/200644561-e719f1d0-f7f7-4424-b3fe-6d378283b5b7.png)

2022-11-14 11:02 UTC, closed without merging