add Flare Testnet Chain (Coston2)
ethereum-lists/chains pull request #1768
Opened 2022-10-24 10:53 UTC by sea-edge

Create eip155-114.json
- ref: https://docs.flare.network/dev/reference/network-configs/

2022-10-24 14:29 UTC, ligi requested changes

2022-10-24 14:29 UTC, ligi commented on _data/chains/eip155-114.json
> +
```suggestion
```

2022-10-25 02:06 UTC, sea-edge commented
@ligi 
Retry prettier actions ,please.

2022-11-07 14:03 UTC, RareData commented
Please let the older PR take precedence: https://github.com/ethereum-lists/chains/pull/1710/files

2022-11-14 04:29 UTC, closed without merging