Added MOAC testnet, mainnet and icon
ethereum-lists/chains pull request #1770
Opened 2022-10-24 20:44 UTC by mdranger

2022-10-25 00:06 UTC, ligi requested changes

2022-10-25 00:06 UTC, ligi commented on _data/chains/eip155-201.json
> +      "standard": "EIP3091"
```suggestion
      "standard": "none"
```

the explorer does not respect EIP3091 when it comes to addresses

2022-11-04 21:57 UTC, ligi requested changes
please apply my suggestions of fix it yourself

2022-11-05 15:08 UTC, mdranger reviewed
updated

2022-11-05 15:39 UTC, ligi requested changes
short name must be unique - but found `MOAC` more than once

2022-11-08 13:22 UTC, mdranger reviewed
change the testnet shortName to moactest, mainnet shortName uses moac

2022-11-08 13:54 UTC, ligi approved these changes

2022-11-08 13:54 UTC, merged