Add mantle chains
ethereum-lists/chains pull request #1779
Opened 2022-10-26 06:28 UTC by chengwenxi

Mantle is a suite of Ethereum scaling solutions.

The Testnet and Mainnet will be launched in the next few months.

2022-10-26 06:36 UTC, guoshijiang approved these changes

2022-10-26 07:51 UTC, shidaxi approved these changes
LGTM

2022-10-26 10:53 UTC, bradyjoestar approved these changes

2022-11-03 22:10 UTC, ligi requested changes
eip155-5000json

there is a dot missing here

2022-11-04 06:56 UTC, chengwenxi commented
> eip155-5000json
> 
> there is a dot missing here

Thanks for the review, added the missing dot.

2022-11-08 18:14 UTC, ligi requested changes
short name must be unique - but found `MANTLE` more than once

2022-11-29 04:51 UTC, ligi requested changes
The explorers are not reachable

2022-11-29 05:05 UTC, chengwenxi commented
> The explorers are not reachable

Once the blockchain is launched, explorers will be reachable.

2022-11-29 05:06 UTC, ligi commented
ping me then - cant merge now as I cannot verify the explorers

2022-12-12 02:07 UTC, ligi commented
no it's not - explorers are not reachable

2022-12-13 23:42 UTC, shidaxi commented
@ligi our testnet sites are avaiable now but mainnet is WIP at the moment and not publicly accessible. We can roll out a initial version first. Now it's available. Pls check again https://explorer.mantle.xyz . Thank you very much!

2022-12-16 10:17 UTC, shidaxi commented
Hey @ligi , is there any update?

2022-12-16 11:48 UTC, chengwenxi commented on _data/chains/eip155-5001.json
> +      "url": "https://explorer.testnet.mantle.xyz",
```suggestion
      "url": "https://explorer.mantle.xyz",
```

Seems that the testnet explorer is same as mainnet, can you update it?

2022-12-17 06:10 UTC, ligi approved these changes

2022-12-17 06:11 UTC, merged