add Glif Explorer as Filecoin Wallaby explorer
ethereum-lists/chains pull request #1793
Opened 2022-10-28 14:17 UTC by mur-me

Hi, I've just added one more explorer for Filecoin wallaby network

Example of work using `EIP3091` standard:
https://explorer.glif.io/wallaby/tx/0xbabe0c9aa93ab52696d5a3881ae2b64a3ccab9ede8f0c452c52a133a8865ef3b/

2022-10-28 14:54 UTC, raulk approved these changes

2022-10-28 15:42 UTC, mur-me commented
Hey @raulk I can't merge it, probably you can do it :smile:

2022-10-29 14:40 UTC, ligi requested changes
https://explorer.glif.io/wallaby is a 404 - also when it comes to block it does not seem to respect the EIP

2022-10-31 16:11 UTC, mur-me commented
Hi @ligi,  404 is normal for https://explorer.glif.io/wallaby, because right now it is in test state and wallaby is test network, but we will fix it soon.

Speaking about EIP, I've read it and agree, move it to the `none` and will change as soon it will be fixed.
Please review and thank you for your work :pray:

2022-11-01 17:43 UTC, merged