Add Ethermint Testnet
ethereum-lists/chains pull request #182
Opened 2021-03-10 20:14 UTC by freddyli7

Add ethermint testnet chain

2021-03-10 23:38 UTC, ligi requested changes

2021-03-10 23:38 UTC, ligi commented on _data/chains/eip155-777.json
> +  "chainId": "etherminttestnet-777",
```suggestion
  "chainId": 777,
```

2021-03-10 23:38 UTC, ligi commented on _data/chains/eip155-777.json
> +  "shortName": "eth",
```suggestion
  "shortName": "emint",
```
cannot be eth

2021-03-11 16:43 UTC, freddyli7 commented on _data/chains/eip155-777.json
> +  "chainId": "etherminttestnet-777",
👌

2021-03-11 17:44 UTC, freddyli7 commented on _data/chains/eip155-777.json
> +  "shortName": "eth",
👌

2021-03-11 20:35 UTC, ligi approved these changes

2021-03-11 20:36 UTC, merged