eip155-877.json
ethereum-lists/chains pull request #1859
Opened 2022-11-10 02:58 UTC by Dexit-Network

please add Dexit mainnet RPC

2022-11-14 20:04 UTC, ligi requested changes

2022-11-14 20:04 UTC, ligi commented on _data/chains/eip155-877.json
> +
```suggestion
    "https://rpc.dexit.network"
```

2022-11-14 20:08 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also:  The Icon DXT does not exist - was used in eip155-877.json

2022-11-16 04:48 UTC, ligi commented
?

2022-12-10 02:00 UTC, Dexit-Network commented
hi can you please advise what need to be done if possible can you please help me

2022-12-10 02:03 UTC, nutty323 approved these changes
Approved

2022-12-10 02:06 UTC, Dexit-Network reviewed
this information is correct

2022-12-10 02:22 UTC, nutty323 approved these changes

2022-12-10 02:26 UTC, nutty323 approved these changes

2022-12-11 04:42 UTC, closed without merging

2022-12-11 05:21 UTC, pranver approved these changes