Add Exosama Network
ethereum-lists/chains pull request #1861
Opened 2022-11-10 14:08 UTC by tuimf

Added Exosama Network ( chain ID: 2109)

2022-11-11 05:12 UTC, hoanglamcoin approved these changes

2022-11-14 20:17 UTC, ligi requested changes
where did you pin the IPFS CID? I could not resolve it via `ipfs get`

2022-11-14 21:13 UTC, tuimf commented
> where did you pin the IPFS CID? I could not resolve it via `ipfs get`

Hey ligi, it's on pinata.
Did a few tests from my machine and other public gateways and looks good to me:

/ # ipfs get QmaQxfwpXYTomUd24PMx5tKjosupXcm99z1jL1XLq9LWBS
Saving file(s) to QmaQxfwpXYTomUd24PMx5tKjosupXcm99z1jL1XLq9LWBS
 14.29 KiB / 14.29 KiB [===============================================================================================================================================================================] 100.00% 0s

https://gateway.ipfs.io/ipfs/QmaQxfwpXYTomUd24PMx5tKjosupXcm99z1jL1XLq9LWBS

https://cloudflare-ipfs.com/ipfs/QmaQxfwpXYTomUd24PMx5tKjosupXcm99z1jL1XLq9LWBS

Thanks

2022-11-16 15:08 UTC, milad237 approved these changes

2022-11-18 14:51 UTC, merged