Addition of Calypso NFT Hub | SKALE Chain
ethereum-lists/chains pull request #1876
Opened 2022-11-15 15:17 UTC by TheGreatAxios

2022-11-15 17:24 UTC, ligi requested changes
Please consider contributing to our grant: https://gitcoin.co/grants/2974/ethereum-lists
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2022-11-16 04:46 UTC, milad237 commented
> # Calypso NFT Hub
> The Calypso NFT Hub is a chain apart of the multi-chain SKALE Network. This chain is part of the community hub model. 
> It is designed to be shared by many dApps in order to best utilize resources in addition to optimizing user experience. 
>

2022-11-16 04:46 UTC, milad237 commented
- [ ]

2022-11-16 04:46 UTC, milad237 approved these changes

2022-11-16 04:46 UTC, milad237 commented on _data/chains/eip155-1564830818.json
> +  "infoURL": "https://calypsohub.network/",
- [ ]

2022-11-16 05:23 UTC, kamikase2005 approved these changes

2022-11-16 14:35 UTC, TheGreatAxios commented
@ligi Ran the prettier function as requested.
Hopefully that fixes this issue!

2022-11-17 22:10 UTC, TheGreatAxios commented
@milad237 @kamikase2005 I pushed the changes as requested. 
Can you please re-review. 

Thank you!

2022-11-18 03:21 UTC, TheGreatAxios commented
@ligi Not sure why another repo was tagged above, but can you please confirm whether this can be merged or not? 

Thanks!

2022-11-18 03:47 UTC, ligi approved these changes

2022-11-18 03:47 UTC, merged