added QomL1 testnet, mainnet and icon
ethereum-lists/chains pull request #1905
Opened 2022-11-20 21:56 UTC by encrypt3dw4lrus

The mainnet isn't live yet, the testnet is in private testnet, will be exposed soon to the the dns when we start up the testnet

2022-11-20 22:01 UTC, backend69 approved these changes

2022-11-20 22:02 UTC, backend69 approved these changes

2022-11-20 22:02 UTC, backend69 approved these changes

2022-11-21 06:21 UTC, ligi requested changes

2022-11-21 06:21 UTC, ligi commented on _data/icons/ql1.json
> +
```suggestion
```

2022-11-21 15:19 UTC, encrypt3dw4lrus commented
Addressed the comment

2022-11-21 15:25 UTC, ligi requested changes
chainId must match the filename

2022-11-23 00:22 UTC, ligi approved these changes

2022-11-23 00:22 UTC, merged