Create eip155-4689.json and eip155-4690.json
ethereum-lists/chains pull request #194
Opened 2021-03-24 00:20 UTC by raullenchai

2021-03-24 00:40 UTC, raullenchai commented
@ligi - pls help with the code review.

2021-03-24 01:40 UTC, ququzone commented on _data/chains/eip155-4690.json
> +  "name": "IoTeX Network Mainnet",
should be `IoTeX Network Testnet` ?

2021-03-24 23:02 UTC, ligi requested changes
short names must be unique and shorter than name

2021-03-24 23:32 UTC, raullenchai commented
> short names must be unique and shorter than name

Fixed. PTAL

2021-04-03 13:53 UTC, ligi commented
Oh sorry - missed the notification - just saw it when you closed the issue - would merge - why did you close?

2021-04-03 14:13 UTC, raullenchai commented
> Oh sorry - missed the notification - just saw it when you closed the issue - would merge - why did you close?

Reopened, I thought I need another pr to pass the tests

2021-04-03 14:20 UTC, ligi approved these changes

2021-04-03 14:20 UTC, merged

2021-04-03 14:21 UTC, ligi commented
no you passed the tests - was just human (me) error here - sorry for the delay