feat: add SPS chainId and SPSTest chianId
ethereum-lists/chains pull request #1948
Opened 2022-11-27 17:14 UTC by Clubswap

Please verify the request.

The SPS and SPS-Testnet is proposed and the testnet is running on.  The SPS is incubating.

Thanks a lot.

2022-11-28 05:22 UTC, ligi requested changes
short name must be unique - but found `SPS-TEST` more than once

2022-11-28 05:35 UTC, LycrusHamster commented
> short name must be unique - but found `SPS-TEST` more than once

Oooops, sorry for my recklessness

2022-11-28 05:43 UTC, Clubswap commented
> short name must be unique - but found `SPS-TEST` more than once

Sorry for my recklessness.

2022-11-28 06:08 UTC, ligi requested changes
the explorer URLs do not seem to work

2022-11-28 09:08 UTC, Clubswap commented
> the explorer URLs do not seem to work

which one? 
The SPS testnet explorer https://explorer.3sps.net/ is working perfectly.
The SPS explorer might be out-of-service, cause it's incubating :)    It's fixed and running now.

2022-11-29 01:37 UTC, Clubswap commented
Move testnet explorer from https://www.3sps.net/ to https://explorer.3sps.net/

2022-11-29 01:41 UTC, ligi requested changes

2022-11-29 01:41 UTC, ligi commented on _data/chains/eip155-14000.json
> +      "url": "https://explorer.3sps.net/",
```suggestion
      "url": "https://explorer.3sps.net",
```

2022-11-29 01:44 UTC, ligi approved these changes

2022-11-29 01:44 UTC, merged