Armonia Meta Chain - Eva and Wall-e for EVM
ethereum-lists/chains pull request #1956
Opened 2022-11-29 06:24 UTC by masteraychen

Need to have unique chain IDs reserved for our EVM-compatible mainnet & testnet chains:
 - Eva chain: mainnet
 - Wall-e chain: testnet

2022-11-29 15:26 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2022-11-29 15:26 UTC, ligi commented
also https://evascan.io is not reachable

2022-11-30 12:36 UTC, masteraychen commented
removed the mainnet explorer as it's being developed.

2022-12-01 05:36 UTC, masteraychen commented
Pls kindly let me know if anything that needs be done further

2022-12-04 20:31 UTC, ligi requested changes

2022-12-04 20:31 UTC, ligi commented on _data/chains/eip155-160.json
> +  "faucets": [""],
```suggestion
  "faucets": [],
```

2022-12-04 20:31 UTC, ligi commented on _data/chains/eip155-161.json
> +  "faucets": [""],
```suggestion
  "faucets": [],
```

2023-01-19 11:13 UTC, masteraychen commented
Pls revive it

2023-01-19 15:15 UTC, merged