Add Gitshock Chain
ethereum-lists/chains pull request #1961
Opened 2022-11-30 14:38 UTC by avenbreaks

Adding new Gitshockchain Evm

2022-11-30 15:28 UTC, ligi requested changes
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

2022-11-30 15:59 UTC, avenbreaks commented
> tl;dr: it is now required to put the binary icon into iconDownload
> 
> why: it was a PITA to always `ipfs get` in the review process - sometimes it takes _really long_ or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

sorry I forgot to add the icon to the folder, now I have added it

2022-11-30 16:11 UTC, ligi commented on _data/icons/gitshockchain.json
> +
```suggestion
```

2022-11-30 17:03 UTC, ligi requested changes
chainId must match the filename

2022-11-30 17:10 UTC, avenbreaks commented
> chainId must match the filename



> chainId must match the filename

other chains have used our chainid, what is the solution?

2022-11-30 17:15 UTC, ligi commented
https://github.com/ethereum-lists/chains#collision-management

2023-01-16 11:41 UTC, closed without merging

2023-01-17 05:29 UTC, avenbreaks commented
> N

sorry we open new PR, this PR old and chainId already exist.