add CloudTx Chain
ethereum-lists/chains pull request #1974
Opened 2022-12-03 07:52 UTC by massanto

add CloudTX mainnet adn CLoudTx Testnet

2022-12-03 13:46 UTC, Ukandu147 approved these changes

2022-12-03 18:52 UTC, ligi requested changes
short name must be unique - but found `CLD` more than once

2022-12-03 19:23 UTC, ligi requested changes
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

2022-12-03 19:40 UTC, massanto commented
> tl;dr: it is now required to put the binary icon into iconDownload
> 
> why: it was a PITA to always `ipfs get` in the review process - sometimes it takes _really long_ or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

thanks you, I don't know add CID on iconDownload.
just code name ? like QmSEsi71AdA5HYH6VNC5QUQezFg1C7BiVQJdx1VVfGz3g3

2022-12-04 15:36 UTC, ligi commented
size of the icon is wrong:

QmSEsi71AdA5HYH6VNC5QUQezFg1C7BiVQJdx1VVfGz3g3 PNG 713x830 713x830+0+0 8-bit sRGB 121957B 0.000u 0:00.000

2022-12-04 22:25 UTC, massanto commented
> 

noted, we will change

2022-12-04 23:18 UTC, ligi requested changes

2022-12-04 23:18 UTC, ligi commented on _data/icons/cloudtx.json
> +    "format": "PNG"
```suggestion
    "format": "png"
```

2022-12-04 23:20 UTC, merged

2022-12-04 23:31 UTC, massanto commented on _data/chains/eip155-31223.json
> +  "rpc": ["https://mainnetrpc.num.network"],
i will change the RPC mainnet to https://mainnet-rpc.cloudtx.finance