add eip155-3912.json add drac.json
ethereum-lists/chains pull request #1992
Opened 2022-12-08 03:05 UTC by DRAC-Network

add DRAC Chain
Update _data/chains/eip155-3912.json
Update _data/chains/drac.json

add new network, include icon RPC website  chainId explorers

2022-12-10 00:57 UTC, ligi commented on _data/icons/drac.json
> +    "url": "ipfs://bafybeihogmgrzljritbv2sdkoj3r34iiueg2oyby6uibk36uznuar4bvuu",
```suggestion
    "url": "ipfs://QmXbsQe7QsVFZJZdBmbZVvS6LgX9ZFoaTMBs9MiQXUzJTw",
```

2022-12-13 01:57 UTC, DRAC-Network commented
modify eip155-3912.json
ShortName must match this pattern: '^[A-Za-z0-9-_]{1,64}$'

2022-12-13 02:00 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2022-12-14 20:36 UTC, DRAC-Network commented
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

It has been modified and updated as required, please check for confirmation.Thank you.

2022-12-14 21:45 UTC, ligi approved these changes

2022-12-17 06:14 UTC, merged