add oCash Chocolate Chicken Testnet
ethereum-lists/chains pull request #1994
Opened 2022-12-08 16:34 UTC by p0nch00

2022-12-10 02:01 UTC, ligi requested changes
filename extension must be json

2022-12-16 13:29 UTC, p0nch00 commented
fixed

2023-01-03 11:50 UTC, ligi commented
do not use special chars in names

2023-02-17 20:15 UTC, Amazinggrace07 approved these changes

2023-02-25 02:00 UTC, closed without merging