Add Mythical icon
ethereum-lists/chains pull request #2024
Opened 2022-12-13 17:55 UTC by drew-meshreky-mg

2022-12-13 18:01 UTC, milad237 approved these changes
0x302F5F5b0A79b2333888886c7651B7EC0b7855F4

2022-12-14 01:39 UTC, Uzocoiny-source approved these changes
_data/chains/eip155-151.json

2022-12-15 09:56 UTC, ligi requested changes

2022-12-15 09:56 UTC, ligi commented on _data/chains/eip155-201804.json
> +    "url": "https://explorer.mythicalgames.com/",
```suggestion
    "url": "https://explorer.mythicalgames.com",
```

2022-12-16 01:22 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2022-12-20 12:53 UTC, merged