Update logo + eip155-217.json
ethereum-lists/chains pull request #2087
Opened 2023-01-02 12:54 UTC by warewar1

2023-01-02 17:11 UTC, ligi requested changes
please resolve conflicts

2023-01-02 23:06 UTC, warewar1 commented
Resolve

2023-01-02 23:07 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also remove bafybeifp6dbzrzrpsgtsxvlbffhxgtdlvbmmsbvlmk2ukeakjhu5ug4ycy from iconDownload and add the new one

2023-01-03 10:45 UTC, ligi approved these changes

2023-01-03 10:45 UTC, merged