Add Network Eightbox Testnet
ethereum-lists/chains pull request #2101
Opened 2023-01-05 18:46 UTC by eightbox

Add Network Eightbox Testnet

2023-01-05 20:00 UTC, ligi requested changes
tl;dr: it is now required to put the binary icon into iconDownload

why: it was a PITA to always `ipfs get` in the review process - sometimes it takes *really long* or even fails (especially with pinata) - this took significant time (which adds up with the amount of chains added) and slowed down the review process. Also sometimes CIDs become unavailable after - big mess. Hence it is now required to put them in iconDownload (still named via CID)

2023-01-05 20:00 UTC, ligi commented on _data/icons/eightbox.json
> +
```suggestion
```

2023-01-05 23:04 UTC, eightbox commented
@ligi I've got the CID file, but I don't know how to download it. I'm using webui ipfs
![image](https://user-images.githubusercontent.com/120139020/210896853-b33be41a-bcc5-411a-9c66-15c004ea11b6.png)

2023-01-05 23:07 UTC, eightbox commented
I've uploaded it on the pinata but the status is searching

![image](https://user-images.githubusercontent.com/120139020/210897097-935c36b2-5336-4baa-842e-824a993b0e78.png)

2023-01-06 08:44 UTC, ligi requested changes

2023-01-06 08:44 UTC, ligi commented on _data/icons/eightbox.json
> +    "url": "https://ipfs.eightbox.org/QmQ516hXZRyoNCJ7mXwG4fN4ECQRvkB3EmDpyBR8GTdxgR",
```suggestion
    "url": "ipfs://QmQ516hXZRyoNCJ7mXwG4fN4ECQRvkB3EmDpyBR8GTdxgR",
```

2023-01-06 16:51 UTC, eightbox commented
why does it always fail? is there any solution?

2023-01-06 16:53 UTC, ligi commented
The image you uploaded is not a image ..

2023-01-06 20:32 UTC, eightbox commented
> The image you uploaded is not a image ..

Then can you help me? because I've followed various ways on Google, but haven't found it

2023-01-06 20:44 UTC, ligi commented
send me the icon and 100DAI - I can't help random chains for free - the day only has 24h

2023-01-07 20:44 UTC, Aqeebrao approved these changes

2023-01-07 20:51 UTC, Aqeebrao approved these changes
#2101

2023-03-07 02:06 UTC, closed without merging