add Giant Mammoth Chain
ethereum-lists/chains pull request #2109
Opened 2023-01-09 08:38 UTC by MammothDevMaster

add Giant Mammoth Chain

2023-01-11 08:27 UTC, ligi requested changes

2023-01-11 08:27 UTC, ligi commented on _data/icons/gmmt.json
> +
```suggestion
```

2023-01-11 08:27 UTC, ligi commented on _data/chains/eip155-8989.json
> +        "url": "https://scan.gmmtchain.io/",
```suggestion
        "url": "https://scan.gmmtchain.io",
```

2023-01-13 10:31 UTC, ligi requested changes

2023-01-13 10:31 UTC, ligi commented on _data/icons/gmmt.json
> +      "url" : " ipfs://QmVth4aPeskDTFqRifUugJx6gyEHCmx2PFbMWUtsCSQFkF" ,
```suggestion
      "url" : "ipfs://QmVth4aPeskDTFqRifUugJx6gyEHCmx2PFbMWUtsCSQFkF" ,
```

2023-01-13 10:36 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-01-16 05:48 UTC, MammothDevMaster commented
Merge and prettier update Finish

2023-01-16 12:09 UTC, ligi requested changes

2023-01-16 12:09 UTC, ligi commented on _data/icons/gmmt.json
> +    "url": " ipfs://QmVth4aPeskDTFqRifUugJx6gyEHCmx2PFbMWUtsCSQFkF",
```suggestion
    "url": "ipfs://QmVth4aPeskDTFqRifUugJx6gyEHCmx2PFbMWUtsCSQFkF",
```

2023-01-16 12:19 UTC, ligi approved these changes

2023-01-16 12:22 UTC, merged