Renaming Buildernet to Hyperspace testnet
ethereum-lists/chains pull request #2120
Opened 2023-01-10 14:41 UTC by eshon

Also adding more explorers and an RPC endpoint

2023-01-10 15:00 UTC, raulk approved these changes

2023-01-11 08:23 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-01-11 12:05 UTC, ligi requested changes

2023-01-11 12:05 UTC, ligi commented on _data/chains/eip155-3141.json
> +      "standard": "EIP3091"
this one also does not really support EIP3091 - e.g. blocks and tokens seem to be unsupported. Maybe https://github.com/ChainAgnostic/CAIPs/pull/200 can help in the future - but for now we should set to none to be able to merge 

```suggestion
      "standard": "none"
```

2023-01-11 12:05 UTC, ligi commented on _data/chains/eip155-31415.json
> +      "standard": "EIP3091"
see above
```suggestion
      "standard": "none"
```

2023-01-11 13:39 UTC, merged