Create eip155-1455.json
ethereum-lists/chains pull request #2132
Opened 2023-01-12 20:23 UTC by ctextoken

2023-01-12 20:29 UTC, ctextoken commented
please add ctex scan blockchain to chainlist

2023-01-13 09:57 UTC, ctextoken commented
please add ctex scan blockchain to chainlist

2023-01-13 09:58 UTC, ligi requested changes

2023-01-13 09:58 UTC, ligi commented on _data/chains/eip155-1455.json
> +      "url": "https://ctexscan.com/",
```suggestion
      "url": "https://ctexscan.com",
```

2023-01-13 10:03 UTC, ligi approved these changes

2023-01-13 10:03 UTC, merged

2023-01-13 10:05 UTC, ctextoken commented
hello @ligi  when it will show on https://chainlist.org/ and also i have created pull request for rpc adding kindly approve that also https://github.com/DefiLlama/chainlist/pull/301

2023-01-13 10:24 UTC, ligi commented
I do not care for Defi and/or Lamas

2023-01-13 10:29 UTC, ctextoken commented
ok sorry for that , please add ctex chain to chainlist.org website

2023-01-13 10:29 UTC, ctextoken commented
also where else we can add ctex chain

2023-01-13 11:16 UTC, ctextoken commented
hello @ligi  please add it on https://chainlist.org/ and https://chainlist.wtf/