add home_verse
ethereum-lists/chains pull request #2143
Opened 2023-01-16 01:48 UTC by phi7

Create eip155-19011.json
Create home_verse.json

Thank you!

2023-01-16 11:51 UTC, ligi requested changes

2023-01-16 11:51 UTC, ligi commented on _data/chains/eip155-19011.json
> +        "url": "https://explorer.oasys.homeverse.games/",
```suggestion
        "url": "https://explorer.oasys.homeverse.games",
```

2023-01-16 14:48 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-01-18 02:27 UTC, phi7 commented
I run the prerinter!

2023-01-19 15:24 UTC, ligi requested changes

2023-01-19 15:24 UTC, ligi commented on _data/chains/eip155-19011.json
> +      "url": "https://explorer.oasys.homeverse.games/",
```suggestion
      "url": "https://explorer.oasys.homeverse.games",
```

2023-01-19 17:34 UTC, ligi approved these changes

2023-01-19 17:34 UTC, merged