add Liveplex OracleEVM network
ethereum-lists/chains pull request #2156
Opened 2023-01-18 10:23 UTC by salim-mahat

2023-01-18 10:28 UTC, ligi requested changes
shortName cannot be empty

2023-01-19 03:57 UTC, salim-mahat commented
shortname added

On Wed, Jan 18, 2023 at 3:58 PM ligi ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> shortName cannot be empty
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/2156#pullrequestreview-1253212220>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASIAJJQMZJIR7TGRRE7FD6LWS7AUFANCNFSM6AAAAAAT64XOSU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-22 17:37 UTC, ligi approved these changes

2023-01-22 17:37 UTC, merged

2023-01-23 04:21 UTC, salim-mahat commented
How long after the code was merged on the master branch will it take for my
network to be visible in chainlist.org's network side?

On Sun, Jan 22, 2023 at 11:07 PM ligi ***@***.***> wrote:

> Merged #2156 <https://github.com/ethereum-lists/chains/pull/2156> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/2156#event-8329241043>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASIAJJQQAOUELXCIQAFAKNLWTVV6PANCNFSM6AAAAAAT64XOSU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>