add dogcoin to the chain list
ethereum-lists/chains pull request #2158
Opened 2023-01-18 11:29 UTC by solidityx

2023-01-18 11:34 UTC, ligi requested changes
also why 2 jsons for same icons?

2023-01-18 11:34 UTC, ligi commented on _data/chains/eip155-1117.json
> +      "standard": "EIP3091"
explorer is not reachable

2023-02-04 04:43 UTC, solidityx commented
> also why 2 jsons for same icons?

One for mainnet and second for testnet, but I'll remove and keep just one

2023-02-04 15:53 UTC, ligi approved these changes

2023-02-04 17:19 UTC, ligi approved these changes

2023-02-04 17:20 UTC, merged

2024-08-05 14:33 UTC, dicv2 commented
ARB