please add blockton blockchain to chainlist
ethereum-lists/chains pull request #2170
Opened 2023-01-21 10:48 UTC by blocktoncoin

please add blockton blockchain to chainlist

2023-01-21 16:10 UTC, ligi requested changes

2023-01-21 16:10 UTC, ligi commented on _data/chains/eip155-8272.json
> +      "url": "https://blocktonscan.com/",
```suggestion
      "url": "https://blocktonscan.com",
```

2023-01-21 16:11 UTC, ligi commented
The contrast in your explorer is really bad:

![image](https://user-images.githubusercontent.com/111600/213875888-e27662b3-3ef0-4e79-b573-57ef6585a479.png)

2023-01-21 16:29 UTC, blocktoncoin commented
yes ligi the transaction is ongoing.

2023-01-21 16:30 UTC, blocktoncoin commented
please add the chain

2023-01-21 16:34 UTC, ligi approved these changes

2023-01-21 16:34 UTC, merged

2023-01-21 16:45 UTC, blocktoncoin commented
thanks @ligi for adding blockton when we expect blockton live on chainlist.org

2023-02-15 11:31 UTC, blocktoncoin commented
hello please add our mainnet coin we are listed on cmc

https://coinmarketcap.com/currencies/blockton/