Update eip155-269.json
ethereum-lists/chains pull request #221
Opened 2021-04-14 13:40 UTC by wgllele

Update to the latest HPB information.

2021-04-14 16:48 UTC, ligi requested changes
When you use an icon - please also provide the icon definition as outlined in the readme

2021-04-15 01:38 UTC, ligi requested changes

2021-04-15 01:38 UTC, ligi commented on _data/chains/eip155-269.json
> +  "networkId": 100
```suggestion
  "networkId": 100,
```

2022-03-11 23:10 UTC, Lucid369 approved these changes

2022-04-30 02:12 UTC, closed without merging