Update eip155-269.json
ethereum-lists/chains pull request #222
Opened 2021-04-15 01:46 UTC by wgllele

Update to the correct information.

2021-04-15 05:15 UTC, ligi reviewed
Why did you remove slip-44?

2021-04-21 11:35 UTC, ligi requested changes
Should not remove the SLIP44

2021-04-25 01:10 UTC, Hubtig23 commented
This should be used as reference material it have predictable and constant environment deployment as a gain

2021-04-25 01:11 UTC, Hubtig23 commented
#229

2022-04-23 02:05 UTC, closed without merging