Add ENULS Chain (mainnet & testnet)
ethereum-lists/chains pull request #2224
Opened 2023-02-02 03:04 UTC by niels1286

[I make a pin the icon at : https://ipfs.io/ipfs/QmYz8LK5WkUN8UwqKfWUjnyLuYqQZWihT7J766YXft4TSy?filename=ENULS.svg](https://github.com/ethereum-lists/chains/pull/1588)

2023-02-02 12:04 UTC, ligi requested changes

2023-02-02 12:04 UTC, ligi commented on _data/chains/eip155-119.json
> +  "network": "mainnet",
```suggestion
```

2023-02-02 12:04 UTC, ligi commented on _data/chains/eip155-120.json
> +  "network": "testnet",
```suggestion
```

2023-02-02 12:13 UTC, ligi requested changes
short name must be unique - but found `ENULS` more than once

2023-02-02 14:11 UTC, niels1286 commented
> 

I have fixed this problem, please deal with it again, thank you

2023-02-04 03:15 UTC, niels1286 commented
I update the code format . All matched files use Prettier code style!

2023-02-04 06:19 UTC, merged