added saakuru chain
ethereum-lists/chains pull request #2227
Opened 2023-02-02 14:15 UTC by aag-victor

2023-02-02 15:48 UTC, ligi approved these changes

2023-02-02 15:48 UTC, ligi commented on _data/chains/eip155-247253.json
> +      "url": "https://explorer-testnet.saakuru.network/",
```suggestion
      "url": "https://explorer-testnet.saakuru.network",
```

2023-02-02 15:48 UTC, ligi commented on _data/chains/eip155-247253.json
> +      "url": "https://explorer-testnet.saakuru.network/",
```suggestion
      "url": "https://explorer-testnet.saakuru.network",
```

2023-02-02 15:48 UTC, ligi commented on _data/chains/eip155-7225878.json
> +      "url": "https://explorer.saakuru.network/",
```suggestion
      "url": "https://explorer.saakuru.network",
```

2023-02-03 05:56 UTC, ariel3112 approved these changes

2023-02-04 02:29 UTC, ligi requested changes
short name must be unique - but found `OAS` more than once

2023-02-04 07:40 UTC, aag-victor commented
short name changed. please check. thanks!

2023-02-04 15:34 UTC, ligi approved these changes

2023-02-04 15:34 UTC, merged