Create eip155-424242.json
ethereum-lists/chains pull request #2234
Opened 2023-02-03 09:54 UTC by terjanyan

Added Fastex Chain

2023-02-03 13:09 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

 The Icon ftn does not exist - was used in eip155-424242.json

2023-02-04 10:06 UTC, ponury1990 approved these changes

2023-02-04 10:06 UTC, ponury1990 approved these changes

2023-02-04 10:07 UTC, ponury1990 approved these changes

2023-02-04 10:07 UTC, ponury1990 approved these changes

2023-02-10 00:17 UTC, ligi approved these changes

2023-02-10 00:17 UTC, merged