Add BXN chains (testnet and mainnet)
ethereum-lists/chains pull request #2257
Opened 2023-02-09 17:56 UTC by BlackFortGroup

2023-02-09 19:50 UTC, ligi requested changes

2023-02-09 19:50 UTC, ligi commented on _data/chains/eip155-4777.json
> +  "networkId": 477,
typo?

2023-02-09 19:50 UTC, ligi commented on _data/chains/eip155-4777.json
> +    "https://testnet.blackfort.network/rpc",
```suggestion
    "https://testnet.blackfort.network/rpc"
```

2023-02-10 19:20 UTC, BlackFortGroup commented on _data/chains/eip155-4777.json
> +  "networkId": 477,
Yes, resolves in the last commit

2023-02-10 21:34 UTC, Mey1212 approved these changes

2023-02-11 16:57 UTC, ligi approved these changes

2023-02-11 16:57 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-02-12 09:42 UTC, 13364174888 approved these changes

2023-02-14 15:55 UTC, ligi approved these changes

2023-02-14 15:56 UTC, merged

2023-04-22 05:45 UTC, 13364174888 reviewed
好

2023-04-22 06:37 UTC, Mey1212 commented
i dont understand chinese