Add vechain
ethereum-lists/chains pull request #2259
Opened 2023-02-09 19:44 UTC by Bread-VeSea

2023-02-09 19:49 UTC, ligi approved these changes

2023-02-09 20:07 UTC, ligi requested changes
missing field(s) [rpc] - can be empty array

2023-02-11 19:36 UTC, Bread-VeSea commented
> missing field(s) [rpc] - can be empty array

Added to empty array to both main and testnet files

2023-02-12 01:47 UTC, ligi approved these changes

2023-02-12 01:47 UTC, merged

2023-02-13 02:10 UTC, regalwright approved these changes