update: canto chain rpc endpoints & explorer endpoints
ethereum-lists/chains pull request #2274
Opened 2023-02-13 08:14 UTC by jessepinkman9900

2023-02-13 10:46 UTC, Bjonesca30 approved these changes

2023-02-14 05:16 UTC, jessepinkman9900 commented
Thanks @Bjonesca30! Can you merge this as well?

2023-02-14 15:46 UTC, ligi requested changes

2023-02-14 15:46 UTC, ligi commented on _data/chains/eip155-7700.json
> +    },
please add this on the end

2023-02-14 15:46 UTC, ligi commented on _data/chains/eip155-7700.json
> +  "rpc": ["https://canto.neobase.one", "https://canto.slingshot.finance"],
please add the new RPC as last entry

2023-02-16 05:45 UTC, jessepinkman9900 commented
have resolved the issues. please review @ligi 
thanks!

2023-02-17 13:58 UTC, ligi approved these changes

2023-02-17 13:58 UTC, merged