Add MARO Blockchain
ethereum-lists/chains pull request #2291
Opened 2023-02-17 06:19 UTC by TTCOffical

2023-02-17 13:57 UTC, ligi requested changes

2023-02-17 13:57 UTC, ligi commented on _data/chains/eip155-8848.json
> +      "standard": "EIP3091"
```suggestion
      "standard": "none"
```

2023-02-18 15:45 UTC, Marvin8122 approved these changes

2023-02-18 18:15 UTC, 13364174888 approved these changes

2023-02-18 19:16 UTC, 13364174888 commented
> 

好

2023-02-18 19:17 UTC, 13364174888 approved these changes
好

2023-02-18 19:26 UTC, 13364174888 commented on _data/chains/eip155-8848.json
> +      "standard": "EIP3091"
我

2023-02-19 06:18 UTC, ligi commented on _data/chains/eip155-8848.json
> +      "url": "https://scan.ma.ro/#/",
```suggestion
      "url": "https://scan.ma.ro/#",
```

2023-02-19 06:18 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-02-19 12:50 UTC, TTCOffical commented
Hi, thanks for reviewing for our chains, we just delete the icon firstly and process it later, thanks

2023-02-19 14:41 UTC, Marvin8122 approved these changes

2023-02-19 21:09 UTC, ligi approved these changes

2023-02-19 21:09 UTC, merged