added IceCreamSwap public RPC for CORE blockchain
ethereum-lists/chains pull request #2303
Opened 2023-02-19 12:32 UTC by simone1999

2023-02-19 19:48 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-02-27 22:39 UTC, simone1999 commented
ok, now ran prettier. for me definitely looks worse than before, but I guess prettier knows what it is doing haha

2023-03-16 00:47 UTC, simone1999 commented
@ligi please check again, the pipeline seems to be stuck.

2023-03-16 07:55 UTC, ligi approved these changes

2023-03-16 07:55 UTC, merged

2023-03-19 04:35 UTC, alokeutpal approved these changes