Add icons for Autonity testnets
ethereum-lists/chains pull request #2323
Opened 2023-02-24 02:01 UTC by flofrie

2023-02-24 09:07 UTC, ligi requested changes
please put your icon in iconDownload so the CI can check it. Seeing some diff here:

```
identify Qmae5oAFpcCG1MEMBwGbNodHAR3wqPBxQkon28AF2SfKTX         09:36:19
Qmae5oAFpcCG1MEMBwGbNodHAR3wqPBxQkon28AF2SfKTX SVG 81x81 81x81+0+0 8-bit sRGB 1824B 0.000u 0:00.000
```

2023-02-27 09:51 UTC, flofrie commented
@ligi or someone else, please review again; this should all be working now.

2023-02-28 10:19 UTC, flofrie commented
> please put your icon in iconDownload so the CI can check it. Seeing some diff here:
> 
> ```
> identify Qmae5oAFpcCG1MEMBwGbNodHAR3wqPBxQkon28AF2SfKTX         09:36:19
> Qmae5oAFpcCG1MEMBwGbNodHAR3wqPBxQkon28AF2SfKTX SVG 81x81 81x81+0+0 8-bit sRGB 1824B 0.000u 0:00.000
> ```

@ligi , we've addressed your comment; can you please have another look and review? (If not you, should we be contacting someone else? We're not 100% certain of the process ...)

2023-02-28 10:21 UTC, ligi approved these changes

2023-02-28 10:21 UTC, merged