Update Twala Testnet (Jellie)
ethereum-lists/chains pull request #2327
Opened 2023-02-24 14:16 UTC by apquinit

2023-02-24 15:02 UTC, ligi requested changes

2023-02-24 15:02 UTC, ligi commented on _data/chains/eip155-202624.json
> +  "network": "testnet",
```suggestion
```

2023-03-02 07:28 UTC, apquinit commented
JSON updated @ligi

2023-03-09 14:46 UTC, apquinit commented
bump @ligi

2023-04-08 19:56 UTC, ligi commented
Fix CI errors like this one:
Found file QmTXJVhVKvVC7DQEnGKXvydvwpvVaUEBJrMHvsCr4nr1sK in ../_data/iconsDownload that is not referenced

2023-05-28 01:59 UTC, closed without merging