add kcc testnet
ethereum-lists/chains pull request #233
Opened 2021-04-26 03:40 UTC by lingyun92

2021-04-26 10:26 UTC, ligi requested changes
The exporers section is invalid JSON
Also the exporer does not adhere EIP3091 (block is broken - https://scan-testnet.kucoin.one/block/32735)
So they either need to change this or create their own standard

2021-04-29 01:53 UTC, lingyun92 commented
> The exporers section is invalid JSON
> Also the exporer does not adhere EIP3091 (block is broken - https://scan-testnet.kucoin.one/block/32735)
> So they either need to change this or create their own standard

fixed, thanks.

2021-04-29 06:38 UTC, ligi commented
Great! Seems the explorer is close to following the standard now - only tokens is still wrong as far as I see.
https://scan-testnet.kucoin.one/token/0xb296bab2ed122a85977423b602ddf3527582a3da

Also please add the  "standard": "EIP3091" then - after I can merge

2021-04-29 13:33 UTC, lingyun92 commented
> Great! Seems the explorer is close to following the standard now - only tokens is still wrong as far as I see.
> https://scan-testnet.kucoin.one/token/0xb296bab2ed122a85977423b602ddf3527582a3da
> 
> Also please add the "standard": "EIP3091" then - after I can merge

works now

2021-04-29 13:45 UTC, ligi requested changes
CI found this extra comma and complained about it

2021-04-29 13:45 UTC, ligi commented on _data/chains/eip155-322.json
> +    "https://rpc-testnet.kucoin.one",
```suggestion
    "https://rpc-testnet.kucoin.one"
```

2021-04-29 14:08 UTC, ligi approved these changes

2021-04-29 14:08 UTC, merged

2021-04-29 14:08 UTC, ligi commented
Long time in the making - but finally merged ;-)