KLYNTAR listing
ethereum-lists/chains pull request #2335
Opened 2023-02-26 12:23 UTC by VladChernenko

<div align="center">

### KLYNTAR - nextgen, "cloud-of-everything" project that relies on decentralization & security & TPS of all blockchains in the industry, has multilevel sharding, multitasking, EVM & WASM & Docker compatibility, post-quantum cryptography, RWX codeless smart-contracts, etc.

<a href="https://github.com/KLYN74R">🔥Follow us!🔥</a>

<img src="https://user-images.githubusercontent.com/53381472/220953430-e8841c35-1832-411d-b0da-a8247c8242b7.jpg">

</div>

2023-02-26 13:45 UTC, VladChernenko commented
Added more commits after Prettier execution

2023-02-26 16:57 UTC, ligi requested changes

2023-02-26 16:57 UTC, ligi commented on _data/chains/eip155-7331.json
> +      "url": "https://klyntarscan.org",
this URL is not reachable

2023-02-28 10:23 UTC, ligi requested changes
explorer is still not reachable - also if this is a incubating chain add status incubating

2023-03-01 11:37 UTC, VladChernenko commented
@ligi Decided to remove explorer URL and add a status

2023-03-01 21:41 UTC, merged