Add quarix Blockchain mainnet and testnet
ethereum-lists/chains pull request #2356
Opened 2023-03-03 04:04 UTC by quarix-tech

2023-03-03 07:53 UTC, ligi requested changes
shortName must be unique

2023-03-03 10:55 UTC, ligi requested changes
The Icon quarix does not exist - was used in eip155-88888881.json

2023-03-04 14:25 UTC, Shahidul783 approved these changes

2023-03-04 14:25 UTC, Shahidul783 approved these changes

2023-03-24 08:18 UTC, quarix-tech commented
>

Fixed already, and please let me know if I am missing anything.

2023-03-26 09:45 UTC, ligi approved these changes

2023-03-26 09:45 UTC, merged