Create CAIP-2
ethereum-lists/chains pull request #2362
Opened 2023-03-05 01:03 UTC by briannichols0702

MAINNET
Chain ID: 535037 - 0x829FD
RPC : https://mainnet-rpc.bescscan.io       
Graph Node : https://thegraph.bescscan.io

Explorer : https://bescscan.io 
Staking : https://staking.bescscan.io  
Status : https://status.bescscan.io   
BOT API : https://bot.bescscan.io
Docs : https://docs.bescscan.io    
   
TESTNET
Chain ID: 892272 - 0xD9D70
RPC : https://testnet-rpc.bescscan.io 
Explorer : https://testnet-explorer.bescscan.io 
Faucet : https://faucet.bescscan.io

2023-03-05 01:10 UTC, ligi requested changes
Your filename is completely wrong

2023-03-05 01:31 UTC, briannichols0702 commented
> Your filename is completely wrong

Ahh sorry about that I believe I got it fixed.

2023-03-05 04:21 UTC, ligi commented
a bit better - still very wrong though

2023-03-05 06:26 UTC, Imebeez approved these changes

2023-03-05 07:18 UTC, ligi requested changes
nope - it really looks like you have no idea what you are doing - can someone else of your team take over? I kinda don't want to spend time reviewing your PRs for free anymore

2023-03-05 07:49 UTC, briannichols0702 commented
> nope - it really looks like you have no idea what you are doing - can someone else of your team take over? I kinda don't want to spend time reviewing your PRs for free anymore



> nope - it really looks like you have no idea what you are doing - can someone else of your team take over? I kinda don't want to spend time reviewing your PRs for free anymore

I apologize Send me an ur Busd address I’ll make it worth ur time 😂 was trying to
Get this done while
My dev has weekend
Off.

2023-03-05 07:53 UTC, ligi commented
send something to lists.eth and I fix up the PR

2023-03-05 08:08 UTC, briannichols0702 commented
> 

Sponsored you with lil something for your help

2023-03-05 08:21 UTC, ligi commented on _data/chains/eip155-535037.json
> +   "rpc": ["mainnet-rpc.bescscan.io", "thegraph.bescscan.io"],
```suggestion
   "rpc": ["https://mainnet-rpc.bescscan.io"],
```

2023-03-05 08:37 UTC, ligi approved these changes

2023-03-05 08:37 UTC, merged

2023-04-08 20:50 UTC, Imebeez reviewed
👍

2023-04-08 20:53 UTC, Imebeez reviewed
👍