Add GeneChain Adenine Testnet
ethereum-lists/chains pull request #238
Opened 2021-04-30 04:42 UTC by genechain-dev

GeneChain Adenine Testnet has been running for a while.
Here's the pull request to merge information for GeneChain adenine testnet.
Thanks!

2021-04-30 10:15 UTC, ligi requested changes
the exporer is not EIP3091 compatible - it fails for block and token

2021-05-08 08:18 UTC, genechain-dev commented
> the exporer is not EIP3091 compatible - it fails for block and token

Fixed. Please check again. Sorry for the inconvenience.

2021-05-08 09:47 UTC, ligi approved these changes

2021-05-08 09:47 UTC, merged

2021-05-08 09:47 UTC, ligi commented
Thanks for making the explorer EIP3091 compatible!