Add iExec sidechain network
ethereum-lists/chains pull request #2386
Opened 2023-03-08 08:53 UTC by gfournieriExec

This PR adds entrie for Bellecour, iExec's sidechain.

2023-03-08 14:26 UTC, ligi requested changes

2023-03-08 14:26 UTC, ligi commented on _data/chains/eip155-134.json
> +      "url": "https://blockscout.bellecour.iex.ec",
cannot be reached

2023-03-08 14:58 UTC, gfournieriExec commented on _data/chains/eip155-134.json
> +      "url": "https://blockscout.bellecour.iex.ec",
Thanks, this can be reached now

2023-03-10 05:28 UTC, ligi approved these changes

2023-03-10 05:36 UTC, merged

2023-03-10 05:36 UTC, leop6140 commented
Leop6140

On Thu, Mar 9, 2023, 10:28 PM ligi ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/2386#pullrequestreview-1334187951>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVU2XUWT534TLJJ7HQBDAGDW3K3ZHANCNFSM6AAAAAAVTPZWLI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>