Create eip155-10101.json
ethereum-lists/chains pull request #240
Opened 2021-05-01 20:38 UTC by gentlebitcz

Hello, please add Blockchain Genesis Mainnet, thanks

2021-05-02 08:28 UTC, ligi requested changes
The explorer needs to adhere to a standard. Ideally the explorer should follow EIP-3091

2021-05-05 13:14 UTC, gentlebitcz commented
Hello, thanks for info.
I've removed explorer reference

2021-05-05 13:24 UTC, ligi approved these changes

2021-05-05 13:24 UTC, merged

2021-05-05 13:24 UTC, ligi commented
Thanks! Would be good to have the explorer back at some point. Maybe via redirects?