add doschain mainnet
ethereum-lists/chains pull request #2417
Opened 2023-03-14 08:51 UTC by Dien-DOS

2023-03-14 10:29 UTC, leop6140 approved these changes

2023-03-14 11:36 UTC, ligi requested changes
I will review after you fix the CI errors

2023-03-17 09:10 UTC, Dien-DOS commented
please help me!

2023-03-23 02:31 UTC, robledo6 commented
Ahuch

2023-03-24 07:28 UTC, closed without merging