Add rikeza testnet and mainnet
ethereum-lists/chains pull request #2427
Opened 2023-03-15 11:49 UTC by iamakshaykumar

Add rikeza testnet and mainnet

2023-03-15 12:40 UTC, ligi requested changes

2023-03-15 12:40 UTC, ligi commented on httpsloader/bin/main/org/ethereum/lists/chains/https/Chain.kt
remove that file please - why is it here?

2023-03-15 12:40 UTC, ligi commented on _data/chains/eip155-12715.json
> +        "url": "https://testnet.rikscan.com/",
```suggestion
        "url": "https://testnet.rikscan.com",
```

2023-03-16 02:43 UTC, iamakshaykumar reviewed
changed

2023-03-16 06:12 UTC, closed without merging