Add Scolcoin Blockchain mainnet and testnet
ethereum-lists/chains pull request #2436
Opened 2023-03-16 16:04 UTC by scolcoin

Add eip155-65450 "Scolcoin Mainnet"
Add eip155-6552 "Scolcoin Testnet"

2023-03-16 17:35 UTC, scolcoin commented
I am waiting to be able to make modifications and be able to add the Chain of our project

2023-03-16 19:49 UTC, ligi requested changes

2023-03-16 19:49 UTC, ligi commented on _data/chains/eip155-65450.json
> +    "url": "https://explorer.scolcoin.com/",
```suggestion
    "url": "https://explorer.scolcoin.com",
```

2023-03-16 20:31 UTC, ligi requested changes
short name must be unique - but found `SCOL` more than once

also: run the prettier

2023-03-17 01:52 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

also: 

I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

2023-03-17 06:21 UTC, ligi approved these changes

2023-03-17 06:25 UTC, merged