Add DeFi Oracle Meta (138 Mainnet and 2138 Testnet)
ethereum-lists/chains pull request #2506
Opened 2023-03-26 08:00 UTC by defi-oracle

2023-03-26 09:14 UTC, Bjonesca30 approved these changes

2023-03-26 09:14 UTC, Bjonesca30 commented on _data/chains/eip155-138.json
> +   "name": "Defi Oracle Meta Mainnet",
[]()@
```suggestion
   "name": "Defi Oracle Meta Mainnet",```suggestion
   "name": "Defi Oracle Meta Mainnet",**$@9**
```

```

2023-03-26 09:40 UTC, defi-oracle reviewed
cool

2023-03-26 10:02 UTC, robledo6 commented
Aveeer

2023-03-26 16:43 UTC, ligi requested changes
Do not touch files outside _data

2023-03-26 17:14 UTC, robledo6 approved these changes

2023-03-26 17:38 UTC, closed without merging

2023-03-27 02:38 UTC, Mohito62 commented
Hi

2023-03-27 03:32 UTC, defi-oracle commented
Hello.

From: Mohito62 ***@***.***>
Sent: Sunday, March 26, 2023 7:39 PM
To: ethereum-lists/chains ***@***.***>
Cc: DeFi Oracle ***@***.***>; State change ***@***.***>
Subject: Re: [ethereum-lists/chains] Add DeFi Oracle Meta (138 Mainnet and 2138 Testnet) (PR #2506)


Hi

—
Reply to this email directly, view it on GitHub<https://github.com/ethereum-lists/chains/pull/2506#issuecomment-1484397903>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A33O7TJ7FUGG76L6VPIC5PTW6D4ULANCNFSM6AAAAAAWIA2YEQ>.
You are receiving this because you modified the open/close state.Message ID: ***@***.******@***.***>>