Add super chain.
ethereum-lists/chains pull request #2528
Opened 2023-03-28 16:47 UTC by superexchain

Add super chain.

2023-03-28 16:52 UTC, yardapen commented
I have me for it guy but someone is trying to steal them do there put up

On Tue, Mar 28, 2023, 11:48 AM superexchain ***@***.***>
wrote:

> Add super chain.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ethereum-lists/chains/pull/2528
> Commit Summary
>
>    - 8f4266c
>    <https://github.com/ethereum-lists/chains/pull/2528/commits/8f4266c110c818a3a26faf1e84983f3dda5cdaeb>
>    Add super chain.
>
> File Changes
>
> (4 files <https://github.com/ethereum-lists/chains/pull/2528/files>)
>
>    - *A* _data/chains/eip155-1969.json
>    <https://github.com/ethereum-lists/chains/pull/2528/files#diff-f015bb800e51b289c69ed1126aa2300ce26e1e7a95516ae94057a2edaa6335d4>
>    (23)
>    - *A* _data/chains/eip155-1970.json
>    <https://github.com/ethereum-lists/chains/pull/2528/files#diff-2e33172b0ccb2d8da60a86376ea6321bb911cda4bfdc28f71d5b7fbccd76f7a2>
>    (23)
>    - *A* _data/icons/super.json
>    <https://github.com/ethereum-lists/chains/pull/2528/files#diff-92083cb7884062848350989ea1c2c45993bbb5ebb25b473aa7f539426a77d500>
>    (8)
>    - *A*
>    _data/iconsDownload/QmW4C4QHLMhLeH5MsdVbauMc2Skb4ehzLKU3egLKKoux4D
>    <https://github.com/ethereum-lists/chains/pull/2528/files#diff-c52b7f8e1712d9365417b60c94f60ece3cdfbd2e1e9b726a7c986273d2b597ef>
>    (0)
>
> Patch Links:
>
>    - https://github.com/ethereum-lists/chains/pull/2528.patch
>    - https://github.com/ethereum-lists/chains/pull/2528.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/2528>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6QX6LA44YFG6IVAME3T743W6MI4BANCNFSM6AAAAAAWK2M3FU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-03-28 23:19 UTC, ligi requested changes

2023-03-28 23:19 UTC, ligi commented on _data/chains/eip155-1970.json
> +      "standard": "EIP3091"
this does not look like a block explorer & not EIP3091 compatible.

2023-03-29 09:09 UTC, ligi requested changes
you did not address my comment at all

2023-03-29 09:37 UTC, superexchain commented
> 4587de5

sorry, i forgot update explorer url

2023-03-29 12:54 UTC, merged