Add GeneChain mainnet
ethereum-lists/chains pull request #260
Opened 2021-05-17 12:57 UTC by genechain-dev

GeneChain mainnet is now ready for launching. The genesis block has been set to 2021/5/18 4:00 UTC.
Explorer is ensured the same version as our testnet. So it's EIP3091. Because the genesis block is in the future, only block 0 can be found on the scan right at the moment.
Thanks for reviewing our pull request!

2021-05-17 21:19 UTC, ligi requested changes
The faucets field is required but can be an empty array

2021-05-18 02:06 UTC, genechain-dev commented
> The faucets field is required but can be an empty array

Fixed. Please have a review.
Sorry for the inconvenience.

2021-05-18 04:58 UTC, ligi requested changes
Thanks - but the CI is not yet happy. The ShortName must be unique - this is important for TREZOR.

```
Exception in thread "main" org.ethereum.lists.chains.model.ShortNameMustBeUnique: short name must be unique - but found `GeneChain` more than once
        at org.ethereum.lists.chains.MainKt.parseWithMoshi(Main.kt:181)
        at org.ethereum.lists.chains.MainKt.checkChain(Main.kt:76)
        at org.ethereum.lists.chains.MainKt.main(Main.kt:21)

```

2021-05-18 07:56 UTC, genechain-dev commented
The short name of our testnet has been changed. Hopes this will work. Thanks!

2021-05-18 08:01 UTC, ligi commented
you changed the chain field - not the shortName field

2021-05-18 08:24 UTC, genechain-dev commented
Ops, sorry for the mistake.

2021-05-18 08:27 UTC, ligi approved these changes

2021-05-18 08:27 UTC, merged