Create eip155-330844.json
ethereum-lists/chains pull request #2630
Opened 2023-04-12 19:50 UTC by Tayfuntaner

TTcoin Smart Chain Explorer

2023-04-14 19:53 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-04-18 14:19 UTC, ligi approved these changes

2023-04-18 14:19 UTC, merged

2023-05-20 17:07 UTC, Wisanu19covit commented
🤘

2023-11-02 09:36 UTC, Tayfuntaner commented
https://chainlist.wtf/ Hello, it does not appear on the website.