Added the router chain test for cross chain communication
ethereum-lists/chains pull request #2773
Opened 2023-05-08 07:38 UTC by hydrogenbond007

if you wanna check out more https://devnet-docs.routerprotocol.com/overview

2023-05-08 07:57 UTC, ligi requested changes

2023-07-02 10:13 UTC, alokeutpal approved these changes
Y/l

2023-08-19 16:33 UTC, hydrogenbond007 commented
Just keeping it alive

2023-08-19 16:55 UTC, ligi commented
https://aplha-explorer-ui.routerprotocol.com is not reachable

2023-08-20 04:45 UTC, hydrogenbond007 commented
> https://aplha-explorer-ui.routerprotocol.com is not reachable

Sorry it was a typo, fixed it

2023-08-31 15:47 UTC, hydrogenbond007 commented
@ligi ready to merge!

2023-09-04 02:06 UTC, ligi requested changes

2023-09-04 02:06 UTC, ligi commented on _data/chains/eip155-101010
> +      "standard": "EIP3091"
Does not seem to be EIP3091 compatible
```suggestion
      "standard": "none"
```

2023-10-26 01:46 UTC, closed without merging