Adding AxelChain (Mainnet, Pre-Prod, and Dev-net)
ethereum-lists/chains pull request #2890
Opened 2023-05-24 10:26 UTC by axelnetwork

2023-05-24 10:48 UTC, eltonliyongdong approved these changes

2023-05-26 07:35 UTC, ligi requested changes
explorer cannot be reached

2023-05-29 09:25 UTC, axelnetwork reviewed
Adding AxelChain Dev-Net

2023-05-29 14:47 UTC, ligi approved these changes

2023-05-29 14:47 UTC, merged