Added Avocado
ethereum-lists/chains pull request #3018
Opened 2023-06-15 19:13 UTC by ishanjain28

Hey, This PR is for adding Instadapp's Avocado product on this list.

* https://avocado.instadapp.io
* https://instadapp.io

2023-06-16 02:03 UTC, ligi approved these changes

2023-06-16 02:03 UTC, ligi commented on _data/chains/eip155-634.json
> +      "url": "https://avoscan.co/",
```suggestion
      "url": "https://avoscan.co",
```

2023-06-16 02:05 UTC, ligi requested changes

2023-06-16 02:05 UTC, ligi commented on _data/chains/eip155-634.json
> +      "standard": "EIP3091"
explorer does not seem to be EIP3091 compatible 
```suggestion
      "standard": "none"
```

2023-06-19 04:36 UTC, ishanjain28 commented
Hey, There was an issue with the IPFS node and it has been fixed. Please re-run the pipeline and it should be able to fetch the assets now.

2023-06-21 18:56 UTC, ishanjain28 commented
Hey @ligi Please review this again

2023-06-27 21:29 UTC, ishanjain28 commented
Hi @ligi, I hope you are doing well. I have rebased the PR on latest head in `master`.

Please review this PR and approve gh action runs.

2023-06-28 20:04 UTC, ishanjain28 commented
Hi, Thank you for re-running gh actions for this PR and I am sorry about this failing again. 

I didn't realize ipfs had bit of a problem related to memory consumption and it was repeatedly getting killed by oomkiller. I have worked around that problem and it should stay online from now on. Please re-run the pipeline, Thank you!

2023-07-02 10:21 UTC, alokeutpal approved these changes

2023-07-06 18:49 UTC, merged