Add ArbRinkeby
ethereum-lists/chains pull request #307
Opened 2021-06-21 09:27 UTC by FabijanC

2021-06-21 10:36 UTC, ligi requested changes
I think the currency should be Arbitrum Rinkeby Ether (ARETH)

2021-06-21 11:43 UTC, ligi approved these changes

2021-06-21 11:43 UTC, merged

2022-08-04 10:20 UTC, vmichalik commented
@ligi it doesn't seem like the Arbitrum team are in alignment over this naming for the native currency, see their documentation [here](https://developer.offchainlabs.com/docs/public_chains)

![image](https://user-images.githubusercontent.com/12459761/182824060-29923044-55e8-4d68-8bcd-0fb9ee67a2e8.png)

I'll make a PR to change it to RinkebyETH

2022-08-04 10:24 UTC, ligi commented
Dam - I actually think this is worse - but if it's the official one - yea. Naming is hard.