Add linea mainnet
ethereum-lists/chains pull request #3093
Opened 2023-06-30 10:02 UTC by Akaryatrh

Hi! Following the PRs opened for Linea testnet a few weeks and months ago, we now would like to add support for **Linea mainnet**.
Please keep in mind that RPC endpoints, bridge and block explorer will be available in the upcoming weeks (hence the draft status).

Many thanks for support 🙂

2023-06-30 13:41 UTC, Khunyurry approved these changes

2023-07-02 10:24 UTC, alokeutpal approved these changes

2023-07-04 06:44 UTC, Akaryatrh commented on _data/chains/eip155-59144.json
> +    "https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}",
I'm not sure to understand your question? What issue are you highlighting?

2023-07-04 13:05 UTC, Akaryatrh commented
Side question @ligi, would you be ok if `ethereum-lists` was listed as part of Linea's ecosystem on [linea.build](https://linea.build/) website? If so, would you have a logotype to provide?

(Or maybe it's just the one below? )
<img src="https://github.com/ethereum-lists/chains/assets/574787/60a0efab-2757-4991-87f0-7f8f68485efa" width="50" />

2023-07-05 17:27 UTC, ligi requested changes
https://lineascan.build is not reachable

2023-07-05 17:27 UTC, ligi commented
sure you can list it - and yeah this is the only logo we have

2023-07-05 19:15 UTC, alokeutpal approved these changes

2023-07-05 21:48 UTC, Akaryatrh commented
> https://lineascan.build is not reachable
Yep, as said in the PR description, for now neither the RPC endpoints, the bridge or even the block explorer are available. But it's coming soon 🙂

2023-07-12 09:14 UTC, Akaryatrh commented
**Update:** changed information for explorers for both testnet and mainnet

2023-07-18 10:35 UTC, Akaryatrh commented
FYI @ligi explorer https://lineascan.build and bridge https://bridge.linea.build are now available 🙂 
I then mark this PR as ready.

2023-07-22 15:03 UTC, ligi approved these changes

2023-07-22 15:07 UTC, merged

2026-01-18 16:43 UTC, Alamznetwork commented
how do I commit please