Add Sepolia Public Goods Network
ethereum-lists/chains pull request #3139
Opened 2023-07-10 14:25 UTC by wbt

2023-07-10 16:42 UTC, wbt commented
I see that validate_formatting failed, but can't tell why it failed or how to fix it.

2023-07-10 17:46 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-07-11 20:26 UTC, wbt commented
Done, but that requirement is quite unintuitive, especially when it requires correction to a whitespace pattern directly copied from the readme for this repo (example around bridges where linking to a parent).  
Prettier also changed every single JSON file under _data, apparently a line-ending difference which VSCode doesn't visualize as a diff. I didn't commit all of them.

2023-07-11 20:45 UTC, ligi approved these changes

2023-07-11 20:46 UTC, merged