Add toronet
ethereum-lists/chains pull request #3145
Opened 2023-07-10 19:53 UTC by enoch-aik

2023-07-11 13:31 UTC, enoch-aik commented
Hi @ligi 
Can you please help?  
validate_json workflow seems to be failing and I don't know why

2023-07-11 14:21 UTC, enoch-aik commented
Yes, I have done that in my last commit

2023-07-12 15:28 UTC, ligi requested changes

2023-07-14 06:44 UTC, enoch-aik commented
@ligi Can you please review this PR again?

The last change for the explorer standard that you requested has been resolved

2023-07-14 10:04 UTC, alirezaayande92 approved these changes

2023-07-14 21:40 UTC, ligi approved these changes

2023-07-14 21:40 UTC, merged