Add chain-id for REAP
ethereum-lists/chains pull request #3181
Opened 2023-07-17 10:46 UTC by helloreap

Main-net: 221230
Test-net: 221231

2023-07-17 17:22 UTC, julioAk47 approved these changes

2023-07-17 18:32 UTC, minimayki6232 approved these changes

2023-07-22 13:32 UTC, ligi requested changes
short name must be unique - but found `REAP` more than once

2023-07-26 09:24 UTC, ligi approved these changes

2023-07-26 09:24 UTC, merged