Script Network RPC Setup
ethereum-lists/chains pull request #3188
Opened 2023-07-18 10:57 UTC by dheeraj2414

Script Network RPC Setup

2023-07-18 14:35 UTC, ligi requested changes
not compatible with the EIP

2023-07-19 05:44 UTC, dheeraj2414 commented on _data/chains/eip155-742.json
> +    "standard": "EIP3091"
Recommended changes has been done standard replace with none

2023-07-19 13:40 UTC, dheeraj2414 commented on _data/chains/eip155-742.json
> +    "standard": "EIP3091"
Hi @ligi , may i know what the reason behind fail this action (https://github.com/ethereum-lists/chains/actions/runs/5595477102/jobs/10239894257). I have added json object according to example. Please let me know. Thanks 
![Screenshot from 2023-07-19 19-09-56](https://github.com/ethereum-lists/chains/assets/103170259/589d4f22-b4a8-47ab-a697-f723a21e59e4)

2023-07-21 05:40 UTC, surgarshorts commented
Sorry reviewing hyperlinks to learn and understand

2023-07-21 13:51 UTC, ligi commented
diff is empty - closing

2023-07-21 13:51 UTC, closed without merging