Add Ronin network
ethereum-lists/chains pull request #3219
Opened 2023-07-24 16:39 UTC by quybeans

Ronin is an EVM blockchain designed specifically for game developers. The Ronin blockchain and ecosystem is under actively development by Sky Mavis, the team behind Axie Infinity.

We aware that Ronin's chain ID 2020 has collision with Public Mint. Public Mint is undergoing scaling back and maintenance on a recent [Discord announcement](https://discord.com/channels/973622565111201853/977264189674508298/1123257278783553628).

As Ronin is onboarding more dApps to its ecosystem, we are looking to settle this collision with Public Mint team and this repo maintainer.

2023-07-24 19:37 UTC, ligi requested changes
their chain is still active - so I will not merge this unless they make a public (not some discord) announcement that they abandon this chain

2023-12-09 11:47 UTC, glitch-txs commented
Hi @ligi ! Could we consider reopening this PR? Public Mint has been inactive for several months now, while Ronin has been growing and active.
 They have also been very responsive to the Ethereum protocols, the main wallet supports [EIP-6963](https://github.com/WalletConnect/EIP6963/blob/dd30b7cb95888cdda808e5b9c47d69020b47aebe/src/utils/constants.ts#L79) and CAIP-25. They are also registered in [Viem's repo](https://github.com/wevm/viem/blob/main/src/chains/definitions/ronin.ts) and [WalletConnect explorer chain registry](https://docs.walletconnect.com/advanced/multichain/chain-list).
 We noticed there were a chain mismatch due to this conflict as we use this chain registry for the EIP6963 website. Thanks!

2023-12-09 11:52 UTC, ligi commented
the other chain is still producing blocks

2024-06-03 01:57 UTC, glitch-txs commented
Hey @ligi could you reopen? Seems like the blockchain stopped working [6 months ago](https://explorer.publicmint.io/)

2024-08-06 17:52 UTC, dwi commented
Hello @ligi, the Public Mint network is not producing blocks for 8 months now. Last tweet was 17 months ago. It seems to me that the chain is now abandoned and no longer active.

2024-08-22 21:00 UTC, ligi commented
@zaidhub @rafaeltorres77 can you please chime in here?
@dwi this PR will then for sure need the redFlag reusedChainId

2024-09-04 10:48 UTC, justinabsentia commented
Bump

2024-09-05 04:07 UTC, quybeans commented
Red flag is added.

2024-10-20 16:54 UTC, glitch-txs commented
Bump

2024-11-19 00:34 UTC, YaroShkvorets commented
Bump

2024-11-19 13:40 UTC, glitch-txs commented
can we merge? @ligi 👍

2025-01-22 08:06 UTC, dwi commented
@ligi Can we please merge this?

2025-01-28 04:00 UTC, viko42 commented
Why is that not validated yet?

2025-01-28 04:37 UTC, Rias0232022 commented
Ok

2025-01-28 10:58 UTC, maxshedra commented
Can this be merged?

2025-01-28 11:26 UTC, ligi commented
CI is red: so no merge 
the other chain does not seem to be a blocker anymore - but the CI is

2025-01-28 11:27 UTC, Rias0232022 commented
Ok

2025-01-28 11:49 UTC, ligi commented
the red CI is fixed now - but the PR needs redFlags reusedChainId

2025-01-28 11:51 UTC, dwi commented on _data/chains/eip155-2020.json
> +  "redFlags": ["reusedChainId"],
@ligi it has the red flag

2025-01-28 11:52 UTC, ligi approved these changes

2025-01-28 11:52 UTC, merged