Update eip155-81.json with Japan Open Chain Mainnet
ethereum-lists/chains pull request #3222
Opened 2023-07-25 01:43 UTC by cuonghx1108

Hello ,

The current older test network "Zenith Testnet (Vilnius)" that is currently associated with chainId 81 is no longer active anymore.
- https://chainlist.org/chain/81

The website links associated with it are non-functional and the project seems to be inactive.
- https://www.zenithchain.co/
- https://docs.zenithchain.co/add-to-metamask/testnet

I propose updating the listing to represent the "Japan Open Chain Mainnet," an active network utilizing the same chainId 81.

Here is the relevant information:

Japan Open Chain Mainnet
Website: https://www.japanopenchain.org/en/docs/developer/dev-on-ethereum

2023-07-25 01:46 UTC, cuonghx1108 commented
# Recheck IPFS file available
![image](https://github.com/ethereum-lists/chains/assets/100658449/b6c63bee-7e7b-47f4-920b-61d241e9cfd9)

# PR verification
![image](https://github.com/ethereum-lists/chains/assets/100658449/6983f299-a229-4acd-aa85-f03b81787782)

2023-07-25 08:52 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-07-26 01:12 UTC, cuonghx1108 commented
I updated it, Thank for reviewing

2023-07-26 10:30 UTC, ligi approved these changes

2023-07-26 10:30 UTC, merged