Add STN network
ethereum-lists/chains pull request #3224
Opened 2023-07-25 05:40 UTC by Agentspades

2023-07-25 08:51 UTC, ligi requested changes
fix CI errors like this one: explorer standard must be 'none' or 'EIP3091'

2023-07-25 10:42 UTC, Agentspades commented
Cheers for the review i have added the missing explorers section and can confirm gradle builds successfully and the logo is accessible on ipfs

2023-07-26 09:11 UTC, ligi approved these changes

2023-07-26 09:11 UTC, merged

2023-08-07 05:34 UTC, jnut321 reviewed
_new. Interface-ownership
- [x] Learningkutgw!_