Add KalarChain
ethereum-lists/chains pull request #3238
Opened 2023-07-27 04:17 UTC by KalarChain

Thanks for your support

2023-07-27 13:26 UTC, ligi requested changes

2023-07-27 13:26 UTC, ligi commented on _data/chains/eip155-1379.json
> +    "url": "https://explorer.kalarchain.tech/",
```suggestion
    "url": "https://explorer.kalarchain.tech",
```

2023-07-27 13:29 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-07-28 18:09 UTC, ligi requested changes
I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

2023-07-31 01:00 UTC, KalarChain commented
Im so sorry to have wasted your precious time, I will fix it soon and be
more careful. Thank you very much.

Regards

Vào 01:09 AM, T.7, 29 Th7, 2023 ligi ***@***.***> đã viết:

> ***@***.**** requested changes on this pull request.
>
> I could not resolve your CID with ipfs get in a reasonable time - and
> before having a back and forth here I require you to put it in
> iconDownload. Before this back and forth did cost me a lot of time that I
> do not have.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/3238#pullrequestreview-1552680404>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBRAV46AKQGOWR76TEAWTATXSP55JANCNFSM6AAAAAA2ZPROZE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-31 01:28 UTC, KalarChain commented
> 

Hi Ligi, i checked the IPFS address in both on cloudflare and found it working fine. This error can also occur when the connection to cloudflare is unstable. You can do a quick check here:
For KalarChain icon

- https://cloudflare-ipfs.com/ipfs/bafkreihfoy2kgf2rebaoicso7z5h7ju46z6gtr64mskkths3qbfkrtnkjm

For KalarScan icon

- https://cloudflare-ipfs.com/ipfs/bafkreidbzzv3lrwlzquhlpl4jcmr54sifhi5ufoek6olb5kjh3h3kvktdq

2023-07-31 08:16 UTC, ligi approved these changes

2023-07-31 08:16 UTC, merged