Adding the Obscuro testnet
ethereum-lists/chains pull request #3240
Opened 2023-07-27 10:27 UTC by CaisManai

Adding the Obscuro testnet running as an L2 on Sepolia

2023-07-27 11:07 UTC, ligi requested changes

2023-07-27 11:07 UTC, ligi commented on _data/chains/eip155-443.json
> +      "url": "https://testnet.obscuroscan.io/",
```suggestion
      "url": "https://testnet.obscuroscan.io",
```

2023-07-27 12:56 UTC, ligi requested changes
https://testnet.obscuroscan.io is down

2023-07-27 16:34 UTC, CaisManai commented
> https://testnet.obscuroscan.io is down

apologies @ligi 🙏 it's up now

2023-07-27 19:34 UTC, ligi requested changes
explorer seems EIP3091 incompatible

2023-07-27 19:34 UTC, ligi commented on _data/chains/eip155-443.json
> +      "standard": "EIP3091"
```suggestion
      "standard": "none"
```

2023-07-28 18:12 UTC, CaisManai commented
> explorer seems EIP3091 incompatible

Apologies for this @ligi. Also, our bridge is still not fully up but isn't required for testnet. Should I remove this from the PR or can I keep it in for now?

2023-07-28 18:16 UTC, merged