add yooldo verse mainnet
ethereum-lists/chains pull request #3309
Opened 2023-08-10 07:33 UTC by web3isthefuture

2023-08-17 16:26 UTC, CryptoSubin commented
Hello @ligi 🥰

Could you please provide information about the reasons for the failed build? 
Is there any issue with the file we submitted the merge request for?

2023-08-18 13:30 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-08-18 13:30 UTC, ligi commented on _data/chains/eip155-345.json
> +      "url": "https://explorer.yooldo-verse.xyz/",
```suggestion
      "url": "https://explorer.yooldo-verse.xyz",
```

2023-08-18 13:50 UTC, ligi approved these changes

2023-08-18 13:50 UTC, merged