upgrade base rpc
ethereum-lists/chains pull request #3313
Opened 2023-08-10 19:35 UTC by angel-ding-cb

Added developer access rpc to base mainnet

2023-08-10 19:40 UTC, anikaraghu commented on _data/chains/eip155-8453.json
> +  "rpc": ["https://mainnet.base.org/", "https://developer-access-mainnet.base.org"],
nit: multiple lines and I think we need a slash at the end 
```suggestion
  "rpc": [
      "https://mainnet.base.org/",
       "https://developer-access-mainnet.base.org/"
    ],
```

2023-08-10 19:46 UTC, angel-ding-cb commented
related PR: https://github.com/ethereum-lists/chains/pull/3247

2023-08-10 19:48 UTC, anikaraghu approved these changes

2023-08-10 19:55 UTC, aflock commented on _data/chains/eip155-8453.json
> +       "https://developer-access-mainnet.base.org/"
small whitespace inconsistency?

2023-08-11 04:20 UTC, Loloo651 approved these changes

2023-08-11 08:59 UTC, ligi commented
@wbnns can you comment on this? Was removed in your PR

2023-08-11 16:37 UTC, wbnns commented
@ligi 

Looks good, thanks! The reason we are adding this back is because it caused a downstream issue with a provider.

2023-08-14 15:38 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-08-16 14:41 UTC, ligi approved these changes

2023-08-16 14:41 UTC, merged