Add Rethereum Mainnet
ethereum-lists/chains pull request #3326
Opened 2023-08-14 05:22 UTC by JABirchall

- Create eip155-622277.json

2023-08-17 22:13 UTC, Memorti commented
Hello

2023-08-31 14:39 UTC, Akaslove99 commented on _data/icons/rethereum.json
#

2023-08-31 14:50 UTC, Akaslove99 approved these changes

2023-08-31 14:57 UTC, JABirchall commented
This is now ready for merge.

2023-09-01 16:51 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-09-01 16:51 UTC, ligi commented on _data/chains/eip155-622277.json
> +    "url": "https://explorer.rethereum.org/",
```suggestion
    "url": "https://explorer.rethereum.org",
```

2023-09-01 17:13 UTC, JABirchall commented
Ran prettier and commited changes.

2023-09-01 17:38 UTC, ligi approved these changes

2023-09-01 17:38 UTC, merged

2023-09-02 09:59 UTC, Ayid7676 commented
0xFbB638237383ac291251cea4974d8f60642e8A49