Add chain ID for the cheapETH blockchain
ethereum-lists/chains pull request #335
Opened 2021-07-14 05:31 UTC by geohot

cheapETH is alive and well and using chain ID 777!

Learn more at https://cheapeth.org, perhaps more legit than the Ethermint Testnet?

2021-07-14 05:38 UTC, ligi commented
In a case of a collision the oldest chain wins and it seems yours is younger

2021-07-14 05:46 UTC, ligi commented
OK - just wanted to check the timestamps of the genesis block - and it seems their RPC is down - so there is a chance actually ;-)

2021-07-15 09:26 UTC, fedekunze requested changes
We will still use 777 for our testnet chain-id, we stopped it because we were doing breaking changes and also because the maintainers of the project changed. We will relaunch the testnet in a few weeks

2021-07-15 09:28 UTC, ligi commented
Thanks for the information! Will 'relaunch' mean a new genesis?

2021-07-16 15:54 UTC, merged

2021-07-16 15:55 UTC, ligi commented
OK merged this now as the  Ethermint Testnet is inactive. Once it comes back (with the same genesis) - I might revert. But for users I think this is the best way now.

2021-07-16 19:02 UTC, geohot commented
Thanks!