Add BLXq Testnet
ethereum-lists/chains pull request #3419
Opened 2023-08-31 10:52 UTC by BLXDev20

Add BLXq Testnet

2023-09-01 16:50 UTC, ligi requested changes
explorer seems incompatible

2023-09-02 03:24 UTC, surgarshorts commented on _data/chains/eip155-1107.json
> +      "standard": "EIP3091"
Am I suppose to change this? I'm still learning my way, I get confused & don't understand everything.

2023-09-02 14:04 UTC, BLXDev20 commented
Hi @ligi can you look at this. my icon is valid:

https://explore.ipld.io/#/explore/QmS9kDKr1rgcz5W55yCQVfFs1vRTCneaLHt1t9cBizpqpH

Thanks

2023-09-03 11:29 UTC, ligi approved these changes

2023-09-03 11:29 UTC, merged

2023-09-20 22:14 UTC, jonesk7734 approved these changes
Ok