Add Synapse Sepolia Testnet in place of deprecated chain
ethereum-lists/chains pull request #3492
Opened 2023-09-11 20:50 UTC by aureliusbtc

In #3463, the testnet that is now down which was using chain ID 444 is now deprecated. 

Please let me know if this correctly adds new chain information in place of a deprecated chain, I could not find an example prior, except in the readme which mentions: "The only way to get a chain reassigned is when the old chain gets deprecated. This can e.g. be used for testnets that are short-lived."

2023-09-11 21:09 UTC, ligi requested changes
you need to add `"redFlags": ["reusedChainId"]`

2023-09-11 22:21 UTC, aureliusbtc commented
Updated @ligi

2023-09-12 10:35 UTC, jonesk7734 approved these changes
😀

2023-09-12 17:44 UTC, ligi approved these changes

2023-09-12 17:44 UTC, merged