Update explorer link for Celo Testnet Alfajores
ethereum-lists/chains pull request #3518
Opened 2023-09-17 08:42 UTC by rayedsikder

Updated the Celo Mainnet explorer link with Celo Testnet Alfajores explorer link.

2023-09-17 09:00 UTC, ligi requested changes
are both just pointing to the same instance - or should both be kept for redundancy?

2023-09-17 09:27 UTC, dazimmie57 commented
Redundant. Thank u.


On Sun, Sep 17, 2023, 3:21 AM rayedsikder ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In _data/chains/eip155-44787.json
> <https://github.com/ethereum-lists/chains/pull/3518#discussion_r1328068075>
> :
>
> > @@ -20,8 +20,8 @@
>    "infoURL": "https://docs.celo.org/",
>    "explorers": [
>      {
> -      "name": "Celoscan",
> -      "url": "https://celoscan.io",
> +      "name": "Alfajoresscan",
> +      "url": "https://alfajores.celoscan.io/",
>
> The previous link was pointing to Celo Mainnet (ChainID: 42220), the
> updated link points to the Celo Testnet explorer Alfajores (ChainID: 44787)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/3518#discussion_r1328068075>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA5LV5WCZ2LKKUCZYXVBFGDX226IFANCNFSM6AAAAAA43PBT7M>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-09-19 09:18 UTC, ligi approved these changes

2023-09-19 09:18 UTC, merged

2023-09-20 11:52 UTC, jonesk7734 approved these changes
Ok