Add Fuse Explorer information
ethereum-lists/chains pull request #355
Opened 2021-07-29 10:42 UTC by benjlevesque

The wrong Explorer URL is used on https://chainlist.org/

2021-07-29 11:27 UTC, ligi requested changes
EIP3091 is not respected - e.g. see: https://explorer.fuse.io/block/12218333

2021-07-29 15:42 UTC, benjlevesque commented
Good catch @ligi, I totally missed that. 
I submitted an issue to the blockscout repo: https://github.com/blockscout/blockscout/issues/4455

Feel free to close this PR as it might take a while to be available

2021-07-29 16:31 UTC, ligi commented
cool - feel free to keep it open! Yea - it's the best to fix it in BlockScout - most people currently work around it with redirects - but it is best to fix it in the root!

2021-12-14 16:01 UTC, benjlevesque commented
Hey @ligi, Fuse upgraded Blockscout and the link is now working :)

2021-12-14 16:12 UTC, Tody11 commented
Uhh

2022-03-23 02:04 UTC, closed without merging