add btc20 network config
ethereum-lists/chains pull request #3564
Opened 2023-09-23 06:11 UTC by fuhongxuelook

2023-09-23 15:56 UTC, ligi requested changes

2023-09-23 15:56 UTC, ligi commented on _data/chains/eip155-963.json
> +      "url": "https://scan.bitcoincode.technology/",
```suggestion
      "url": "https://scan.bitcoincode.technology",
```

2023-09-25 20:15 UTC, Bvincent11 commented
FundTrasfer.sol

2023-09-25 20:16 UTC, Bvincent11 commented
Funds.sol

2023-09-27 15:01 UTC, closed without merging