add bnbchain icon for opBNB
ethereum-lists/chains pull request #3626
Opened 2023-10-03 16:07 UTC by huihzhao

2023-10-10 05:00 UTC, blackdoc111 approved these changes

2023-10-10 12:35 UTC, huihzhao commented
@blackdoc111 if you could help me to identify the problem, it would be great.

2023-10-10 14:02 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

2023-10-13 07:24 UTC, huihzhao commented
Could you help review the latest commits? thanks

2023-10-15 18:10 UTC, huihzhao commented
> The file you put in iconDownload ends with .png - this is no valid CID

sorry, have corrected the file name

2023-10-15 18:11 UTC, huihzhao commented on _data/iconsDownload/bafybeib75gwytvblyvjpfminitr3i6mpat3a624udfsqsl5nysf5vuuvie
renamed the file

2023-10-18 07:12 UTC, huihzhao reviewed
updated the icon file

2023-10-19 13:39 UTC, ligi approved these changes

2023-10-19 13:39 UTC, merged