Remove staled enpoints for the Crab chain
ethereum-lists/chains pull request #3653
Opened 2023-10-10 05:41 UTC by boundless-forest

2023-10-10 13:49 UTC, ligi requested changes
what do you mean with staled?

```
curl https://crab.api.onfinality.io/public-ws   -X POST   -H "Content-Type: application/json"   --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}' ; curl https://crab-rpc.darwiniacommunitydao.xyz   -X POST   -H "Content-Type: application/json"   --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","result":"0x167cfa","id":1}{"jsonrpc":"2.0","result":"0x167cfa","id":1}
```

2023-10-10 20:50 UTC, ninooo123 approved these changes

2023-10-11 03:15 UTC, boundless-forest commented
> what do you mean with staled?

Sorry for the lack of information on this. We have decided to suspend the RPC service in the onfinality in this week, the endpoints will no longer be available in today or tomorrow, so I raised this pr.

2023-10-13 04:22 UTC, ninooo123 approved these changes

2023-10-13 11:58 UTC, ninooo123 approved these changes

2023-10-13 12:09 UTC, merged