VinuChain
ethereum-lists/chains pull request #3682
Opened 2023-10-16 11:35 UTC by ur-os

2023-10-17 05:31 UTC, Amazinggrace07 approved these changes

2023-10-18 23:09 UTC, ligi requested changes

2023-10-18 23:09 UTC, ligi commented on _data/chains/eip155-207.json
> +      "standard": "EIP3091"
does not seem to be compatible

```suggestion
      "standard": "none"
```

2023-10-20 20:55 UTC, ligi approved these changes

2023-10-20 20:55 UTC, merged