add iotex explorer info
ethereum-lists/chains pull request #369
Opened 2021-08-12 01:40 UTC by ququzone

2021-08-12 02:32 UTC, ligi requested changes
the "standard" field must be present

2021-08-12 02:32 UTC, ligi commented on _data/chains/eip155-4689.json
> +    "name": "iotexscan",
```suggestion
    "name": "iotexscan",
    "standard": "EIP3091",
```

2021-08-12 02:32 UTC, ligi commented on _data/chains/eip155-4690.json
> +    "name": "testnet iotexscan",
```suggestion
    "name": "testnet iotexscan",
    "standard": "EIP3091",
```

2021-08-29 09:31 UTC, ququzone commented on _data/chains/eip155-4689.json
> +    "name": "iotexscan",
Thanks, iotexscan now support EIP3091

2021-08-29 16:45 UTC, ligi approved these changes

2021-08-29 16:56 UTC, merged