updated elysium mainnet and testnet metadata
ethereum-lists/chains pull request #3692
Opened 2023-10-17 08:27 UTC by farazahmadvaival

updated elysium mainnet and atlantis testnet metadata

2023-11-01 19:41 UTC, Aholaone360 requested changes
Fix

2024-01-28 14:43 UTC, melissamforbs approved these changes

2024-01-28 14:43 UTC, melissamforbs approved these changes

2024-01-28 14:43 UTC, melissamforbs approved these changes

2024-01-28 14:44 UTC, melissamforbs approved these changes

2024-03-21 05:34 UTC, closed without merging