Master
ethereum-lists/chains pull request #3694
Opened 2023-10-17 16:45 UTC by CryptoDeveloper87

add BlocX Network

2023-10-18 03:18 UTC, z3r086 commented
> add BlocX Network

2023-10-19 07:32 UTC, CryptoDeveloper87 reviewed
Update BlocX Network

2023-10-19 13:35 UTC, Akaslove99 approved these changes

2023-10-20 17:23 UTC, CryptoDeveloper87 commented
Why does the build keep failing.. even with out my update..

2023-10-20 20:49 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-10-21 04:22 UTC, CryptoDeveloper87 reviewed
Update BlocX Network

2023-10-21 11:52 UTC, CryptoDeveloper87 commented
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

I have done this , Thank you

2023-11-20 05:47 UTC, ligi requested changes
Do not checkin any vscode stuff

I could not resolve your CID with `ipfs get` in a reasonable time - and before having a back and forth here I require you to put it in iconDownload. Before this back and forth did cost me a lot of time that I do not have.

2023-11-20 05:47 UTC, ligi commented on _data/chains/eip155-879151.json
> +      "url": "https://explorer.blxscan.com/",
```suggestion
      "url": "https://explorer.blxscan.com",
```

2024-01-09 01:46 UTC, closed without merging