Add Liquichain
ethereum-lists/chains pull request #3748
Opened 2023-10-30 02:11 UTC by smichea

replace deprecated chain by liquichain

2023-10-30 03:39 UTC, ligi requested changes
you need to add redFlags reusedChainId

2023-11-15 10:46 UTC, smichea commented
@ligi should i do something else ? thank you

2023-11-18 08:44 UTC, ligi requested changes
The explorer must be an object - please see the other chains.

Also: Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-11-19 02:53 UTC, smichea commented
sorry for that @ligi , hope all is fine now

2023-11-19 05:45 UTC, ligi requested changes

2023-11-19 05:45 UTC, ligi commented on _data/chains/eip155-1662.json
> +      "url": "https://mainnet.liquichain.io/",
```suggestion
      "url": "https://mainnet.liquichain.io",
```

2023-11-27 08:45 UTC, ligi approved these changes

2023-11-27 08:45 UTC, merged