Add HYTOPIA Mainnet & HYTOPIA Testnet
ethereum-lists/chains pull request #3769
Opened 2023-11-01 19:22 UTC by iamarkdev

2023-11-18 17:35 UTC, macvts requested changes
ChainID need to be state differently, won't do for the same chainid (2911) to both mainnet and testnet

2023-11-19 17:37 UTC, iamarkdev commented
> ChainID need to be state differently, won't do for the same chainid (2911) to both mainnet and testnet

Ahh, apologies @macvts - resolved.

2023-11-22 15:08 UTC, macvts approved these changes

2023-11-30 18:09 UTC, macvts requested changes

2023-11-30 18:09 UTC, macvts commented on _data/icons/hytopia.json
> +    "format": "png"
Format is wrong, cause failure to pr merging

2024-01-19 01:46 UTC, closed without merging