Add the Redstone Holesky network (ID 17001)
ethereum-lists/chains pull request #3804
Opened 2023-11-13 23:41 UTC by qbzzt

Also the redstone.png icon (ipfs://bafkreieyaqgkgntvxuo5tnhgseladga5q6gutc37dab7kqqfdguhq7vkxq)

2023-11-18 15:21 UTC, macvts reviewed
just a little comment on infoURL, existing URL didn't work or is it going to be up-coming for the redstone holesky's landing page?

2023-11-18 15:21 UTC, macvts commented on _data/chains/eip155-17001.json
didn't seem to access through the current infoURL
should you adjust the infoURL into "https://redstone.xyz/" ?

2023-11-18 15:35 UTC, qbzzt commented on _data/chains/eip155-17001.json
Oops, sorry. I thought it will be there, but it ended up as https://redstone.xyz/docs/network-info. I updated the PR.

2023-11-18 17:07 UTC, macvts approved these changes

2023-11-27 15:42 UTC, macvts approved these changes

2023-11-27 15:44 UTC, macvts commented
@ligi he's probably fixed all the issue, assuming that this pr need your approval one last time to merge

2023-11-27 18:27 UTC, ligi commented
formatting is not fixed - still red

2023-11-28 00:29 UTC, qbzzt commented
> formatting is not fixed - still red

I have no idea why, it's valid JSON. I removed the name of the native currency, but I'm not able to rerun the verifier on my own.

2023-11-28 02:57 UTC, macvts approved these changes

2023-11-28 14:10 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-11-28 14:37 UTC, qbzzt commented
> Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json) e.g. run `npx prettier --write _data/*/*.json`

Done

2023-11-28 14:41 UTC, macvts approved these changes

2023-11-28 14:46 UTC, ligi approved these changes

2023-11-28 14:46 UTC, merged