SKALE Network chain hubs fixes and addition of new SKALE Titan Hub (Mainnet and Testnet)
ethereum-lists/chains pull request #3834
Opened 2023-11-22 16:30 UTC by manuelbarbas

## SKALE Network Hubs

The SKALE Network is a EVM compatible multichain model where exist 4 main hubs. Each one of these hubs their own Mainnet and Testnet chains.
It were made two types of changes: some hubs were created a metadata file from scratch and others the metadata was update to a more accurate version.
Existing SKALE Hubs on chains list:

- **SKALE Nebula Hub** (Mainnet and Testnet) -> Metadata modified
- **SKALE Europa Hub** (Mainnet and Testnet) -> Metadata modified
- **SKALE Calypso Hub** (Mainnet and Testnet) -> Metadata modified
- **SKALE Titan Hub** (Mainnet and Testnet) -> New Metadata files created

2023-11-22 17:36 UTC, TheGreatAxios requested changes

2023-11-22 17:36 UTC, TheGreatAxios commented on _data/chains/eip155-344106930.json
>    "title": "Calypso NFT Hub Testnet",
Remove NFT

2023-11-22 17:36 UTC, TheGreatAxios commented on _data/chains/eip155-1517929550.json
> +  "shortName": "titan-staging",
Titan Testnet?

2023-11-27 13:39 UTC, manuelbarbas commented
Hey @ligi,

Here is Manuel from the SKALE Network team.
Could you please review and merge this PR pls? 

Thank you

2023-11-27 15:25 UTC, ligi approved these changes

2023-11-27 15:25 UTC, merged