Add Innovatorchain
ethereum-lists/chains pull request #3862
Opened 2023-11-27 05:12 UTC by masterdubs

Add innovator chain to the list.

2024-01-02 11:04 UTC, masterdubs commented
Is there something wrong with PR ?

2024-01-14 15:39 UTC, ligi approved these changes

2024-01-14 15:40 UTC, ligi requested changes
resolve conflicts

2024-01-14 19:39 UTC, masterdubs commented
Our commit was before the one that used the same ID, as I understand the first to commit is the first that got the ID no ? 
our commit is #3862 and the other one is #4055 .

2024-01-27 00:28 UTC, ligi approved these changes

2024-01-27 00:28 UTC, merged