Update Scroll Sepolia URLs
ethereum-lists/chains pull request #3887
Opened 2023-11-29 17:47 UTC by dghelm

After launch of Scoll mainnet, testnet URLs have changed.

2023-11-29 18:03 UTC, ligi requested changes
can you provide some docs on these changes?

2023-11-29 19:01 UTC, macvts commented
probably this one to referred -> https://sepolia.scroll.io/portal 
and the old bridge url is for mainnet now @ligi

2023-11-29 19:03 UTC, macvts approved these changes

2023-11-30 04:13 UTC, dghelm commented
Yes! https://docs.scroll.io/en/developers/developer-quickstart/#network-configuration

Tables at the top show the `.com` url, and the first link in [this section](https://docs.scroll.io/en/developers/developer-quickstart/#sepolia-additional-infra) points to the moved testnet bridge.

![image](https://github.com/ethereum-lists/chains/assets/4205837/308da0c9-5118-4f71-a232-6d44328b861a)
![image](https://github.com/ethereum-lists/chains/assets/4205837/03adcf7e-f4ea-4756-8965-4b9fe9dc5e3e)

2023-11-30 06:47 UTC, merged