Add Immutable zkEVM Mainnet
ethereum-lists/chains pull request #3914
Opened 2023-12-04 19:18 UTC by nick8319

Hello, this PR is to add Immutable zkEVM Mainnet network.
Genesis is planned for next week.

Local checks:
- Check JSON Schema / validate_json (push) Successful in 6s [Details](https://github.com/protofire/chains/actions/runs/7091419506/job/19300513525)
- Run prettier / prettier (push) Successful in 18s [Details](https://github.com/protofire/chains/actions/runs/7091419510/job/19300513534)

Gradle build result:

```
BUILD SUCCESSFUL in 1m 12s
8 actionable tasks: 8 executed
```
Thank you!

2023-12-05 07:41 UTC, ligi requested changes
explorer is not reachable 
![image](https://github.com/ethereum-lists/chains/assets/111600/2a0e42ed-6b66-4cea-ae46-024394d9eef7)

2023-12-15 00:46 UTC, nick8319 commented
Hey @ligi the explorer is now available - https://explorer.immutable.com/

2023-12-15 00:55 UTC, nick8319 reviewed
Explorer is now available

2023-12-15 01:04 UTC, ligi approved these changes

2023-12-15 01:04 UTC, merged