Deprecates zksync Goerli and adds new zkSync Sepolia testnet
ethereum-lists/chains pull request #3921
Opened 2023-12-06 09:26 UTC by githubdoramon

Also updates some minor information on all zkSync networks

2023-12-06 09:30 UTC, ligi requested changes
If you deprecate a chain -> you MUST add the status deprecated field
If you really want to reactivate a deprecated chain -> you MUST add the redFlags reusedChainId info

2023-12-06 10:29 UTC, githubdoramon commented
> If you deprecate a chain -> you MUST add the status deprecated field If you really want to reactivate a deprecated chain -> you MUST add the redFlags reusedChainId info

Thanks @ligi . Addressed the comments

2023-12-06 13:22 UTC, Romsters commented on _data/chains/eip155-300.json
> +  "name": "zkSync Sepolia Mainnet",
```suggestion
  "name": "zkSync Sepolia Testnet",
```
?

2023-12-06 13:37 UTC, githubdoramon commented on _data/chains/eip155-300.json
> +  "name": "zkSync Sepolia Mainnet",
oh god. Thanks

2023-12-06 23:53 UTC, tilemanrenovations commented
Hows it going for you Mr .  Digimon?

2023-12-07 04:16 UTC, 9844272456 commented
ในวันที่ พฤ. 7 ธ.ค. 2023 06:54 น. Travis C. Nelson Jr. <
***@***.***> เขียนว่า:

> Hows it going for you Mr . Digimon?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/3921#issuecomment-1843878091>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BEKQF246IEQTWB2BHCE4CBTYIEASJAVCNFSM6AAAAABAJBWKU6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNBTHA3TQMBZGE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-12-07 04:19 UTC, 9844272456 approved these changes

2023-12-07 11:24 UTC, githubdoramon commented
@ligi friendly nudge :) - Can you please review again based on the changes?

2023-12-07 13:32 UTC, merged