Update LightLink network mainnet+testnet RPC's and faucet for testnet
ethereum-lists/chains pull request #3992
Opened 2023-12-18 01:08 UTC by danatpellar

Provide load balanced RPC endpoints and also new link for Pegasus testnet faucet

2023-12-18 13:55 UTC, ligi approved these changes

2023-12-18 14:01 UTC, ligi requested changes
Please run the prettier to format your json according to the style [defined here ](https://github.com/ethereum-lists/chains/blob/master/.prettierrc.json)
e.g. run `npx prettier --write _data/*/*.json`

2023-12-19 04:06 UTC, dan-e-lightlink commented
Hi, I have run prettier over the files now @ligi

2023-12-24 14:42 UTC, ligi approved these changes

2023-12-24 14:43 UTC, merged