Add HALO Network mainnet
ethereum-lists/chains pull request #401
Opened 2021-09-08 12:14 UTC by f4nzkrys31

2021-09-08 13:08 UTC, ligi requested changes
Please make it valid json and use the correct filename

2021-11-02 04:50 UTC, f4nzkrys31 commented
Hi , may i check why the submitted mainnet still cant be search on chainlist.org.
do advice how do get listed on chainlist.org
thanks

2021-11-02 08:54 UTC, ligi commented
it was never merged - so it is not there - and it will not get merged when there is a file `_data/chains/CAIP-2.json`

2021-11-02 16:22 UTC, f4nzkrys31 commented
Hi,thanks for advice. Has removed _data/chains/CAIP-2.json. The file will be automatically merged?

2021-11-02 17:57 UTC, ligi commented on _data/chains/eip155-1280.json
> +    "https://https://nodes.halo.land",
```suggestion
    "https://https://nodes.halo.land"

```

2021-11-02 19:04 UTC, ligi commented on _data/chains/eip155-1280.json
> +  "icon": "HALONetwork",
```suggestion
```

2021-11-03 03:41 UTC, f4nzkrys31 commented
Hi, do i need to amend anything?

2021-11-03 13:34 UTC, ligi commented
yea - CI is not happy about: explorer standard must be 'none' or 'EIP3091'
also I removed the Icon for now - if you want it back you need to actually add the definition ;-)

2021-11-03 13:58 UTC, f4nzkrys31 commented
had removed the explorer and pending review.

2021-11-03 13:58 UTC, ligi commented
you do not need to remove the whole explorer section - just add the `standard` field
and if you remove it - please remove it proper - you now produced invalid json

2021-11-03 14:05 UTC, f4nzkrys31 commented
> you do not need to remove the whole explorer section - just add the `standard` field and if you remove it - please remove it proper - you now produced invalid json

sorry for that. not a tech guy.
i hope it is correct now.

2021-11-03 14:10 UTC, ligi requested changes
seems this explorer is not EIP3091 compatible - e.g. see:

https://browser.halo.land/block/1

please fix or use 'none'

also when using a icon here you need to define it

2021-11-03 14:12 UTC, f4nzkrys31 commented
updated to "none"

2021-11-03 14:30 UTC, ligi commented on _data/chains/eip155-1280.json
> +    "explorers": [{
```suggestion
"explorers": [{
```

2021-11-03 14:36 UTC, ligi commented on _data/chains/eip155-1280.json
> +"explorers": [{
```suggestion
  "explorers": [{
```

2021-11-03 14:49 UTC, merged

2021-11-03 14:49 UTC, ligi commented
:tada: