Updated Firchain Explorer and ZkEvm Testnet
ethereum-lists/chains pull request #4081
Opened 2024-01-02 01:52 UTC by 0xfirechain

2024-01-02 02:21 UTC, Morhef approved these changes

2024-01-02 05:15 UTC, shahzadrahim1 commented
hi

On Tue, Jan 2, 2024, 7:23 AM Morhef ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/4081#pullrequestreview-1799908886>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BB3AJ2QFN4ZK24JJY3HVY5LYMNVRNAVCNFSM6AAAAABBJOPPXOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJZHEYDQOBYGY>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-01-04 22:34 UTC, ligi requested changes
![image](https://github.com/ethereum-lists/chains/assets/111600/baec8e2d-24e2-42ba-9e99-736b7f982500)

2024-01-07 12:50 UTC, KingRobZombie-CEO approved these changes

2024-01-15 21:37 UTC, 0xfirechain commented
Hi, sorry for the late reply. The explorer link has just been removed for now. Thank you guys so much

2024-02-25 12:24 UTC, closed without merging