Add Cryptoth Chain eip155-997
ethereum-lists/chains pull request #416
Opened 2021-09-14 15:00 UTC by magic9911

2021-09-14 15:45 UTC, ligi requested changes
I cannot check the  explorer - please fix then LMK:

![image](https://user-images.githubusercontent.com/111600/133290179-5aec44eb-245a-46b8-815a-194838485675.png)

2021-09-15 15:00 UTC, magic9911 commented
> I cannot check the explorer - please fix then LMK:
> 
> ![image](https://user-images.githubusercontent.com/111600/133290179-5aec44eb-245a-46b8-815a-194838485675.png)

now web ready update..

2021-09-15 16:45 UTC, ligi requested changes
![image](https://user-images.githubusercontent.com/111600/133475013-d56fc008-c018-4975-8127-dd82bcbc22e8.png)

2022-03-11 23:07 UTC, Lucid369 approved these changes

2022-05-01 02:14 UTC, closed without merging