add Fantom testnet
ethereum-lists/chains pull request #432
Opened 2021-09-23 16:54 UTC by pierreneter

- Main website: https://fantom.foundation/
- Testnet explorer: https://testnet.ftmscan.com/

2021-09-24 11:12 UTC, ligi approved these changes

2021-09-24 11:14 UTC, ligi requested changes
short name must be unique - but found `ftm` more than once

2021-09-24 14:48 UTC, pierreneter commented
hi @ligi, thanks for the feedback, I fixed it. Please review again.

2021-09-24 21:45 UTC, Claudio060320 approved these changes
#432

2021-09-25 23:50 UTC, Claudio060320 approved these changes

2021-09-26 14:31 UTC, merged