Create epi155-710420.json
ethereum-lists/chains pull request #4382
Opened 2024-02-16 19:32 UTC by nstamm10

2024-02-16 23:17 UTC, calmbeforeu approved these changes

2024-02-20 15:44 UTC, connorch commented on _data/chains/epi155-710420.json
> +  ],
Looks like the CI failed due to formatting of this line.  I think it needs to be formatted like this?

```suggestion
  "rpc": ["https://subnets.avax.network/tiltyard/mainnet/rpc"],
```

2024-02-20 16:33 UTC, ligi requested changes
it states it quite clearly
![Uploading image.png…]()

2024-02-21 14:32 UTC, nstamm10 commented
@ligi Could you please explain? Unfortunately, that link is not working for me.

2024-02-24 10:21 UTC, ligi commented
EPI!=EIP

2024-02-26 14:21 UTC, nstamm10 commented
Thanks!

2024-02-27 17:28 UTC, closed without merging