Add RSS3 mainnet and sepolia testnet info
ethereum-lists/chains pull request #4504
Opened 2024-03-08 13:13 UTC by Songkeys

2024-03-16 10:05 UTC, Songkeys commented
@ligi Hi. I think this could be merged now. Could you please take another look? Thank you!

2024-04-03 18:29 UTC, azuic commented
hey @ligi - we’d like to support the maintenance of the repo and hope this donation can help: 0xbb94be3dc177071fb1e06bc0783cfa6661601bed8bb1f0cb5c2aa4d183dfab9b

meanwhile, is it possible to expedite the pr?

2024-04-03 18:41 UTC, ligi requested changes

2024-04-03 18:41 UTC, ligi commented on _data/chains/eip155-2331.json
> +  "icon": "rss3",
```suggestion
  "icon": "rss3-testnet",
```

2024-04-03 18:44 UTC, ligi approved these changes
Thanks - fixed the error and merging the PR

2024-04-03 18:44 UTC, merged