feature: Added Masa Mainnet
ethereum-lists/chains pull request #4560
Opened 2024-03-14 17:08 UTC by H34D

2024-03-14 21:50 UTC, ligi requested changes
![image](https://github.com/ethereum-lists/chains/assets/111600/136c87f1-5530-436f-91da-ac2281529d37)

2024-03-28 07:32 UTC, H34D commented
@ligi thanks for bearing with me, the block explorer should be installed by the end of today

2024-03-29 16:26 UTC, H34D commented
now all links should work @ligi

2024-03-30 01:46 UTC, ligi approved these changes

2024-03-30 01:46 UTC, merged