Add support for re.al chain
ethereum-lists/chains pull request #4577
Opened 2024-03-17 09:45 UTC by veljkoTNFT

Update data for Unreal testnet because
chainId changed. We had to move away from zkEVM Polygon CDK because it wasn't production ready, and we spinned up unreal with Arbitrum CDK.

2024-03-17 09:49 UTC, veljkoTNFT commented
@ligi I saw that you were the one who approved my previous request for unreal. As explained in PR request, we had to move away and deprecate previous testnet so we spinned up a new one. If something more is needed to mitigate this, please let me know. Also, I think I inputed the info about our mainnet correctly, re.al. Incubating is when I'm not certain about all of the information, right?

2024-03-18 13:42 UTC, ligi requested changes
you cannot remove chains - only deprecate them

2024-03-18 18:06 UTC, veljkoTNFT commented
> you cannot remove chains - only deprecate them

How can I do that? leave the file and change the state?

2024-03-18 19:01 UTC, veljkoTNFT commented
@ligi I hope now everything is ok, pls check

2024-03-18 21:26 UTC, OTC15203 approved these changes

2024-03-18 21:26 UTC, OTC15203 approved these changes

2024-03-22 06:35 UTC, ElvisKrop commented
Hello @ligi :wave: 
Please take a look at this PR once again when you will have time :pray:

2024-03-25 16:35 UTC, veljkoTNFT commented
Hey @ligi  can you check this pls? Everything is passing, I even have approve, can you merge this pls?

2024-03-27 14:18 UTC, veljkoTNFT commented
@ligi kind reminder

2024-03-28 11:32 UTC, veljkoTNFT commented
@OTC15203  can you merge my PR? Or at least if something is wrong tell me? My PR is stuck for weeks now, and we are closing launch date.

2024-03-28 11:34 UTC, ligi approved these changes

2024-03-28 11:34 UTC, merged