clubmos Mainnet
ethereum-lists/chains pull request #4755
Opened 2024-04-04 06:26 UTC by Karthigasrini

2024-04-18 00:38 UTC, ligi requested changes

2024-04-18 00:38 UTC, ligi commented on _data/chains/eip155-1188.json
> +      "standard": "EIP3091"
not compatible

```suggestion
      "standard": "none"
```

2024-04-18 16:56 UTC, ligi approved these changes

2024-04-18 16:56 UTC, merged

2024-04-23 22:27 UTC, LizetteO commented
Hello

Please help me solve this problem

Kind Regards,
Lizette

On Thu, Apr 18, 2024 at 6:57 PM ligi ***@***.***> wrote:

> Merged #4755 <https://github.com/ethereum-lists/chains/pull/4755> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/4755#event-12526460912>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANDYFI3V5MAAJQJMC7FPI73Y573OBAVCNFSM6AAAAABFWUBJ6OVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSGUZDMNBWGA4TCMQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>