chore: add taiko mainnet as incubating
ethereum-lists/chains pull request #4777
Opened 2024-04-05 15:14 UTC by d1onys1us

2024-04-07 12:39 UTC, ligi requested changes
you need to remove the explorer if it is not working

2024-04-18 06:49 UTC, d1onys1us commented
> you need to remove the explorer if it is not working

addressed ee3ca44de3f0aa20b86e7af9dab650c081ea2848

2024-04-18 16:54 UTC, ligi approved these changes

2024-04-18 16:54 UTC, merged

2024-04-23 22:27 UTC, LizetteO commented
Hello

Please help me solve this problem

Kind Regards,
Lizette

On Thu, Apr 18, 2024 at 6:55 PM ligi ***@***.***> wrote:

> Merged #4777 <https://github.com/ethereum-lists/chains/pull/4777> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/4777#event-12526439779>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANDYFI7VFXH7KOOPM6VRHWLY573GRAVCNFSM6AAAAABFZKTNVCVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSGUZDMNBTHE3TOOI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>