Remove sunset networks and add Boba Sepolia L2
ethereum-lists/chains pull request #4778
Opened 2024-04-05 22:53 UTC by boyuan-chen

- Boba Rinkeby, Goerli, Avax, Moonbeam, and Fantom L2s are sunset
- Add Boba Sepolia L2

2024-04-06 07:53 UTC, D777Del approved these changes

2024-04-06 11:17 UTC, Hanae1963 approved these changes

2024-04-07 06:23 UTC, IndigoFlo approved these changes

2024-04-07 11:01 UTC, ligi requested changes
you cannot remove networks - only mark them deprecated

2024-04-07 14:54 UTC, Hanae1963 approved these changes

2024-04-07 20:49 UTC, Alkhatri77 approved these changes
Alkhatri77

2024-04-07 22:40 UTC, boyuan-chen commented
> you cannot remove networks - only mark them deprecated

Fixed!

2024-04-10 11:30 UTC, ligi approved these changes

2024-04-10 11:30 UTC, merged