adding new chain BILLIONAIRE CLUB mainnet
ethereum-lists/chains pull request #4895
Opened 2024-04-21 06:19 UTC by bcc2025

did all build & formatting process

2024-04-21 06:25 UTC, bcc2025 commented
@ligi Hi, Could you please take a moment to review this PR? Getting our chain on Chainlist is time-sensitive. Thanks in advance!

2024-04-21 12:58 UTC, Blyla approved these changes

2024-04-21 13:19 UTC, bcc2025 commented
@Blyla Hi, Could you please take a moment to review this PR? Getting our chain on Chainlist is time-sensitive. Thanks in advance!

2024-04-21 13:36 UTC, ligi commented
If it is time-sensitive please pay funds to lists.eth (in your case 0.5ETH) - otherwise this PR will sit for a while

2024-04-27 06:26 UTC, Jpazm01 commented on _data/icons/billionaireclub.json
Who what do I do here?

2024-05-09 12:19 UTC, ligi requested changes
![image](https://github.com/ethereum-lists/chains/assets/111600/43a31847-f037-4b5b-9665-60731a2b6a49)

2024-06-28 01:49 UTC, closed without merging