Create TSC Mainnet eip155-345
ethereum-lists/chains pull request #5087
Opened 2024-05-17 06:09 UTC by vv5d

Create TSC Mainnet eip155-345

2024-05-19 15:16 UTC, ligi requested changes
explorer does not seem to be EIP3091 compatible

2024-05-24 10:09 UTC, vv5d commented
We've addressed all the problems, please review it here @ligi

2024-05-27 02:12 UTC, vv5d commented
**Action errors:**
connecting to https://rpc01.trias.one/
Client:Geth/v1.1.17-1bc5d0f7-20240327/linux-amd64/go1.18.2
BlockNumber:3782392
GasPrice:1000000000
Exception in thread "main" java.lang.IllegalStateException: RPC chainId (16) does not match chainId from json (345)

**After replacing chainId:**
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' https://rpc01.trias.one
{"jsonrpc":"2.0","id":1,"result":"0x159"}
```
please review it here @ligi,  thks.

2024-06-04 19:10 UTC, ligi approved these changes

2024-06-04 19:10 UTC, merged