Add chain ID 2777 for GM Network Mainnet
ethereum-lists/chains pull request #5202
Opened 2024-05-31 04:14 UTC by revotu

Just reserve chain ID 2777 for GM Network Mainnet. 

We are still working on RPC and Explorer (Launching Mainnet).  and we will update its value ​​later next week.

2024-05-31 07:59 UTC, ligi requested changes
add incubating flag

2024-05-31 09:57 UTC, revotu commented
> add incubating flag

done.  Already updated incubating status

2024-06-02 04:59 UTC, revotu commented
@ligi  Updated json format, I've run npx prettier --write _data/*/*.json.

2024-06-04 19:04 UTC, ligi approved these changes

2024-06-04 19:04 UTC, merged