Add Ham chain
ethereum-lists/chains pull request #5203
Opened 2024-05-31 05:32 UTC by gustavoguimaraes

Add Ham chain

2024-06-01 21:50 UTC, ligi requested changes
![image](https://github.com/ethereum-lists/chains/assets/111600/0eff2f05-7406-4fc2-988f-f0067f29f07a)

2024-06-05 12:30 UTC, justinridgely commented
@ligi Would greatly appreciate you taking a look at this as soon as you can.  Thank you!

2024-06-06 23:07 UTC, thewalterwhite commented
@ligi Sending a quick message again. We'd really appreciate it if you could review this as soon as you can. Thank you in advance!

2024-06-07 22:07 UTC, ligi approved these changes

2024-06-07 22:07 UTC, merged