fix short names for hydra chains
ethereum-lists/chains pull request #5230
Opened 2024-06-05 08:31 UTC by R-Santev

2024-06-05 08:44 UTC, ligi requested changes
can you elaborate?

2024-06-05 08:49 UTC, R-Santev commented
The business team requested the short name of the chain to be changed to uppercase.

Thanks in advance!

2024-06-05 08:51 UTC, ligi commented
If I need to put in work because the business team decided something - please send some funds to lists.eth

2024-06-07 22:05 UTC, ligi approved these changes

2024-06-07 22:06 UTC, merged