Add Vcity testnet
ethereum-lists/chains pull request #5482
Opened 2024-07-12 12:05 UTC by rahulmaske77

Vcity Chain
Testnet
RPC: https://testnet.vcity.app/
Explorer: https://scan.vcity.app/
Symbol: VCITY
Chain ID: 20230825

2024-07-13 01:29 UTC, rahulmaske77 commented
@ligi could you please approve the workflow as the all checks have passed on my fork.

2024-07-16 19:55 UTC, ligi requested changes
explorer does not seem to be EIP3091 compatible

2024-07-17 11:27 UTC, rahulmaske77 commented
@ligi  Thanks for the response. explorer updated to match  EIP3091 standards Please check.

2024-07-18 06:49 UTC, ligi approved these changes

2024-07-18 06:49 UTC, merged