Add Alaya mainnet
ethereum-lists/chains pull request #551
Opened 2021-11-10 09:47 UTC by benbaley

Add Alaya mainnet

2021-11-10 12:08 UTC, ligi requested changes
short name must be unique - but found `PlatON` more than once

2021-11-11 02:55 UTC, benbaley commented
> short name must be unique - but found `PlatON` more than once



> short name must be unique - but found `PlatON` more than once

I have changed the `shortname` of PlatON testnet to 'platondev' and kept the shortname of PlatON mainnet, will this work please?

2021-12-26 20:51 UTC, ligi requested changes
The chainId in the filename does not match the chainID in the json

2022-02-07 09:05 UTC, mohamadrezakheradmand commented on _data/chains/eip155-210309.json
> +  "shortName": "platondev",
platondev

2022-02-07 09:06 UTC, mohamadrezakheradmand commented on _data/chains/eip155-210309.json
> -  "faucets": [],
شیر الات

2022-02-07 09:06 UTC, mohamadrezakheradmand reviewed
شیرالات

2022-02-07 09:08 UTC, mohamadrezakheradmand commented on _data/chains/eip155-210309.json
> +  "shortName": "platondev",
platondev

2022-02-10 09:36 UTC, closed without merging