add fusespark
ethereum-lists/chains pull request #560
Opened 2021-11-14 17:31 UTC by henry-hz

2021-11-14 22:55 UTC, ligi requested changes
short name must be unique - but found `fuse` more than once

2021-11-16 11:34 UTC, ligi commented
you checked in a lot of unrelated files now - please fix

2021-11-16 12:40 UTC, henry-hz commented
ops, sorry, fixing now


On Tue, Nov 16, 2021 at 1:34 PM ligi ***@***.***> wrote:

> you checked in a lot of unrelated files now - please fix
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/560#issuecomment-970183556>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHWSWAP2SFIQAVEMRZWHB3UMI6T5ANCNFSM5IACQ5PQ>
> .
>

2021-11-16 12:44 UTC, ligi commented
replaced by #565

2021-11-16 12:44 UTC, closed without merging