Adding CAMP L2
ethereum-lists/chains pull request #5608
Opened 2024-08-02 06:40 UTC by hydrogenbond007

pr to add camp network testnet to chainlist, here is the [developer documentation](https://docs.campnetwork.xyz/building-on-camp/add-camp-network#how-to-connect-to-camp-network)

2024-08-03 20:17 UTC, macvts reviewed
make sure to sync forked repo to updated with reference from original branch

2024-08-03 20:17 UTC, macvts commented on _data/chains/eip155-325000.json
> +  "icon": "CampL2",
the submitted pr didn't have icon, so rather take this out or add up icon file

2024-08-12 06:08 UTC, hydrogenbond007 commented
@macvts removed logo and updated the branch

2024-08-14 13:57 UTC, ligi requested changes
add parent field

2024-09-06 13:51 UTC, ligi requested changes
short name must be unique - but found `CAMP` more than once

2024-09-09 07:57 UTC, hydrogenbond007 commented
@ligi Sorry kinda confused, here did you found the name twice?

2024-09-10 09:31 UTC, hydrogenbond007 commented
Oh seems like you are referencing to #4878, that pr was for Camp Testnet V1 and has been depreciated, seems like #5331 was trying to accomplish the testnet v2 upgrade.

2024-10-30 01:59 UTC, closed without merging