Maalchain V2 Configuration added
ethereum-lists/chains pull request #5625
Opened 2024-08-04 16:57 UTC by maalchain

2024-08-04 22:10 UTC, ligi requested changes
please remove .anima/.gitignore

2024-08-05 04:16 UTC, Jetsoanalin commented
Removed the .anima file.

2024-08-07 04:40 UTC, maalchain commented
@ligi can you look into the changes which we performed ?

2024-08-08 19:23 UTC, ligi approved these changes

2024-08-08 19:25 UTC, merged