Adding Creditcoin 3 Mainnet Chain
ethereum-lists/chains pull request #5726
Opened 2024-08-22 20:46 UTC by BradleyOlson64

This PR should ideally be merged soon after the new mainnet launches, 2024-08-28 10am EST.

2024-08-27 21:32 UTC, ligi requested changes
![image](https://github.com/user-attachments/assets/cefc0ff2-c52c-4b77-a114-30a0d3257cab)

2024-08-28 05:33 UTC, BradleyOlson64 commented
The blockscout link should be good tomorrow after mainnet launches. 

I'll leave another message here once I've verified the link to ask for another CI run.

Thanks for your patience!

2024-08-29 12:30 UTC, beqaabu commented
Hi @ligi, all the checks have passed and we would appreciate it if you could review and merge the pr :pray:

2024-09-07 04:40 UTC, ligi approved these changes

2024-09-07 04:40 UTC, merged