Update chain 31415 data to Wirex Pay
ethereum-lists/chains pull request #5901
Opened 2024-09-24 12:35 UTC by rfortunatov

Hi. I'm working in Wirex company and we're launching a new product called Wirex Pay. We're on the final stage of launch and we've chosen chain id that was previously used by FIL Wallaby testnet. This testnet is not active anymore so I would like to ask to update this chain data to Wirex Pay.
https://github.com/filecoin-project/testnet-wallaby - here's official FIL repository stating that Wallaby was discontinued. 
https://docs.wirexpaychain.com/tech/wirex-pay-chain - here's our product documentation. 
Thanks in advance.

2024-09-24 15:14 UTC, ligi requested changes
you need to add redFlags - reusedChainId

2024-09-25 01:03 UTC, rfortunatov commented
> you need to add redFlags - reusedChainId

Done

2024-09-26 09:36 UTC, rfortunatov commented
@ligi I've added required red flag. Can we merge this?

2024-09-26 11:22 UTC, ligi approved these changes

2024-09-26 11:22 UTC, merged