Add Zenchain Testnet to list
ethereum-lists/chains pull request #5908
Opened 2024-09-26 17:46 UTC by krisbitney

This PR adds the Zenchain Testnet network to the chain list. Thank you!

2024-09-27 18:19 UTC, krisbitney commented
> the 2 explorers are the same

Thanks. I removed the explorer from the mainnet entry. 

The Zenchain mainnet does not yet exist. We are about to launch the testnet and we wanted to reserve the chain ID 8108 for the mainnet, which we expect to release in Q2 2025. If reserving the chain ID like that is not allowed, I can remove the mainnet JSON file altogether.

2024-09-28 09:06 UTC, ligi requested changes
please add status incubating to the chain that is not yet active

2024-09-30 09:28 UTC, krisbitney commented
> please add status incubating to the chain that is not yet active

Thank you. This has been completed. I appreciate your time.

2024-09-30 11:15 UTC, ligi approved these changes

2024-09-30 11:15 UTC, merged