Update eip155-2023.json
ethereum-lists/chains pull request #5935
Opened 2024-10-04 16:01 UTC by BharatBlockChain

2024-10-05 05:08 UTC, ligi requested changes
the other chain seems inoperative currently - but I would like to wait a bit to see if it is not just temporary

2024-10-07 02:48 UTC, BharatBlockChain commented
> the other chain seems inoperative currently - but I would like to wait a bit to see if it is not just temporary

Thanks for letting me know. May i know the next step ?

2024-10-18 05:52 UTC, BharatBlockChain commented
Please review the updates

2024-10-25 13:42 UTC, ligi requested changes
ok the other chain seems to be really down - but you need to add redflags reusedchainid

2024-11-19 18:27 UTC, BharatBlockChain commented
Dear Team, Please review the RPC

2024-11-19 18:31 UTC, BharatBlockChain reviewed
Updated 
"redflags": {
    "reusedchainid": true
  },

2024-11-19 18:31 UTC, BharatBlockChain commented
Dear Team, Please Review.

2024-11-29 11:22 UTC, ligi requested changes
CI failing -> no review

2025-01-19 02:00 UTC, closed without merging