Updates Redbelly Network Mainnet RPC
ethereum-lists/chains pull request #6041
Opened 2024-10-22 05:51 UTC by namanB8

2024-10-22 12:41 UTC, Fart10 reviewed
🔥

2024-10-23 12:34 UTC, ligi requested changes
please add the other explorer and do not replace

2024-11-02 02:08 UTC, Alhaidra reviewed
Updates RPC URL for Mainnet
Updates Block Explorer URL for Testnet

2024-11-13 03:28 UTC, Alhaidra commented on _data/chains/eip155-151.json
> +  "rpc": ["https://governors.mainnet.redbelly.network"],
- [ ]

2024-11-14 16:17 UTC, Alhaidra reviewed
hello my world

2024-11-14 16:18 UTC, Alhaidra commented
hello my world

2025-01-04 01:57 UTC, closed without merging