incubating swell mainnet 1923
ethereum-lists/chains pull request #6084
Opened 2024-10-28 10:50 UTC by cryptoquantx

This is to reserve chainId 1923

2024-10-28 11:03 UTC, tilemanrenovations commented
> You successfully submitted a PR! Due to the amount of PRs coming in: we will only look at PRs that the CI is happy with. We can also not hold your hand getting the CI green - just look how others that where merged did it and RTFM. So as long as there is any CI check that reports an error - no human will look at this. You might be able to ask for some support after supporting the project - e.g. by sending funds to lists.eth. When you fixed things after a requested change - then you also need to (re-)request a review.

2024-10-28 12:02 UTC, tilemanrenovations reviewed
TnMe4Rteam

2024-10-29 14:54 UTC, ligi requested changes
add status incubating then and remove stuff that is not yet there like RPCs

2024-10-31 10:26 UTC, ligi approved these changes

2024-10-31 10:26 UTC, merged