chore: add all lower nibiru envs
ethereum-lists/chains pull request #6118
Opened 2024-10-31 17:51 UTC by cgilbe27

2024-11-05 15:37 UTC, cgilbe27 commented
This MR is ready

2024-11-07 03:48 UTC, ligi requested changes
you cannot delete chains - only mark them deprecated. This is important to prevent replay attacks

2024-11-10 20:17 UTC, cgilbe27 commented
> you cannot delete chains - only mark them deprecated. This is important to prevent replay attacks

Addressed

2024-11-12 15:27 UTC, Unique-Divine commented on _data/chains/eip155-7210.json
>    "icon": "nibiru",
Note that in other deprecated Chain ID files, it uses the deprecated "chainId" and "networkId", not the new values.

2024-11-23 07:47 UTC, ligi requested changes
RPC chainId (7220) does not match chainId from json (6920)

2025-01-08 13:55 UTC, cgilbe27 commented
> RPC chainId (7220) does not match chainId from json (6920)

This will eventually be our chain ID (6920)

2025-03-06 17:57 UTC, closed without merging