Create Evmokripton.json
ethereum-lists/chains pull request #617
Opened 2021-12-01 21:42 UTC by Tresh123

2021-12-02 13:25 UTC, ligi requested changes
this file is emply and wrongly named

2021-12-02 15:34 UTC, Tresh123 commented
> этот файл правильно и неправильно назван



> 

правильно

2021-12-02 20:22 UTC, Tresh123 commented
> этот файл правильно и неправильно назван

Пожалуйста поясните, что значит правильно и неправильно?

2021-12-03 16:33 UTC, ligi commented
nothing is correct ..

2021-12-24 16:29 UTC, closed without merging