Add : EMoney network Mainnet
ethereum-lists/chains pull request #6225
Opened 2024-11-18 11:33 UTC by deepaks-scallopx

Add EMoney network Mainnet to chains

2024-11-23 11:39 UTC, dav3yblaz3 reviewed
the greatest team ever

2024-11-23 14:38 UTC, ligi requested changes
resolve conflicts

2024-12-05 11:47 UTC, closed without merging

2024-12-07 13:32 UTC, dav3yblaz3 reviewed
lets try this

2024-12-07 13:33 UTC, dav3yblaz3 reviewed
lets do this team

2024-12-07 13:35 UTC, dav3yblaz3 commented on _data/chains/eip155-4544.json
i have submitted changes lets get this to testing