adding a network timex
ethereum-lists/chains pull request #6260
Opened 2024-11-25 07:05 UTC by ojhasujeet123

check and verify the files and merge it on master branch

2024-12-01 08:02 UTC, ligi requested changes
resolve conflicts

2024-12-02 06:20 UTC, ojhasujeet123 commented
what conflicts arises on the code pls explain , that's helpme to solve the conflicts.

2024-12-09 07:21 UTC, ojhasujeet123 commented
please check these file and merge it on master , and if any error left then explain it

2024-12-09 07:34 UTC, ojhasujeet123 reviewed
Check the file and explain what is issue addressed to not able to merge it on master .

2024-12-10 06:01 UTC, ojhasujeet123 commented
check again

2024-12-10 06:04 UTC, ligi commented
as long as CI is red I do not check

2024-12-10 06:13 UTC, ojhasujeet123 commented
pls explain what is ci ?

2025-02-01 01:59 UTC, closed without merging