Add ZKcandy Mainnet
ethereum-lists/chains pull request #6329
Opened 2024-12-03 16:41 UTC by marleymarl

2025-02-05 18:18 UTC, ligi requested changes
https://explorer.zkcandy.io does not seem to be a explorer

2025-02-05 18:46 UTC, marleymarl commented
> https://explorer.zkcandy.io does not seem to be a explorer

Apologies - https://explorer.zkcandy.io is working now.

2025-02-05 19:09 UTC, ligi requested changes
can you create a tx on the chain so I can check if it is EIP3091 compatible?

2025-02-06 16:27 UTC, marleymarl commented
> can you create a tx on the chain so I can check if it is EIP3091 compatible?

Yes, done - apologies for the delay in responding.

2025-02-06 16:31 UTC, ligi approved these changes

2025-02-06 16:31 UTC, merged

2025-07-12 12:26 UTC, anton584oh reviewed
😃

2025-08-21 22:04 UTC, FranciscoBelchior reviewed
Aprovado