Update Flow network names, remove Flow previewnet
ethereum-lists/chains pull request #6334
Opened 2024-12-04 02:59 UTC by btspoony

2024-12-05 07:00 UTC, ligi requested changes
you cannot delete chains - only mark them deprecated. This is important to prevent replay attacks

2024-12-05 09:54 UTC, btspoony commented
> you cannot delete chains - only mark them deprecated. This is important to prevent replay attacks

Got it, fixed

2025-01-25 15:16 UTC, btspoony commented
@ligi could you please merge it? 
For now, it is just a simple name change.

2025-02-07 22:56 UTC, ligi requested changes
CI failures -> no merge

2025-02-08 05:40 UTC, btspoony commented
Hi @ligi,
CI failed because the deprecated network is unaccessable.
Now I removed rpc and explorer from the deprecated network.
Could you approve the CI workflows to check it again?

2025-02-19 10:50 UTC, ligi approved these changes

2025-02-19 10:50 UTC, merged