tendermint node removed
ethereum-lists/chains pull request #6363
Opened 2024-12-06 10:19 UTC by jurakontor

2024-12-07 09:20 UTC, ligi requested changes
why the removal?

2024-12-07 09:36 UTC, jurakontor commented
the 2nd rpc node was teneredmint rpc - should not be used. hence removed


On Sat, 7 Dec 2024 at 13:21, ligi ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> why the removal?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/6363#pullrequestreview-2486466217>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMOHI2G6N3K4W3P4ABGB532EK4X5AVCNFSM6AAAAABTELMMZ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOBWGQ3DMMRRG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-07 10:11 UTC, ligi commented
why shouldn't it be used?

2024-12-07 10:14 UTC, jurakontor commented
metamask cannot be connected to this rpc node.
[image: image.png]

On Sat, 7 Dec 2024 at 14:11, ligi ***@***.***> wrote:

> why shouldn't it be used?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/6363#issuecomment-2525059582>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMOHI3Y5R44XQBDZSU2CLL2ELCWVAVCNFSM6AAAAABTELMMZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRVGA2TSNJYGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-07 10:21 UTC, ligi commented
the image is not visible

2024-12-07 10:22 UTC, jurakontor commented
It's OK for now.
I'm.on it . I'll see what I can do

On Sat, 7 Dec 2024, 14:21 ligi, ***@***.***> wrote:

> the image is not visible
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum-lists/chains/pull/6363#issuecomment-2525061901>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMOHI7W5ZSHXZZVOENK63T2ELD2JAVCNFSM6AAAAABTELMMZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRVGA3DCOJQGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-08 06:57 UTC, jurakontor commented
any idea when change will be active ?

2024-12-10 07:34 UTC, jurakontor commented
hello, my latest update still not available in chainlist. could you pls check . thanks

2024-12-10 07:41 UTC, jurakontor commented
Regarding the icon:
url in _data/icons/emoney.json  is ipfs://bafkreigo4gtboztftjdnbvy2rb2ku2gxxbhm4iwutzgnzhvden3vcbsqui
it works through https://ipfs.io/ipfs/bafkreigo4gtboztftjdnbvy2rb2ku2gxxbhm4iwutzgnzhvden3vcbsqui correctly but not shown in https://chainlist.org/chain/4545
Please help.
thanks

2024-12-10 07:42 UTC, jurakontor commented
hello


Regarding the icon:
url in _data/icons/emoney.json is
ipfs://bafkreigo4gtboztftjdnbvy2rb2ku2gxxbhm4iwutzgnzhvden3vcbsqui
it works through
https://ipfs.io/ipfs/bafkreigo4gtboztftjdnbvy2rb2ku2gxxbhm4iwutzgnzhvden3vcbsqui
correctly
but not shown in https://chainlist.org/chain/4545


Please help.
thanks


On Sat, 7 Dec 2024 at 14:21, Juri ***@***.***> wrote:

> It's OK for now.
> I'm.on it . I'll see what I can do
>
> On Sat, 7 Dec 2024, 14:21 ligi, ***@***.***> wrote:
>
>> the image is not visible
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ethereum-lists/chains/pull/6363#issuecomment-2525061901>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ABMOHI7W5ZSHXZZVOENK63T2ELD2JAVCNFSM6AAAAABTELMMZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRVGA3DCOJQGE>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2024-12-10 07:43 UTC, ligi commented
https://github.com/ethereum-lists/chains/pull/6363#issuecomment-2522750099

2025-02-27 02:00 UTC, closed without merging