Create dithereum.json
ethereum-lists/chains pull request #643
Opened 2021-12-09 18:55 UTC by solidityx

added ICON for the Dithereum network

2021-12-09 21:39 UTC, ligi requested changes
Explorer section needs a standard field

2021-12-12 12:17 UTC, solidityx commented
> Explorer section needs a standard field

New commits has that changes. And we are waiting for the etherscan like explorer, yet. We can proceed further once it will be up. Thank you.

2021-12-12 13:17 UTC, ligi commented
pls ping me when it is up

2021-12-13 17:30 UTC, solidityx commented
> pls ping me when it is up
Thanks for your time.. 

Can I remove explorer part for now?  I just want the chain ID to be secured.. and add explorer when its up?  Thanks again.

2021-12-14 08:52 UTC, solidityx commented
Removed explorer details for now. hope to get it added now :D
Thanks for your time..

2021-12-17 11:49 UTC, ligi commented on _data/icons/dithereum.json
> +
```suggestion
```

2021-12-17 11:49 UTC, ligi commented on _data/icons/dithereum.json
> +
```suggestion
```

2021-12-17 11:53 UTC, ligi commented on _data/chains/eip155-34.json
> +  "ens": {}
```suggestion
```

2021-12-17 11:56 UTC, ligi commented on _data/chains/eip155-34.json
> +  "networkId": 34,
```suggestion
  "networkId": 34
```

2021-12-18 11:56 UTC, merged

2023-10-23 18:14 UTC, Hawkins37 approved these changes