Add Hyperliquid EVM Testnet
ethereum-lists/chains pull request #6495
Opened 2024-12-22 15:02 UTC by suraneti

Replaced the non-functional `Lucy Network`.

After testing the RPC, it appears the `Lucy Network` is no longer operational.

2024-12-25 13:40 UTC, ligi requested changes
You for sure need to add redFlags reusedChainId

2024-12-31 04:04 UTC, suraneti commented
@ligi Thanks, I’ve updated following your comment.

2025-01-05 01:24 UTC, suraneti commented
@ligi I've fixed the CI error, could you please re-run CI again?

2025-01-08 14:10 UTC, ligi requested changes
Found unreference bafkreidmvcd5i7touug55hj45mf2pgabxamy5fziva7mtx5n664s3yap6m in ../_data/iconsDownload

2025-01-10 04:28 UTC, suraneti commented
@ligi fixed, please re-run CI again.

2025-01-15 15:14 UTC, merged