Update eip155-8217.json
ethereum-lists/chains pull request #654
Opened 2021-12-12 10:14 UTC by benjioh5

- remove Klayn Official JSON-RPC route (Klaytn official API doesn't work any more)
- add ozys JSON-RPC route
- add klaytnscope uri

2021-12-12 10:41 UTC, ligi requested changes
This explorer violates EIP3091 when it comes to addresses

2021-12-14 08:10 UTC, benjioh5 commented
@ligi remove standard info

2021-12-17 11:43 UTC, ligi commented on _data/chains/eip155-8217.json
> +  }]
```suggestion
  "explorers": [{
    "name": "Klaytnscope",
    "url": "https://scope.klaytn.com",
    "standard": "none"
  }]
```

2021-12-17 11:48 UTC, merged

2021-12-17 13:34 UTC, benjioh5 commented
Thanks a lot!