adding explorer urls for aurora main/test chains
ethereum-lists/chains pull request #773
Opened 2022-01-15 03:41 UTC by applestoapples

Add aurora's explorer urls for the Aurora Mainnet (1313161554) and TestNet (1313161555) chains.

2022-01-15 10:50 UTC, ligi commented on _data/chains/eip155-1313161554.json
> +      "url": "https://explorer.mainnet.aurora.dev/",
```suggestion
      "url": "https://explorer.mainnet.aurora.dev",
```

2022-01-15 10:51 UTC, ligi requested changes

2022-01-15 10:51 UTC, ligi commented on _data/chains/eip155-1313161555.json
> +      "url": "https://explorer.testnet.aurora.dev/",
```suggestion
      "url": "https://explorer.testnet.aurora.dev",
```

2022-01-15 11:35 UTC, merged

2022-08-21 09:05 UTC, alfiomy reviewed
_data/chains/eip155-1313161554.json