OYchain apply for networkID 126, thanks, details please see   EIP155-126.json
ethereum-lists/chains pull request #785
Opened 2022-01-19 15:12 UTC by nfttoken

OYchain apply for networkID 126, 
details information please see   EIP155-126.json, 

thanks very much

2022-01-19 15:17 UTC, ligi commented on _data/chains/EIP155-126.json
> +    "faucets": [http://faucet.cntop3.com],
```suggestion
    "rpc": ["https://rpc.cntop3.com"],
    "faucets": ["http://faucet.cntop3.com"],
```

2022-01-19 15:18 UTC, ligi requested changes
quotes are missing

2022-01-20 10:45 UTC, ligi requested changes
the explorer does not seem to be EIP3091 compatible - please fix or use "none"

2022-01-20 14:30 UTC, nfttoken commented
> the explorer does not seem to be EIP3091 compatible - please fix or use "none"

thanks, change to  "none" now.

2022-01-22 05:01 UTC, nfttoken commented
add "icon" today, and could you approve my PR, or what shoud I do?

2022-01-24 09:27 UTC, nfttoken commented
> **kontinuum/test ** Expected — Waiting for status to be reported
how about this "kontinuum/test Expected — Waiting for status to be reported"?  google says that  to open a new PR in branch not master could fullfil the required.   should I  try it?

2022-01-26 15:47 UTC, nfttoken reviewed
explorer change to "none",and add icon

2022-01-28 15:04 UTC, ligi requested changes
the filename must be lowercase like the others

2022-01-30 01:56 UTC, nfttoken commented
> the filename must be lowercase like the others

ok, thank  you .  
 I will close this PR, and open a new apply.  because this PR's build is failed.

2022-01-30 01:57 UTC, ligi commented
you can also just change it here - it will build again once you change it

2022-01-30 05:47 UTC, ligi commented on _data/chains/eip155-126.json
> +    "slip44": 126
```suggestion
    "slip44": 126,
```

2022-01-30 06:19 UTC, nfttoken reviewed
commit your suggest

2022-01-30 09:41 UTC, merged