Add UBC
ethereum-lists/chains pull request #790
Opened 2022-01-21 03:34 UTC by QDanlSc

2022-01-21 09:28 UTC, ligi requested changes
shortNames must be unique - also the testnet chainId/networkID is wrong

2022-01-22 01:07 UTC, QDanlSc commented
> shortNames must be unique - also the testnet chainId/networkID is wrong

has changed

2022-01-22 15:29 UTC, ligi requested changes
name must be unique - but found `UB Smart Chain` more than once

2022-01-25 21:18 UTC, ligi approved these changes

2022-01-25 21:18 UTC, merged