Create eip155-107.json
ethereum-lists/chains pull request #860
Opened 2022-02-10 00:51 UTC by nova-network-inc

Add Nebula Testnet

2022-02-10 06:48 UTC, ligi commented on _data/chains/eip155-107.json
> +  "icon": ""nebulatestnet",
```suggestion
  "icon": "nebulatestnet",
```

2022-02-10 06:54 UTC, ligi commented on _data/chains/eip155-107.json
> +    "url": "http://explorer.novanetwork.io/?network=Nebula%20Testnet",
```suggestion
    "url": "https://explorer.novanetwork.io/?network=Nebula%20Testnet",
```

2022-02-10 06:55 UTC, ligi commented
The explorer seems to not work?

2022-02-10 07:14 UTC, nova-network-inc commented
> The explorer seems to not work?
It only works with http at the moment. We have just deployed the SSL certificates. Just drop the 's' and you should be able to access it, as it's working fine.

2022-02-10 07:38 UTC, nova-network-inc commented
Have just deployed the nodes, and geth isn't directly compatible with the https protocol. We have already set up the reverse DNS for the RPCs and have just requested the SSL certificates to be signed by DigiCert through Cloudflare. Just waiting for that to kick in, and it should be accessible via HTTPS.

2022-02-10 07:40 UTC, nova-network-inc commented
And just in addition to that, the explorer has been forked from Expedition https://github.com/xops/expedition and our version of the code is also open source and accessible here https://github.com/nova-network-inc/nova-explorer

2022-02-10 07:50 UTC, nova-network-inc commented
If it's a problem we can drop the explorer info on both chains 87 and 107, and commit again when the HTTPS is working. Just let us know.

2022-02-10 08:07 UTC, ligi commented
yea - let's do that

2022-02-10 08:08 UTC, nova-network-inc commented
Can you remove it, or do you want me to recommit?

2022-02-10 08:09 UTC, ligi commented on _data/chains/eip155-107.json
> +  }]
```suggestion
  "networkId": 107
```

2022-02-10 20:24 UTC, nova-network-inc commented
Hi, I saw it has failed on the build/push, but I couldn't find anything wrong with it. Sorry, but could you perhaps shout some light on it for me? Thanks.

2022-02-13 01:35 UTC, Gunawanwahyudi21 reviewed
Good project and nice project, go to support

2022-02-13 01:36 UTC, Gunawanwahyudi21 reviewed
Good project and nice project, go to support

2022-02-14 07:38 UTC, ligi requested changes
The icon nebulatestnet does not exist

2022-02-14 19:52 UTC, nova-network-inc commented
> The icon nebulatestnet does not exist

Nope, it's all right... Perhaps you just overlooked it, or if there's something wrong I'm not seeing, please let me know. Cheers.

2022-02-15 19:54 UTC, merged