Block 0xEB for Ethereum Beacon Chain
ethereum-lists/chains pull request #94
Opened 2020-05-08 14:23 UTC by ligi

2020-05-08 14:29 UTC, ligi commented
another popular option is 0xE2 for Ethereum2.0

2020-05-08 19:17 UTC, MysticRyuujin commented
FWIW I think 0xEB makes more sense than 0xE2 given that the chain ID is for the Beacon Chain itself, assuming that shards will also require chainID.

Also an option: 0xBC 😄

2020-11-12 15:24 UTC, roninkaizen commented
👍

2020-12-22 15:42 UTC, nehtechnine requested changes
Finish

2021-03-24 21:53 UTC, ligi commented
closing - not sure anymore beacon chain actually gets a chainID

2021-03-24 21:53 UTC, closed without merging