add chain id for web3q galileo
ethereum-lists/chains pull request #979
Opened 2022-03-15 04:39 UTC by ping-ke

2022-03-15 05:50 UTC, ligi commented on _data/chains/eip155-3334.json
> +    "url": "https://explorer.galileo.web3q.io/",
```suggestion
    "url": "https://explorer.galileo.web3q.io",
```

2022-03-15 05:51 UTC, ligi requested changes
Please remove the slash

2022-03-23 02:53 UTC, ping-ke commented
> Please remove the slash
Slash has been removed.

2022-03-23 02:53 UTC, ping-ke commented
> Please remove the slash
Slash has been removed.

2022-03-23 03:41 UTC, merged